// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`E2E turn-on-all-rules 1`] = `
[1] openapi.yaml:1:1 at #/

OpenAPI servers must be present.

 1 | openapi: 3.0.0
   | ^^^^^^^^^^^^^^
 2 | info:
   | ^^^^^
 … | < 15 more lines >
18 |           description: example description
   |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error was generated by no-empty-servers rule.


[2] openapi.yaml:2:1 at #/info

Info object description must be present and non-empty string.

1 | openapi: 3.0.0
2 | info:
  | ^^^^
3 |   title: Example OpenAPI 3 definition.
4 |   version: 1.0.0

error was generated by info-description rule.


[3] openapi.yaml:2:1 at #/info

Info object should contain "contact" field.

1 | openapi: 3.0.0
2 | info:
  | ^^^^
3 |   title: Example OpenAPI 3 definition.
4 |   version: 1.0.0

error was generated by info-contact rule.


[4] openapi.yaml:2:1 at #/info

Info object should contain "license" field.

1 | openapi: 3.0.0
2 | info:
  | ^^^^
3 |   title: Example OpenAPI 3 definition.
4 |   version: 1.0.0

error was generated by info-license rule.


[5] openapi.yaml:8:5 at #/paths/~1ping~1{id}~1{test}/get

Operation object should contain "description" field.

 6 | paths:
 7 |   '/ping/{id}/{test}':
 8 |     get:
   |     ^^^
 9 |       parameters:
10 |         - in: path

error was generated by operation-description rule.


[6] openapi.yaml:11:17 at #/paths/~1ping~1{id}~1{test}/get/parameters/0/name

Path parameter \`test_id\` is not used in the path \`/ping/{id}/{test}\`.

 9 | parameters:
10 |   - in: path
11 |     name: test_id
   |           ^^^^^^^
12 |     description: User id
13 |     required: true

error was generated by path-parameters-defined rule.


[7] openapi.yaml:9:7 at #/paths/~1ping~1{id}~1{test}/get/parameters

The operation does not define the path parameter \`{id}\` expected by path \`/ping/{id}/{test}\`.

 7 | '/ping/{id}/{test}':
 8 |   get:
 9 |     parameters:
   |     ^^^^^^^^^^
10 |       - in: path
11 |         name: test_id

error was generated by path-parameters-defined rule.


[8] openapi.yaml:9:7 at #/paths/~1ping~1{id}~1{test}/get/parameters

The operation does not define the path parameter \`{test}\` expected by path \`/ping/{id}/{test}\`.

 7 | '/ping/{id}/{test}':
 8 |   get:
 9 |     parameters:
   |     ^^^^^^^^^^
10 |       - in: path
11 |         name: test_id

error was generated by path-parameters-defined rule.



❌ Validation failed with 8 errors and 0 warnings. 

run with \`--generate-exceptions\` to add all messages to exceptions file


`;
