// Generated by @redocly/client-generator — do not edit by hand.
// Source: OpenAPI document. Re-run `redocly generate-client` to update.

import { z } from "zod";

export const PageSchema = z.object({
    endCursor: z.union([z.string(), z.null()]),
    startCursor: z.union([z.string(), z.null()]),
    hasNextPage: z.boolean(),
    hasPrevPage: z.boolean(),
    limit: z.number().int().min(1).max(100),
    total: z.number().int().min(0)
});

export const MenuBaseItemSchema = z.object({
    createdAt: z.string(),
    updatedAt: z.string(),
    id: z.string().regex(new RegExp("^prd_[0-9abcdefghjkmnpqrstvwxyz]{26}$")),
    object: z.literal("menuItem"),
    name: z.string().min(1).max(50),
    price: z.number().int().min(0),
    photo: z.union([z.instanceof(Blob), z.null()]).optional(),
    photoUrl: z.string().optional(),
    photoTextDescription: z.union([z.string(), z.null()]).optional()
});

export const BeverageSchema = z.object({
    category: z.literal("beverage"),
    volume: z.number().gt(0),
    containsCaffeine: z.boolean()
}).and(z.lazy(() => MenuBaseItemSchema));

export const DessertSchema = z.object({
    category: z.literal("dessert"),
    calories: z.number().gt(0)
}).and(z.lazy(() => MenuBaseItemSchema));

export const MenuItemSchema = z.union([z.lazy(() => BeverageSchema), z.lazy(() => DessertSchema)]);

export const MenuItemListSchema = z.object({
    object: z.literal("list"),
    page: z.lazy(() => PageSchema),
    items: z.array(z.lazy(() => MenuItemSchema))
});

export const ErrorSchema = z.object({
    type: z.string(),
    title: z.string(),
    status: z.number().int().min(100).lt(600),
    instance: z.string().optional(),
    details: z.record(z.string(), z.unknown()).optional()
});

export const OrderStatusSchema = z.enum(["placed", "preparing", "completed", "canceled"]);

export const OrderSchema = z.object({
    id: z.string().regex(new RegExp("^ord_[0-9abcdefghjkmnpqrstvwxyz]{26}$")).optional(),
    object: z.literal("order").optional(),
    customerName: z.string().min(1).max(100).regex(new RegExp("^[A-Za-z]+(?:[\\s'-][A-Za-z]+)*$")),
    status: z.lazy(() => OrderStatusSchema).optional(),
    totalPrice: z.number().int().min(0).optional(),
    createdAt: z.string().optional(),
    updatedAt: z.string().optional(),
    orderItems: z.array(z.object({
        menuItemId: z.string(),
        quantity: z.number().int().min(1),
        discount: z.number().int().min(0).optional(),
        comment: z.string().max(500).optional()
    })).min(1)
});

export const OrderListSchema = z.object({
    object: z.literal("list"),
    page: z.lazy(() => PageSchema),
    items: z.array(z.lazy(() => OrderSchema))
});

export const OrderItemSchema = z.object({
    menuItemId: z.string(),
    menuItem: z.lazy(() => MenuItemSchema).optional(),
    quantity: z.number().int().min(1),
    discount: z.number().int().min(0).optional(),
    comment: z.string().max(500).optional()
});

export const RevenueStatisticsSchema = z.object({
    revenue: z.number().min(0),
    averageOrderAmount: z.number().min(0),
    totalOrders: z.number().int().min(0),
    placedOrders: z.number().int().min(0),
    preparingOrders: z.number().int().min(0),
    completedOrders: z.number().int().min(0),
    canceledOrders: z.number().int().min(0),
    startDate: z.string(),
    endDate: z.string()
});

export const RegisterClientObjectSchema = z.object({
    name: z.string(),
    redirectUris: z.array(z.string()).optional(),
    scopes: z.array(z.enum(["menu:read", "menu:write", "orders:read", "orders:write"])).optional(),
    grantTypes: z.array(z.enum(["authorization_code", "client_credentials"])).optional()
});

export const OAuth2ClientSchema = z.object({
    clientId: z.string(),
    clientSecret: z.string(),
    clientIdIssuedAt: z.number().int(),
    clientSecretExpiresAt: z.number().int(),
    name: z.string().optional(),
    redirectUris: z.array(z.string()).optional(),
    registrationClientUri: z.string(),
    registrationAccessToken: z.string(),
    scopes: z.array(z.enum(["menu:read", "menu:write", "orders:read", "orders:write"])).optional(),
    grantTypes: z.array(z.enum(["authorization_code", "client_credentials"])).optional()
});

export const OrderNotificationSchema = z.object({
    orderId: z.string(),
    orderStatus: z.lazy(() => OrderStatusSchema),
    timestamp: z.string()
});

/**
 * Request/response validators by operationId — powers `zodValidation`, or import one directly.
 */
export const operationSchemas = {
    listMenuItems: { response: z.lazy(() => MenuItemListSchema) },
    createMenuItem: { response: z.lazy(() => MenuItemSchema) },
    listOrders: { response: z.lazy(() => OrderListSchema) },
    createOrder: { request: OrderSchema.omit({ id: true, object: true, status: true, totalPrice: true, createdAt: true, updatedAt: true }), response: z.lazy(() => OrderSchema) },
    getOrderById: { response: z.lazy(() => OrderSchema) },
    updateOrder: { request: z.object({
            status: z.lazy(() => OrderStatusSchema)
        }), response: z.lazy(() => OrderSchema) },
    listOrderItems: { response: z.array(z.lazy(() => OrderItemSchema)) },
    getRevenue: { response: z.lazy(() => RevenueStatisticsSchema) },
    registerOAuth2Client: { request: z.lazy(() => RegisterClientObjectSchema), response: z.lazy(() => OAuth2ClientSchema) }
};
/** `request`/`response` validators for one operation (an absent side is not validated). */
export type OperationSchemaSet = { request?: z.ZodType; response?: z.ZodType };

const schemaIndex: Partial<Record<string, OperationSchemaSet>> = operationSchemas;

/** A request or response payload failed validation. Always thrown, even on result-mode clients. */
export class ZodValidationError extends Error {
    constructor(
        readonly operationId: string,
        readonly direction: "request" | "response",
        readonly issues: z.ZodError["issues"]
    ) {
        const detail = issues
            .map((issue) => `${issue.path.join(".") || "(root)"}: ${issue.message}`)
            .join("; ");
        super(`${direction === "request" ? "Request" : "Response"} validation failed for operation "${operationId}": ${detail}`);
        this.name = "ZodValidationError";
    }
}

/**
 * Schema-validation middleware for the generated client: `use(zodValidation())`.
 * Request bodies are validated before any network call; successful JSON responses are
 * validated against the operation's response schema. Payloads are never mutated, and
 * operations without a schema pass through untouched. A failure throws
 * `ZodValidationError` — always, even on result-mode clients.
 */
export function zodValidation(options: { request?: boolean; response?: boolean } = {}) {
    const { request = true, response = true } = options;
    return {
        onRequest(context: { body?: unknown; operation: { id: string } }): void {
            if (!request || context.body === undefined) return;
            const schema = schemaIndex[context.operation.id]?.request;
            if (!schema) return;
            const result = schema.safeParse(context.body);
            if (!result.success) {
                throw new ZodValidationError(context.operation.id, "request", result.error.issues);
            }
        },
        async onResponse(incoming: Response, context: { operation: { id: string } }): Promise<void> {
            if (!response || !incoming.ok) return;
            const schema = schemaIndex[context.operation.id]?.response;
            if (!schema) return;
            const contentType = (incoming.headers.get("content-type") ?? "").toLowerCase();
            if (!contentType.includes("json")) return;
            const result = schema.safeParse(await incoming.clone().json());
            if (!result.success) {
                throw new ZodValidationError(context.operation.id, "response", result.error.issues);
            }
        },
    };
}
