// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`E2E lint assertions-list-types 1`] = `

validating openapi.yaml...
[1] openapi.yaml:10:3 at #/servers

rule/ServerList failed because the ServerList didn't meet the assertions: Should have at most 0 characters

 8 |     url: https://opensource.org/licenses/MIT
 9 | servers: #ServerList
10 |   - url: http://petstore.swagger.io:{Port}/v1
   |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
11 |     variables:
   |     ^^^^^^^^^^
 … |     < 4 more lines >
16 |         default: '8443'
   |         ^^^^^^^^^^^^^^^
17 | security: [] # SecurityRequirementList
18 | tags: # TagList

Error was generated by the rule/ServerList rule.


[2] openapi.yaml:17:11 at #/security

rule/SecurityRequirementList failed because the SecurityRequirementList didn't meet the assertions: Should have at least 1 characters

15 |           - '443'
16 |         default: '8443'
17 | security: [] # SecurityRequirementList
   |           ^^
18 | tags: # TagList
19 |   - name: pets

Error was generated by the rule/SecurityRequirementList rule.


[3] openapi.yaml:19:3 at #/tags

rule/TagList failed because the TagList didn't meet the assertions: Should be not defined

17 | security: [] # SecurityRequirementList
18 | tags: # TagList
19 |   - name: pets
   |   ^^^^^^^^^^^^
20 |     description: Test description
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
21 |   - name: store
   |   ^^^^^^^^^^^^^
22 |     description: Access to Petstore orders
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
23 | paths:
24 |   /pets:

Error was generated by the rule/TagList rule.


openapi.yaml: validated in <test>ms

❌ Validation failed with 3 errors.
run \`redocly lint --generate-ignore-file\` to add all problems to the ignore file.


`;
