// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`E2E lint enforcements-sort-order-asc-error 1`] = `

validating /openapi.yaml...
[1] openapi.yaml:21:7 at #/paths/~1pet~1findByStatus/get/tags

Operation tags should be ordered in ASC direction

19 | operationId: example-id
20 | summary: summary example
21 | tags:
   | ^^^^
22 |   - foo
23 |   - baz

Error was generated by the enforcements rule.


/openapi.yaml: validated in <test>ms

❌ Validation failed with 1 error.
run \`openapi lint --generate-ignore-file\` to add all problems to the ignore file.


`;
