// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`E2E lint info-description-empty-warning 1`] = `

validating /openapi.yaml...
[1] openapi.yaml:5:3 at #/info/description

Info object \`description\` must be non-empty string.

3 |   title: Example OpenAPI 3 definition.
4 |   version: 1.0.0
5 |   description: 
  |   ^^^^^^^^^^^^
6 |
7 | paths:

Warning was generated by the info-description rule.


/openapi.yaml: validated in <test>ms

Woohoo! Your OpenAPI definition is valid. 🎉
You have 1 warning.


`;
