// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`E2E lint assertions-casing-sentence-case-error 1`] = `

validating /openapi.yaml...
[1] openapi.yaml:20:16 at #/paths/~1pet~1findByStatus/post/summary

Summary should be Sentencecase

18 | post:
19 |   operationId: post-ExampleId
20 |   summary: A Summary Example
   |            ^^^^^^^^^^^^^^^^^
21 |   responses:
22 |     '200':

Error was generated by the rule/summary-sentence-case rule.


[2] openapi.yaml:28:16 at #/paths/~1pet~1findByStatus/delete/summary

Summary should be Sentencecase

26 | delete: 
27 |   operationId: delete-ExampleId
28 |   summary: a third summary Example
   |            ^^^^^^^^^^^^^^^^^^^^^^^
29 |   responses:
30 |     '200':

Error was generated by the rule/summary-sentence-case rule.


/openapi.yaml: validated in <test>ms

❌ Validation failed with 2 errors.
run \`redocly lint --generate-ignore-file\` to add all problems to the ignore file.


`;
