import type { ApiModel } from '../../ir/model.js';
import { getWriter } from '../index.js';
import { singleFileWriter } from '../single-file-writer.js';
import { splitWriter } from '../split-writer.js';
import { tagsSplitWriter } from '../tags-split-writer.js';
import { tagsWriter } from '../tags-writer.js';

const model: ApiModel = {
  title: 'Tiny',
  version: '1.0.0',
  serverUrl: 'https://api.example.com',
  services: [
    {
      name: 'Default',
      operations: [
        {
          name: 'ping',
          method: 'get',
          path: '/ping',
          pathParams: [],
          queryParams: [],
          headerParams: [],
          successResponses: [],
          errorResponses: [],
          security: [],
          tags: [],
        },
      ],
    },
  ],
  schemas: [],
  securitySchemes: [],
};

describe('getWriter', () => {
  it('returns the single-file writer for the `single` mode', () => {
    expect(getWriter('single')).toBe(singleFileWriter);
  });

  it('returns the split writer for the `split` mode', () => {
    expect(getWriter('split')).toBe(splitWriter);
  });

  it('returns the tags writer for the `tags` mode', () => {
    expect(getWriter('tags')).toBe(tagsWriter);
  });

  it('returns the tags-split writer for the `tags-split` mode', () => {
    expect(getWriter('tags-split')).toBe(tagsSplitWriter);
  });
});

describe('singleFileWriter', () => {
  it('produces exactly one file at the output path containing the client', () => {
    const files = singleFileWriter({
      model,
      outputPath: '/out/api.ts',
      emit: {},
    });
    expect(files).toHaveLength(1);
    expect(files[0].path).toBe('/out/api.ts');
    expect(files[0].content).toContain('export async function ping(');
    expect(files[0].content).toContain('// Generated by @redocly/client-generator');
  });
});
