import type { ApiModel } from '../../intermediate-representation/model.js';
import { getWriter } from '../index.js';
import { singleFileWriter } from '../single-file-writer.js';
import { splitWriter } from '../split-writer.js';

const model: ApiModel = {
  title: 'Tiny',
  version: '1.0.0',
  serverUrl: 'https://api.example.com',
  services: [
    {
      name: 'Default',
      operations: [
        {
          name: 'ping',
          method: 'get',
          path: '/ping',
          pathParams: [],
          queryParams: [],
          headerParams: [],
          successResponses: [],
          errorResponses: [],
          security: [],
          tags: [],
        },
      ],
    },
  ],
  schemas: [],
  securitySchemes: [],
};

describe('getWriter', () => {
  it('returns the single-file writer for the `single` mode', () => {
    expect(getWriter('single')).toBe(singleFileWriter);
  });

  it('returns the split writer for the `split` mode', () => {
    expect(getWriter('split')).toBe(splitWriter);
  });
});

describe('singleFileWriter', () => {
  it('produces exactly one file at the output path containing the client', () => {
    const files = singleFileWriter({
      model,
      outputPath: '/out/api.ts',
      emit: {},
    });
    expect(files).toHaveLength(1);
    expect(files[0].path).toBe('/out/api.ts');
    expect(files[0].content).toContain('// Generated by @redocly/client-generator');
    // The default (inline) arm embeds the runtime and wires the descriptor client.
    expect(files[0].content).toContain('// ─── Embedded runtime');
    expect(files[0].content).toContain(
      'export const client = createClient<Ops, OperationId, OperationPath, string>(OPERATIONS,'
    );
    expect(files[0].content).toContain('export const ping = (init: RequestOptions = {})');
  });

  it('emits the package import instead of the embedded runtime for runtime: package', () => {
    const files = singleFileWriter({
      model,
      outputPath: '/out/api.ts',
      emit: { runtime: 'package' },
    });
    expect(files).toHaveLength(1);
    expect(files[0].content).toContain("from '@redocly/client-generator'");
    expect(files[0].content).not.toContain('// ─── Embedded runtime');
    // An explicit `inline` embeds.
    const inline = singleFileWriter({
      model,
      outputPath: '/out/api.ts',
      emit: { runtime: 'inline' },
    });
    expect(inline[0].content).toContain('// ─── Embedded runtime');
    expect(inline[0].content).not.toContain("from '@redocly/client-generator'");
  });
});
