import type { EmitOptions } from '../../emitters/client.js';
import type { ApiModel, OperationModel } from '../../intermediate-representation/model.js';
import { splitWriter } from '../split-writer.js';

function operation(overrides: Partial<OperationModel> = {}): OperationModel {
  return {
    name: 'op',
    method: 'get',
    path: '/p',
    pathParams: [],
    queryParams: [],
    headerParams: [],
    successResponses: [],
    errorResponses: [],
    security: [],
    tags: [],
    ...overrides,
  };
}

function model(overrides: Partial<ApiModel> = {}): ApiModel {
  return {
    title: 'Tiny',
    version: '1.0.0',
    serverUrl: 'https://api.example.com',
    services: [{ name: 'Default', operations: [] }],
    schemas: [],
    securitySchemes: [],
    ...overrides,
  };
}

const PET_MODEL = model({
  schemas: [
    {
      name: 'Pet',
      schema: {
        kind: 'object',
        properties: [{ name: 'id', schema: { kind: 'scalar', scalar: 'integer' }, required: true }],
      },
    },
    // Never referenced by an operation — must NOT be imported by the entry.
    { name: 'Unreferenced', schema: { kind: 'object', properties: [] } },
  ],
  services: [
    {
      name: 'Default',
      operations: [
        operation({
          name: 'getPet',
          path: '/pets/{id}',
          pathParams: [
            {
              name: 'id',
              in: 'path',
              schema: { kind: 'scalar', scalar: 'string' },
              required: true,
            },
          ],
          successResponses: [
            { contentType: 'application/json', status: 200, schema: { kind: 'ref', name: 'Pet' } },
          ],
        }),
      ],
    },
  ],
});

function run(m: ApiModel, emit: EmitOptions = {}) {
  const files = splitWriter({ model: m, outputPath: '/out/client.ts', emit });
  return {
    files,
    schemas: files.find((f) => f.path === '/out/client.schemas.ts'),
    entry: files.find((f) => f.path === '/out/client.ts')!,
  };
}

describe('splitWriter — file set & paths', () => {
  it('emits exactly the schemas file and the entry file', () => {
    const { files } = run(PET_MODEL);
    expect(files.map((f) => f.path)).toEqual(['/out/client.schemas.ts', '/out/client.ts']);
  });

  it('omits the schemas file entirely when the document declares no schemas', () => {
    const { files, entry } = run(
      model({ services: [{ name: 'Default', operations: [operation()] }] })
    );
    expect(files.map((f) => f.path)).toEqual(['/out/client.ts']);
    expect(entry.content).not.toContain('.schemas.js');
  });
});

describe('splitWriter — schemas module', () => {
  it('contains the model types + type guards and nothing runtime-related', () => {
    const withUnion = run(
      model({
        schemas: [
          {
            name: 'Cat',
            schema: {
              kind: 'object',
              properties: [
                { name: 'type', schema: { kind: 'literal', value: 'cat' }, required: true },
              ],
            },
          },
          {
            name: 'Dog',
            schema: {
              kind: 'object',
              properties: [
                { name: 'type', schema: { kind: 'literal', value: 'dog' }, required: true },
              ],
            },
          },
          {
            name: 'Animal',
            schema: {
              kind: 'union',
              members: [
                { kind: 'ref', name: 'Cat' },
                { kind: 'ref', name: 'Dog' },
              ],
            },
          },
        ],
      })
    );
    const schemas = withUnion.schemas!.content;
    expect(schemas).toContain('// Generated by @redocly/client-generator');
    expect(schemas).toContain('export type Cat = {');
    expect(schemas).toContain('export function isCat(');
    expect(schemas).not.toContain('createClient');
    expect(schemas).not.toContain('OPERATIONS');
  });
});

describe('splitWriter — entry (inline runtime, the default)', () => {
  it('embeds the runtime, re-exports the schemas module, and imports only referenced schema types', () => {
    const { entry } = run(PET_MODEL);
    expect(entry.content).toContain("import type { Pet } from './client.schemas.js';");
    expect(entry.content).toContain("export * from './client.schemas.js';");
    // `Unreferenced` is exported via the `export *` but never imported by name.
    expect(entry.content).not.toContain('Unreferenced }');
    expect(entry.content).toContain('// ─── Embedded runtime');
    expect(entry.content).toContain(
      'export const client = createClient<Ops, OperationId, OperationPath, string>(OPERATIONS,'
    );
    expect(entry.content).toContain('export const { configure, use } = client;');
    expect(entry.content).toContain(
      'export const getPet = (id: string, init: RequestOptions = {}) => client.getPet({ id }, init);'
    );
    // The schema types themselves live only in the schemas module.
    expect(entry.content).not.toContain('export type Pet = {');
  });

  it('skips the type import when no schema name is referenced by the entry code', () => {
    const { entry, schemas } = run(
      model({
        schemas: [{ name: 'Orphan', schema: { kind: 'object', properties: [] } }],
        services: [{ name: 'Default', operations: [operation({ name: 'ping' })] }],
      })
    );
    expect(schemas!.content).toContain('export type Orphan');
    expect(entry.content).toContain("export * from './client.schemas.js';");
    expect(entry.content).not.toContain('import type {');
  });
});

describe('splitWriter — entry (package runtime)', () => {
  it('imports the runtime from the package and keeps the schemas linkage + re-export tail', () => {
    const { entry, schemas } = run(PET_MODEL, { runtime: 'package' });
    expect(schemas!.content).toContain('export type Pet = {');
    expect(entry.content).toContain("import type { Pet } from './client.schemas.js';");
    expect(entry.content).toContain("export * from './client.schemas.js';");
    expect(entry.content).toContain("from '@redocly/client-generator';");
    expect(entry.content).not.toContain('// ─── Embedded runtime');
    expect(entry.content).toContain(
      "export { ApiError, createClient } from '@redocly/client-generator';"
    );
  });
});

describe('splitWriter — SSE', () => {
  it('keeps SSE descriptors + flat sugar in the entry file', () => {
    const { entry } = run(
      model({
        schemas: [{ name: 'Message', schema: { kind: 'object', properties: [] } }],
        services: [
          {
            name: 'Default',
            operations: [
              operation({
                name: 'streamMessages',
                path: '/stream',
                successResponses: [
                  {
                    contentType: 'text/event-stream',
                    status: 200,
                    schema: { kind: 'unknown' },
                    itemSchema: { kind: 'ref', name: 'Message' },
                  },
                ],
              }),
            ],
          },
        ],
      })
    );
    expect(entry.content).toContain('responseKind: "sse"');
    expect(entry.content).toContain(
      'export const streamMessages = (init: SseOptions = {}) => client.streamMessages({}, init);'
    );
    // The streamed event type is imported from the schemas module (Ops references it).
    expect(entry.content).toContain("import type { Message } from './client.schemas.js';");
  });
});
