// The built-in `php` generator — the third non-TypeScript library entry, authored
// with the language-neutral toolkit only (same dogfooding invariant as python/go,
// pinned by the guard test). Output is a single PHP >= 8.1 file over the curl
// extension: promoted-constructor classes with fromArray/toArray hydration, native
// backed enums, match-based discriminator dispatchers, and a Client over the
// embedded runtime. Exceptions are the error mode (`errorMode` does not apply).

import {
  type CodeSample,
  type Generator,
  identifierFor,
  jsonSuccessSchema,
  type NeutralPaginationRule,
  type OperationModel,
  paginationItemSchema,
  renderReferencePage,
  type SampleContext,
  sseResponse,
} from '@redocly/client-generator';
import { PhpPrinter } from '@redocly/client-generator/printers/php';
import { PHP_RUNTIME_SOURCE } from '@redocly/client-generator/runtime-sources';

import { writeServers } from './client.js';
import { phpPaginationLiteral, phpSecurityLiteral } from './descriptor.js';
import { hydration, renderPhpModels } from './models.js';
import { methodIdents, methodName, PHP, phpString, propertyName } from './naming.js';
import { writePhpMethod } from './operations.js';
import { writePhpPaginationWrappers } from './pagination.js';
import { phpType } from './types.js';

export { renderPhpModels } from './models.js';
export { phpType } from './types.js';

/** Drop the standalone header (<?php, declare, namespace, leading comments) for stitching. */
function stripPhpHeader(source: string): string {
  const lines = source.split('\n');
  let start = 0;
  for (let index = 0; index < lines.length; index++) {
    const line = lines[index].trim();
    if (line.startsWith('namespace ')) {
      start = index + 1;
      break;
    }
  }
  return lines.slice(start).join('\n').trim();
}

/** The whole generated file: namespace + models + embedded runtime + operations + Client. */
export const phpGenerator: Generator = ({ model, output, banner, emit, pagination }) => {
  const printer = new PhpPrinter();
  const dateType = emit.dateType ?? 'string';
  const namespace = identifierFor(model.title, { style: 'pascal', reserved: PHP });
  printer.line('<?php');
  printer.blank();
  printer.line(
    `// Code generated by @redocly/client-generator (php) from ${phpString(model.title)} ${model.version}. DO NOT EDIT.`
  );
  printer.line(
    '// Regenerate with `redocly generate-client`. PHP >= 8.1, curl extension — zero Composer dependencies.'
  );
  printer.blank();
  printer.line('declare(strict_types=1);');
  printer.blank();
  printer.line(`namespace ${namespace};`);
  printer.blank();
  printer.line(renderPhpModels(model, dateType));
  writeServers(printer, model);
  if (emit.runtime === 'module') {
    // The runtime file re-declares this same namespace, so the require binds the
    // exact names the inline stitching would have defined at this position.
    printer.line('// ─── Runtime (a real file beside this one, written by the same run) ───');
    printer.line("require_once __DIR__ . '/runtime.php';");
    printer.blank();
  } else {
    printer.line('// ─── Embedded runtime (@redocly/client-generator php runtime) ───');
    printer.line(stripPhpHeader(PHP_RUNTIME_SOURCE));
    printer.blank();
  }

  const operations = model.services.flatMap((service) => service.operations);
  const idents = methodIdents(model);
  // Pagination arrives RESOLVED from the pipeline — one fit-verified answer per run.
  const paginationRules = new Map<string, NeutralPaginationRule>();
  for (const op of operations) {
    const spec = pagination?.get(op.name)?.spec;
    if (spec !== undefined) paginationRules.set(op.name, spec);
  }

  printer.block(
    'const OPERATIONS = [',
    () => {
      for (const op of operations) {
        const id = op.specName ?? op.name;
        const security = phpSecurityLiteral(op, model);
        const rule = paginationRules.get(op.name);
        const fields = [
          `'id' => ${phpString(id)}`,
          `'method' => ${phpString(op.method.toUpperCase())}`,
          `'path' => ${phpString(op.path)}`,
          ...(security !== undefined ? [`'security' => ${security}`] : []),
          ...(rule !== undefined ? [`'pagination' => ${phpPaginationLiteral(rule)}`] : []),
        ];
        printer.line(`${phpString(id)} => [${fields.join(', ')}],`);
      }
    },
    '];'
  );
  printer.blank();

  printer.doc('Client', `Client for ${model.title} (${model.version}).`);
  // Not final: PHP test suites mock concrete classes (createMock(Client::class)).
  printer.line('class Client');
  printer.block(
    '{',
    () => {
      printer.line('public function __construct(private Config $config)');
      printer.block(
        '{',
        () => {
          printer.block(
            "if ($this->config->serverUrl === '') {",
            () => {
              printer.line(
                `$this->config->serverUrl = ${phpString(emit.serverUrl ?? model.serverUrl ?? '')};`
              );
            },
            '}'
          );
        },
        '}'
      );
      printer.blank();

      for (const op of operations) {
        const ident = idents.get(op.name)!;
        writePhpMethod(printer, op, ident, model, dateType);
        if (sseResponse(op) === undefined && (op.successResponseHeaders?.length ?? 0) > 0) {
          writePhpMethod(printer, op, ident, model, dateType, true);
        }
        const rule = paginationRules.get(op.name);
        if (rule === undefined) continue;
        const success = jsonSuccessSchema(op);
        const pageHydration =
          success === undefined ? undefined : hydration(success, '$page', model, dateType);
        const element = paginationItemSchema(success, rule.items, model);
        const itemHydration =
          element === undefined ? undefined : hydration(element, '$item', model, dateType);
        writePhpPaginationWrappers(
          printer,
          op,
          ident,
          model,
          dateType,
          pageHydration,
          itemHydration,
          rule.items,
          element === undefined ? 'mixed' : phpType(element, model, dateType)
        );
      }
    },
    '}'
  );

  const entry = { path: output.path.replace(/\.[^.\\/]+$/, '.php'), content: printer.toString() };
  if (emit.runtime !== 'module') return [entry];
  // The runtime, verbatim except its namespace: rewritten to the client's, so one
  // namespace spans both files and every bare reference resolves unchanged.
  const header = banner.map((line) => `// ${line}`).join('\n');
  const runtimeSource = PHP_RUNTIME_SOURCE.replace(/^namespace .*$/m, `namespace ${namespace};`)
    .replace(/^<\?php\n/, `<?php\n\n${header}\n`)
    .trimEnd();
  return [
    entry,
    { path: entry.path.replace(/[^\\/]+$/, 'runtime.php'), content: `${runtimeSource}\n` },
  ];
};

/** One idiomatic PHP call per operation — feeds `x-codeSamples` for docs. */
export function phpSample(op: OperationModel, ctx: SampleContext): CodeSample {
  const args = [
    ...op.pathParams.map((param) => `${phpString(`<${propertyName(param.name)}>`)}`),
    ...(op.requestBody ? ['$body'] : []),
    ...(op.queryParams.length > 0
      ? [`${propertyName(op.queryParams[0].name)}: ${phpString('<value>')}`]
      : []),
  ];
  const namespace = identifierFor(ctx.model.title, { style: 'pascal', reserved: PHP });
  // The file this run writes, so the snippet requires something that exists.
  const file = ctx.outputPath.replace(/^.*[\\/]/, '').replace(/\.[^.]+$/, '.php');
  return {
    lang: 'php',
    label: 'PHP SDK',
    source: `require '${file}';\n\nuse ${namespace}\\{Client, Config};\n\n$client = new Client(new Config());\n$result = $client->${methodIdents(ctx.model).get(op.name) ?? methodName(op)}(${args.join(', ')});\n`,
  };
}

/**
 * The SDK's own reference page, written when `client.docs` is on. The call snippets come
 * from `phpSample` — this generator's own hook — so the page can only ever show the syntax
 * of the SDK beside it, and ejecting this generator takes the page with it.
 */
export const phpDocs: Generator = ({ model, output, emit, pagination }) => [
  {
    path: output.path.replace(/\.[^.\\/]+$/, '.php.md'),
    content: renderReferencePage(model, {
      title: `${model.title} PHP SDK reference`,
      frontmatter: emit.docsFrontmatter === true,
      language: {
        name: 'php',
        label: 'PHP',
        fence: 'php',
        requires: 'The SDK needs the curl extension.',
      },
      sample: (op) => phpSample(op, { model, emit, outputPath: output.path }),
      paginated: new Set(pagination?.keys() ?? []),
    }),
  },
];
