import { apiModel, namedSchema, operation, response } from '../../emitters/__tests__/fixtures.js';
import { mockGenerator } from '../mock.js';

describe('mockGenerator', () => {
  it('returns [] for a model with no operations', () => {
    const result = mockGenerator({
      model: apiModel(),
      outputPath: '/out/client.ts',
      outputMode: 'single',
      emit: {},
    });
    expect(result).toEqual([]);
  });

  it('returns a single mocks file when the model has operations', () => {
    const model = apiModel({ services: [{ name: 'Default', operations: [operation()] }] });
    const result = mockGenerator({
      model,
      outputPath: '/out/client.ts',
      outputMode: 'single',
      emit: {},
    });
    expect(result).toHaveLength(1);
    expect(result[0].path).toBe('/out/client.mocks.ts');
    expect(result[0].content).toContain('Generated by @redocly/client-generator');
    expect(result[0].content).toContain("import { http, HttpResponse } from 'msw'");
  });

  it('imports schema types by their emitted names — a lowercase schema stays lowercase', () => {
    const model = apiModel({
      services: [
        {
          name: 'Default',
          operations: [
            operation({
              name: 'getPet',
              successResponses: [response({ schema: { kind: 'ref', name: 'pet' } })],
            }),
          ],
        },
      ],
      schemas: [
        namedSchema('pet', {
          kind: 'object',
          properties: [
            { name: 'id', schema: { kind: 'scalar', scalar: 'string' }, required: true },
          ],
        }),
      ],
    });
    const [file] = mockGenerator({
      model,
      outputPath: '/out/client.ts',
      outputMode: 'single',
      emit: {},
    });
    // The sdk exports the type verbatim (`pet`); the import and every type reference must match.
    expect(file.content).toContain('import type { pet }');
    expect(file.content).toContain('Partial<pet>');
    expect(file.content).not.toContain('Pet }');
    // Factory names are locally derived, so they keep the readable PascalCase.
    expect(file.content).toContain('createPet');
  });
});
