import { apiModel, operation } from '../../emitters/__tests__/fixtures.js';
import { mockGenerator } from '../mock.js';

describe('mockGenerator', () => {
  it('returns [] for a model with no operations', () => {
    const result = mockGenerator({
      model: apiModel(),
      outputPath: '/out/client.ts',
      outputMode: 'single',
      emit: {},
    });
    expect(result).toEqual([]);
  });

  it('returns a single mocks file when the model has operations', () => {
    const model = apiModel({ services: [{ name: 'Default', operations: [operation()] }] });
    const result = mockGenerator({
      model,
      outputPath: '/out/client.ts',
      outputMode: 'single',
      emit: {},
    });
    expect(result).toHaveLength(1);
    expect(result[0].path).toBe('/out/client.mocks.ts');
    expect(result[0].content).toContain('Generated by @redocly/client-generator');
    expect(result[0].content).toContain("import { http, HttpResponse } from 'msw'");
  });
});
