import { apiModel, operation } from '../../emitters/__tests__/fixtures.js';
import { builtinGenerators } from '../index.js';
import { tanstackQueryGenerator as tanstackQueryGeneratorEntry } from '../tanstack-query/index.js';
import { generatorInput } from './fixtures/generator-input.js';

// The pipeline parses the output anchor; `generatorInput` mirrors it for direct calls.
const tanstackQueryGenerator =
  (framework: Parameters<typeof tanstackQueryGeneratorEntry>[0]) =>
  (input: Parameters<typeof generatorInput>[0]) =>
    tanstackQueryGeneratorEntry(framework)(generatorInput(input));

const SERVICES = [
  {
    name: 'Default',
    operations: [
      operation({ name: 'getPet', method: 'get', path: '/pet' }),
      operation({ name: 'createPet', method: 'post', path: '/pet' }),
    ],
  },
];

describe('tanstackQueryGenerator', () => {
  it('emits one <stem>.tanstack.ts file beside the client with the header + factories', () => {
    const files = tanstackQueryGenerator('react')({
      model: apiModel({ services: SERVICES }),
      outputPath: '/tmp/out/client.ts',
      outputMode: 'single',
      emit: {},
    });
    expect(files).toHaveLength(1);
    expect(files[0].path).toBe('/tmp/out/client.tanstack.ts');
    expect(files[0].content).toContain('// Generated by @redocly/client-generator');
    expect(files[0].content).toContain('import { queryOptions } from "@tanstack/react-query"');
    expect(files[0].content).toContain('export const getPetOptions');
    expect(files[0].content).toContain('export const createPetMutation');
    expect(files[0].content).toContain('from "./client.js"');
  });

  it('emits nothing when the model has no operations', () => {
    const files = tanstackQueryGenerator('react')({
      model: apiModel({ services: [{ name: 'Default', operations: [] }] }),
      outputPath: '/tmp/out/client.ts',
      outputMode: 'single',
      emit: {},
    });
    expect(files).toEqual([]);
  });

  it('imports the sdk entry with a .ts extension when importExt is ts', () => {
    const files = tanstackQueryGenerator('react')({
      model: apiModel({ services: SERVICES }),
      outputPath: '/tmp/out/client.ts',
      outputMode: 'single',
      emit: { importExt: 'ts' },
    });
    expect(files[0].content).toContain('from "./client.ts"');
  });

  it('binds the framework per registry name — bare tanstack-query stays React', () => {
    const registry = builtinGenerators();
    const input = generatorInput({
      model: apiModel({ services: SERVICES }),
      outputPath: '/tmp/out/client.ts',
      outputMode: 'single' as const,
      emit: {},
    });
    const importOf = (name: string) =>
      registry
        .get(name)!
        .run(input)[0]
        .content.match(/@tanstack\/[a-z]+-query/)![0];
    expect(importOf('tanstack-query')).toBe('@tanstack/react-query');
    expect(importOf('tanstack-query-vue')).toBe('@tanstack/vue-query');
    expect(importOf('tanstack-query-svelte')).toBe('@tanstack/svelte-query');
    expect(importOf('tanstack-query-solid')).toBe('@tanstack/solid-query');
  });

  it('registers every framework variant with the sdk/throw contract', () => {
    const registry = builtinGenerators();
    for (const name of [
      'tanstack-query',
      'tanstack-query-vue',
      'tanstack-query-svelte',
      'tanstack-query-solid',
    ]) {
      const descriptor = registry.get(name);
      expect(descriptor?.requires, name).toEqual(['typescript']);
      expect(descriptor?.errorModes, name).toEqual(['throw']);
    }
  });
});
