import { apiModel, namedSchema } from '../../emitters/__tests__/fixtures.js';
import { getGenerator } from '../index.js';
import { transformersGenerator } from '../transformers.js';

const EVENT = namedSchema('Event', {
  kind: 'object',
  properties: [
    {
      name: 'createdAt',
      schema: { kind: 'scalar', scalar: 'string', metadata: { format: 'date-time' } },
      required: true,
    },
  ],
});

const PLAIN = namedSchema('Plain', {
  kind: 'object',
  properties: [{ name: 'id', schema: { kind: 'scalar', scalar: 'string' }, required: true }],
});

describe('transformersGenerator', () => {
  it('emits one <stem>.transformers.ts beside the client with header + type import + transformer', () => {
    const files = transformersGenerator({
      model: apiModel({ schemas: [EVENT] }),
      outputPath: '/tmp/out/client.ts',
      outputMode: 'single',
      emit: {},
    });
    expect(files).toHaveLength(1);
    expect(files[0].path).toBe('/tmp/out/client.transformers.ts');
    expect(files[0].content).toContain('// Generated by @redocly/client-generator');
    expect(files[0].content).toContain('import type {');
    expect(files[0].content).toContain('from "./client.js"');
    expect(files[0].content).toContain('export const transformEvent');
    expect(files[0].content).toContain('new Date(');
  });

  it('emits nothing when no schema carries a date field', () => {
    const files = transformersGenerator({
      model: apiModel({ schemas: [PLAIN] }),
      outputPath: '/tmp/out/client.ts',
      outputMode: 'single',
      emit: {},
    });
    expect(files).toEqual([]);
  });

  it('is registered under "transformers"', () => {
    expect(getGenerator('transformers').run).toBe(transformersGenerator);
  });
});
