import { apiModel, namedSchema } from '../../emitters/__tests__/fixtures.js';
import { builtinGenerators } from '../index.js';
import { transformersGenerator } from '../transformers.js';

const EVENT = namedSchema('Event', {
  kind: 'object',
  properties: [
    {
      name: 'createdAt',
      schema: { kind: 'scalar', scalar: 'string', metadata: { format: 'date-time' } },
      required: true,
    },
  ],
});

const PLAIN = namedSchema('Plain', {
  kind: 'object',
  properties: [{ name: 'id', schema: { kind: 'scalar', scalar: 'string' }, required: true }],
});

describe('transformersGenerator', () => {
  it('emits one <stem>.transformers.ts beside the client with header + type import + transformer', () => {
    const files = transformersGenerator({
      model: apiModel({ schemas: [EVENT] }),
      outputPath: '/tmp/out/client.ts',
      outputMode: 'single',
      emit: {},
    });
    expect(files).toHaveLength(1);
    expect(files[0].path).toBe('/tmp/out/client.transformers.ts');
    expect(files[0].content).toContain('// Generated by @redocly/client-generator');
    expect(files[0].content).toContain('import type {');
    expect(files[0].content).toContain('from "./client.js"');
    expect(files[0].content).toContain('export const transformEvent');
    expect(files[0].content).toContain('new Date(');
  });

  it('references schema types by their emitted names — a lowercase schema stays lowercase', () => {
    const files = transformersGenerator({
      model: apiModel({
        schemas: [
          namedSchema('pet', {
            kind: 'object',
            properties: [
              {
                name: 'bornAt',
                schema: { kind: 'scalar', scalar: 'string', metadata: { format: 'date-time' } },
                required: true,
              },
            ],
          }),
        ],
      }),
      outputPath: '/tmp/out/client.ts',
      outputMode: 'single',
      emit: {},
    });
    // The sdk exports the type verbatim (`pet`); the import and signature must match.
    expect(files[0].content).toContain('import type { pet }');
    expect(files[0].content).toContain('(data: pet): pet');
    expect(files[0].content).not.toContain('Pet }');
    // The transform function name is locally derived, so it keeps the readable PascalCase.
    expect(files[0].content).toContain('export const transformPet');
  });

  it('emits nothing when no schema carries a date field', () => {
    const files = transformersGenerator({
      model: apiModel({ schemas: [PLAIN] }),
      outputPath: '/tmp/out/client.ts',
      outputMode: 'single',
      emit: {},
    });
    expect(files).toEqual([]);
  });

  it('is registered under "transformers"', () => {
    expect(builtinGenerators().get('transformers')?.run).toBe(transformersGenerator);
  });
});
