import { apiModel, namedSchema } from '../../__tests__/fixtures.js';
import { zodGenerator as zodGeneratorEntry } from '../zod/index.js';
import { generatorInput } from './fixtures/generator-input.js';

// The pipeline parses the output anchor; `generatorInput` mirrors it for direct calls.
const zodGenerator = (input: Parameters<typeof generatorInput>[0]) =>
  zodGeneratorEntry(generatorInput(input));

const PET = namedSchema('Pet', {
  kind: 'object',
  properties: [{ name: 'id', schema: { kind: 'scalar', scalar: 'string' }, required: true }],
});

describe('zodGenerator', () => {
  it('emits one <stem>.zod.ts file beside the client with the header + schemas', () => {
    const files = zodGenerator({
      model: apiModel({ schemas: [PET] }),
      outputPath: '/tmp/out/client.ts',
      outputMode: 'single',
      emit: {},
    });
    expect(files).toHaveLength(1);
    expect(files[0].path).toBe('/tmp/out/client.zod.ts');
    expect(files[0].content).toContain('// Generated by @redocly/client-generator');
    expect(files[0].content).toContain('import { z } from "zod"');
    expect(files[0].content).toContain('export const PetSchema = z.object(');
  });

  it('emits nothing when the model has no schemas', () => {
    const files = zodGenerator({
      model: apiModel({ schemas: [] }),
      outputPath: '/tmp/out/client.ts',
      outputMode: 'single',
      emit: {},
    });
    expect(files).toEqual([]);
  });
});
