import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { collectGeneratedFiles, generateClient } from '../index.js';
import type { ApiModel } from '../ir/model.js';

function model(): ApiModel {
  return {
    title: 'T',
    version: '1',
    serverUrl: 'https://x',
    services: [{ name: 'Default', operations: [] }],
    schemas: [],
    securitySchemes: [],
  };
}

describe('collectGeneratedFiles', () => {
  it('runs the given generators and concatenates their files', () => {
    const files = collectGeneratedFiles(model(), {
      outputPath: '/out/api.ts',
      outputMode: 'single',
      emit: {},
      generators: ['sdk'],
    });
    expect(files.length).toBe(1);
    expect(files[0].path).toBe('/out/api.ts');
  });

  it('throws when two generators emit the same path', () => {
    expect(() =>
      collectGeneratedFiles(model(), {
        outputPath: '/out/api.ts',
        outputMode: 'single',
        emit: {},
        generators: ['sdk', 'sdk'],
      })
    ).toThrow(/already emitted/);
  });
});

describe('generateClient — end-to-end orchestration', () => {
  let workDir: string;

  beforeEach(async () => {
    workDir = await mkdtemp(join(tmpdir(), 'client-gen-index-'));
  });

  afterEach(async () => {
    await rm(workDir, { recursive: true, force: true });
  });

  it('writes the generated file to disk and reports its size', async () => {
    const api = join(workDir, 'spec.yaml');
    await writeFile(
      api,
      `openapi: 3.0.3
info:
  title: Tiny
  version: 1.0.0
paths:
  /ping:
    get:
      operationId: ping
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: { type: string }
`,
      'utf-8'
    );

    const output = join(workDir, 'nested/dir/api.ts');
    const result = await generateClient({ api, output });

    expect(result.outputPath).toBe(output);
    expect(result.bytes).toBeGreaterThan(0);

    const contents = await readFile(output, 'utf-8');
    expect(contents).toContain('export async function ping(');
    expect(contents).toContain('// Generated by @redocly/client-generator');
    // bytes should match what we wrote.
    expect(result.bytes).toBe(Buffer.byteLength(contents, 'utf-8'));
  });

  it('emits the result shape when errorMode is `result`', async () => {
    const api = join(workDir, 'errmode.yaml');
    await writeFile(
      api,
      `openapi: 3.0.3
info:
  title: Tiny
  version: 1.0.0
paths:
  /ping:
    get:
      operationId: ping
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: { type: string }
`,
      'utf-8'
    );

    const resultOutput = join(workDir, 'result.ts');
    await generateClient({ api, output: resultOutput, errorMode: 'result' });
    const resultContents = await readFile(resultOutput, 'utf-8');
    expect(resultContents).toContain('__requestResult');
    expect(resultContents).toContain('export type Result<');

    const throwOutput = join(workDir, 'throw.ts');
    await generateClient({ api, output: throwOutput });
    const throwContents = await readFile(throwOutput, 'utf-8');
    expect(throwContents).not.toContain('__requestResult');
    expect(throwContents).not.toContain('export type Result<');
  });

  it('normalizes a Swagger 2.0 document before generating', async () => {
    const api = join(workDir, 'swagger2.yaml');
    await writeFile(
      api,
      `swagger: '2.0'
info:
  title: Tiny2
  version: 1.0.0
host: api.example.com
basePath: /v1
schemes: [https]
consumes: [application/json]
produces: [application/json]
paths:
  /items:
    get:
      operationId: listItems
      parameters:
        - { name: page, in: query, required: false, type: integer }
      responses:
        '200':
          description: ok
          schema: { $ref: '#/definitions/Item' }
definitions:
  Item:
    type: object
    properties:
      id: { type: integer }
`,
      'utf-8'
    );

    const output = join(workDir, 'api2.ts');
    const result = await generateClient({ api, output });

    expect(result.bytes).toBeGreaterThan(0);
    const contents = await readFile(output, 'utf-8');
    expect(contents).toContain('export async function listItems(');
    expect(contents).toContain('export type Item');
    expect(contents).toContain('let BASE = "https://api.example.com/v1"');
  });
});
