// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`E2E operation-description-rule 1`] = `
[1] openapi.yaml:8:5 at #/paths/~1ping/get

Operation object should contain "description" field.

 6 | paths:
 7 |   '/ping':
 8 |     get:
   |     ^^^
 9 |       responses:
10 |         '200':

warning was generated by operation-description rule.



Woohoo! Your OpenAPI definition is valid 🎉
You have 1 warning 


`;
