// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`E2E operation-2xx-response-warning 1`] = `
[1] openapi.yaml:9:7 at #/paths/~1ping/get/responses

Operation must have at least one \`2xx\` response.

 7 | '/ping':
 8 |   get:
 9 |     responses:
   |     ^^^^^^^^^
10 |       '400':
11 |         description: example description

warning was generated by operation-2xx-response rule.



Woohoo! Your OpenAPI definition is valid 🎉
You have 1 warning 


`;
