// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`E2E lint-config invalid-definition-and-config 1`] = `

[1] .redocly.yaml:5:3 at #/rules/context

Property \`context\` is not expected here.

3 |     root: ./openapi.yaml
4 | rules:
5 |   context: null
  |   ^^^^^^^
6 | extends:
7 |   - recommended

Error was generated by the configuration spec rule.


❌ Your config has 1 error.


`;
