// Generated by the nested-facade custom generator. Do not edit by hand.
import { getOrder, listMenuItems, listOrders } from './client.js';

export const orders = { listOrders, getOrder } as const;
export const menu = { listMenuItems } as const;

export const api = { orders, menu } as const;
