// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`E2E lint assertions-ref-pattern-error 1`] = `

validating /openapi.yaml...
[1] openapi.yaml:39:17 at #/paths/~1pets/get/responses/200/content/application~1json/schema

Response MediaType schema should contain ref to components folder

37 |     application/json:
38 |       schema:
39 |         $ref: "#/components/schemas/Pets"
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
40 | default:
41 |   description: unexpected error

Error was generated by the ref assertion rule.


/openapi.yaml: validated in <test>ms

❌ Validation failed with 1 error.
run \`openapi lint --generate-ignore-file\` to add all problems to the ignore file.


`;
