// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`E2E lint test-unused-component 1`] = `

No configurations were defined in extends -- using built in recommended configuration by default.

validating /openapi.yaml...
[1] openapi.yaml:1:1 at #/

Servers must be present.

 1 | openapi: 3.1.0
   | ^^^^^^^^^^^^^^
 2 | info:
   | ^^^^^
 … | < 10 more lines >
13 |           description: example description
   |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
14 |

Error was generated by the no-empty-servers rule.


[2] openapi.yaml:4:12 at #/info/version

Expected type \`string\` but got \`number\`.

2 | info:
3 |   title: Example OpenAPI 3 definition.
4 |   version: 1.0
  |            ^^^
5 |
6 | paths:

Error was generated by the spec rule.


[3] openapi.yaml:3:3 at #/info

Info object should contain \`license\` field.

1 | openapi: 3.1.0
2 | info:
3 |   title: Example OpenAPI 3 definition.
  |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
4 |   version: 1.0
  |   ^^^^^^^^^^^^
5 |
6 | paths:

Warning was generated by the info-license rule.


/openapi.yaml: validated in <test>ms

❌ Validation failed with 2 errors and 1 warning.
run \`openapi lint --generate-ignore-file\` to add all problems to the ignore file.


`;
