// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`E2E lint arazzo-type-extensions-with-plugin 1`] = `

validating museum.yaml...
[1] museum.yaml:8:3 at #/info/wrong-key

Property \`wrong-key\` is not expected here.

 6 |   and information. Built with love by Redocly.
 7 | version: 1.0.0
 8 | wrong-key: wrong-value
   | ^^^^^^^^^
 9 | metadata:
10 |   lifecycle: production

Error was generated by the spec rule.


museum.yaml: validated in <test>ms

❌ Validation failed with 1 error.
run \`redocly lint --generate-ignore-file\` to add all problems to the ignore file.


`;
