// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`E2E lint parameter-description-warning 1`] = `

validating /openapi.yaml...
[1] openapi.yaml:28:9 at #/paths/~1ping/parameters/0

Parameter object description must be present.

26 | '/ping':
27 |   parameters:
28 |     - in: path
   |       ^^^^^^^^
29 |       name: id
   |       ^^^^^^^^
 … |       < 2 more lines >
32 |       required: true
   |       ^^^^^^^^^^^^^^
33 |   get:
34 |     operationId: getPing

Warning was generated by the parameter-description rule.


[2] openapi.yaml:37:11 at #/paths/~1ping/get/parameters/0

Parameter object description must be present.

35 | summary: Example summary
36 | parameters:
37 |   - in: path
   |     ^^^^^^^^
38 |     name: userId
   |     ^^^^^^^^^^^^
 … |     < 2 more lines >
41 |     required: true
   |     ^^^^^^^^^^^^^^
42 | responses:
43 |   '200':

Warning was generated by the parameter-description rule.


[3] openapi.yaml:8:5 at #/components/parameters/offsetParam

Parameter object description must be present.

 6 | components:
 7 |   parameters:
 8 |     offsetParam:
   |     ^^^^^^^^^^^
 9 |       in: query
10 |       name: offset

Warning was generated by the parameter-description rule.


[4] openapi.yaml:15:5 at #/components/parameters/limitParam

Parameter object description must be present.

13 |     type: integer
14 |     minimum: 0
15 | limitParam:
   | ^^^^^^^^^^
16 |   in: query
17 |   name: limit

Warning was generated by the parameter-description rule.


/openapi.yaml: validated in <test>ms

Woohoo! Your API description is valid. 🎉
You have 4 warnings.


`;
