// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`E2E lint-config test with option: { dirName: 'invalid-config--lint-config-error', option: 'error' } 1`] = `

[1] .redocly.yaml:6:3 at #/rules/context

Property \`context\` is not expected here.

4 |
5 | rules:
6 |   context:
  |   ^^^^^^^^
7 |

Error was generated by the configuration spec rule.


❌ Your config has 1 error.


`;
