// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`E2E lint assertions-camel-case-twice 1`] = `

validating openapi.yaml...
[1] openapi.yaml:26:5 at #/components/parameters/header_roleCode

Parameters must use camelCase

24 | components:
25 |   parameters:
26 |     header_roleCode:
   |     ^^^^^^^^^^^^^^^
27 |       description: Some role description
28 |       name: roleCode

Warning was generated by the rule/named-parameters-camelCase rule.


[2] openapi.yaml:33:5 at #/components/parameters/header_Accept

Parameters must use camelCase

31 |   schema:
32 |     type: string
33 | header_Accept:
   | ^^^^^^^^^^^^^
34 |   name: Accept
35 |   in: header

Warning was generated by the rule/named-parameters-camelCase rule.


openapi.yaml: validated in <test>ms

Woohoo! Your API description is valid. 🎉
You have 2 warnings.


`;
