// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`E2E parameter-description-warning 1`] = `

validating /openapi.yaml...
[1] openapi.yaml:30:9 at #/paths/~1ping/parameters/0

Parameter object description must be present.

28 | '/ping':
29 |   parameters:
30 |     - in: path
   |       ^^^^^^^^
31 |       name: id
   |       ^^^^^^^^
 … |       < 2 more lines >
34 |       required: true
   |       ^^^^^^^^^^^^^^
35 |       #description: The user ID.
36 |   get:

Warning was generated by the parameter-description rule.


[2] openapi.yaml:40:11 at #/paths/~1ping/get/parameters/0

Parameter object description must be present.

38 | summary: Example summary
39 | parameters:
40 |   - in: path
   |     ^^^^^^^^
41 |     name: userId
   |     ^^^^^^^^^^^^
 … |     < 2 more lines >
44 |     required: true
   |     ^^^^^^^^^^^^^^
45 |     #description: Numeric ID of the user to get
46 | responses:

Warning was generated by the parameter-description rule.


[3] openapi.yaml:8:5 at #/components/parameters/offsetParam

Parameter object description must be present.

 6 | components:
 7 |   parameters:
 8 |     offsetParam:
   |     ^^^^^^^^^^^
 9 |       in: query
10 |       name: offset

Warning was generated by the parameter-description rule.


[4] openapi.yaml:16:5 at #/components/parameters/limitParam

Parameter object description must be present.

14 |     minimum: 0
15 |   #description: The number of items to skip before starting to collect the result set.
16 | limitParam:
   | ^^^^^^^^^^
17 |   in: query
18 |   name: limit

Warning was generated by the parameter-description rule.


/openapi.yaml: validated in <test>ms

Woohoo! Your OpenAPI definition is valid. 🎉
You have 4 warnings.


`;
