import type { ApiModel, OperationModel } from '../../ir/model.js';
import { emitModules, emitSingleFile } from '../client.js';
import { apiModel, emitWithOp, namedSchema, operation, param } from './fixtures.js';

/** An SSE operation streaming `Message` events (event-stream success + itemSchema $ref). */
function sseOperation(overrides: Partial<OperationModel> = {}): OperationModel {
  return operation({
    name: 'streamMessages',
    path: '/stream',
    successResponses: [
      {
        contentType: 'text/event-stream',
        status: 200,
        schema: { kind: 'unknown' },
        itemSchema: { kind: 'ref', name: 'Message' },
      },
    ],
    ...overrides,
  });
}

/** A model with one SSE op + the `Message` schema it streams. */
function sseModel(overrides: Partial<ApiModel> = {}): ApiModel {
  return apiModel({
    schemas: [namedSchema('Message', { kind: 'object', properties: [] })],
    services: [{ name: 'Default', operations: [sseOperation()] }],
    ...overrides,
  });
}

describe('emitSingleFile — top-level layout', () => {
  it('includes the generated-by header and ends with a newline', () => {
    const out = emitSingleFile(apiModel());
    expect(out.startsWith('// Generated by @redocly/client-generator')).toBe(true);
    expect(out.endsWith('\n')).toBe(true);
  });

  it('inlines the baseUrl as a mutable `let` binding so setBaseUrl() can update it', () => {
    const out = emitSingleFile(apiModel({ baseUrl: 'https://api.example.com/v1' }));
    expect(out).toContain('let BASE = "https://api.example.com/v1";');
    expect(out).not.toContain('const BASE = ');
  });

  it('always exports a setBaseUrl() helper that reassigns the BASE binding', () => {
    const out = emitSingleFile(apiModel({ baseUrl: 'https://api.example.com' }));
    expect(out).toContain('export function setBaseUrl(url: string): void');
    expect(out).toMatch(/BASE\s*=\s*url/);
  });

  it('lets a caller override the spec-derived baseUrl via options.baseUrl', () => {
    const out = emitSingleFile(apiModel({ baseUrl: 'https://from-spec.example.com' }), {
      baseUrl: 'http://127.0.0.1:3101',
    });
    expect(out).toContain('let BASE = "http://127.0.0.1:3101";');
    expect(out).not.toContain('from-spec.example.com');
  });

  it('emits a JSDoc title with the title and version', () => {
    const out = emitSingleFile(apiModel({ title: 'My API', version: '2.0.0' }));
    expect(out).toContain('* My API (v2.0.0)');
  });

  it('appends multi-line descriptions in the JSDoc title block', () => {
    const out = emitSingleFile(apiModel({ title: 'D', description: 'line one\nline two' }));
    expect(out).toContain(' * line one');
    expect(out).toContain(' * line two');
  });
});

describe('emitSingleFile — service-class facade', () => {
  it('emits a Client class by default (name omitted)', () => {
    const out = emitSingleFile(
      apiModel({
        services: [{ name: 'Default', operations: [operation({ name: 'ping' })] }],
      }),
      { facade: 'service-class' }
    );
    expect(out).toContain('export class Client {');
    expect(out).toMatch(/\basync ping\(/);
  });

  it('honors a custom class name via options.name', () => {
    const out = emitSingleFile(
      apiModel({
        services: [{ name: 'Default', operations: [operation({ name: 'ping' })] }],
      }),
      { facade: 'service-class', name: 'CafeClient' }
    );
    expect(out).toContain('export class CafeClient {');
    expect(out).not.toContain('export class Client {');
  });

  it('shares the identical http + schemas modules with the functions facade (core unchanged)', () => {
    const model = apiModel({
      services: [{ name: 'Default', operations: [operation({ name: 'ping' })] }],
    });
    const fns = emitModules(model, { facade: 'functions' });
    const cls = emitModules(model, { facade: 'service-class' });
    // The facade changes only the endpoints; the shared http (runtime + auth) and
    // schemas (types + guards) modules are byte-identical across facades.
    expect(cls.http).toBe(fns.http);
    expect(cls.schemas).toBe(fns.schemas);
  });
});

describe('extension contract (ClientConfig)', () => {
  it('emits the ClientConfig + RequestContext types, the global __config, and configure()', () => {
    const out = emitSingleFile(apiModel());
    expect(out).toContain('export type ClientConfig = {');
    expect(out).toContain('export type RequestContext = {');
    expect(out).toContain('const __config: ClientConfig = {};');
    expect(out).toContain('export function configure(config: ClientConfig): void {');
    expect(out).toContain('Object.assign(__config, config);');
  });

  it('threads the global __config through functions (both __buildUrl and __request)', () => {
    const out = emitWithOp({ name: 'ping', path: '/p' });
    expect(out).toContain('__buildUrl(__config, `/p`)');
    // __request receives __config as its first argument.
    expect(out).toContain('return __request<void>(__config,');
  });

  it('runtime resolves config.baseUrl ?? BASE and config.fetch ?? fetch', () => {
    const out = emitSingleFile(apiModel());
    expect(out).toContain('(config.baseUrl ?? BASE)');
    expect(out).toContain('const doFetch = config.fetch ?? fetch;');
  });

  it('runs the request through the composable middleware chain (single hooks + use())', () => {
    const out = emitSingleFile(apiModel());
    // The single config hooks are folded into one implicit first middleware.
    expect(out).toContain('function __middleware(config: ClientConfig): Middleware[]');
    expect(out).toContain('for (const mw of middleware)');
    expect(out).toContain('if (mw.onRequest)');
    // onResponse runs in reverse (onion).
    expect(out).toContain('for (let i = middleware.length - 1; i >= 0; i--)');
    // onError threads through each middleware.
    expect(out).toContain('error = await mw.onError(error as ApiError, context);');
    // The `use()` registrar is exported for the functions facade.
    expect(out).toContain('export function use(...middleware: Middleware[]): void');
  });

  it('service-class takes a ClientConfig constructor and threads this.config', () => {
    const out = emitSingleFile(
      apiModel({
        services: [
          {
            name: 'Default',
            operations: [operation({ name: 'ping', path: '/p' })],
          },
        ],
      }),
      { facade: 'service-class' }
    );
    expect(out).toContain('constructor(private readonly config: ClientConfig = {}) { }');
    expect(out).toContain('__buildUrl(this.config, `/p`)');
    expect(out).toContain('return __request<void>(this.config,');
  });
});

describe('runtime — retry config types', () => {
  it('emits the retry types and a ClientConfig.retry field', () => {
    const out = emitSingleFile(apiModel());
    expect(out).toContain('export type RetryStrategy =');
    expect(out).toContain('export type RetryConfig = {');
    expect(out).toContain('export type RetryContext = {');
    // The printer reflows the `RequestOptions` type literal across lines.
    expect(out).toContain('export type RequestOptions = RequestInit & {');
    expect(out).toContain('parseAs?: ParseAs;');
    expect(out).toContain('retry?: RetryConfig;');
  });

  it('emits the retry loop, default predicate, backoff, and Retry-After handling', () => {
    const out = emitSingleFile(apiModel());
    expect(out).toContain('function __defaultRetryOn(ctx: RetryContext): boolean');
    expect(out).toContain("['GET', 'HEAD', 'PUT', 'DELETE', 'OPTIONS']");
    expect(out).toContain('[408, 429, 500, 502, 503, 504]');
    expect(out).toContain('function __retryDelay(');
    expect(out).toContain('function __sleep(');
    expect(out).toContain("response.headers.get('retry-after')");
    expect(out).toContain('const { retry: callRetry, ...fetchInit } = init;');
    // The abort helper must use `globalThis.Error` so a spec-defined `Error`
    // schema (e.g. cafe.yaml) does not shadow the built-in error type.
    expect(out).toContain('function __abortError(signal: AbortSignal): globalThis.Error');
  });
});

describe('renderRuntime contents (smoke)', () => {
  it('embeds the QueryValue / __buildUrl / __request / readError surface', () => {
    const out = emitSingleFile(apiModel());
    expect(out).toContain('type QueryValue');
    expect(out).toContain('function __buildUrl(');
    expect(out).toContain('async function __request<T>(');
    expect(out).toContain('async function readError(');
    expect(out).toContain('class ApiError extends Error');
  });
});

describe('emitModules — writer-facing module interface', () => {
  it('exposes the http module (runtime + auth helpers exported) and the endpoints', () => {
    const m = emitModules(apiModel({ services: [{ name: 'Default', operations: [operation()] }] }));
    expect(m.http).toContain('export function __buildUrl(');
    expect(m.http).toContain('export async function __request<T>(');
    expect(m.operations).toContain('export async function op(');
  });

  it('reports hasSchemas and fills the schemas module from the model types', () => {
    const withSchemas = emitModules(
      apiModel({ schemas: [namedSchema('Foo', { kind: 'scalar', scalar: 'string' })] })
    );
    expect(withSchemas.hasSchemas).toBe(true);
    expect(withSchemas.schemas).toContain('export type Foo = string;');

    const noSchemas = emitModules(apiModel({ schemas: [] }));
    expect(noSchemas.hasSchemas).toBe(false);
  });

  it('renderEndpoints renders a named subset; endpointImports wires the shared modules', () => {
    const m = emitModules(
      apiModel({
        services: [
          {
            name: 'Default',
            operations: [
              operation({
                name: 'getPet',
                path: '/pets/{id}',
                pathParams: [param('id', 'path', true)],
                successResponses: [
                  {
                    contentType: 'application/json',
                    schema: { kind: 'ref', name: 'Pet' },
                    status: 200,
                  },
                ],
              }),
            ],
          },
        ],
      })
    );
    const ops = [
      operation({
        name: 'getPet',
        path: '/pets/{id}',
        pathParams: [param('id', 'path', true)],
        successResponses: [
          { contentType: 'application/json', schema: { kind: 'ref', name: 'Pet' }, status: 200 },
        ],
      }),
    ];
    expect(m.renderEndpoints(ops, 'PetsService')).toContain('export async function getPet(');
    const imports = m.endpointImports(ops, 'client');
    expect(imports).toContain('from "./client.http.js"');
    expect(imports).toContain('import type { Pet } from "./client.schemas.js";');
    // `prefix` reaches one folder up for the tags-split layout.
    expect(m.endpointImports(ops, 'client', '../')).toContain('from "../client.http.js"');
  });

  it('publicReexport re-exports the public runtime values and config types', () => {
    const m = emitModules(apiModel());
    const reexport = m.publicReexport('client');
    expect(reexport).toContain(
      'export { ApiError, configure, setBaseUrl } from "./client.http.js";'
    );
    expect(reexport).toContain('export type {');
  });
});

describe('SSE plumbing (single + multi-file)', () => {
  it('emitSingleFile emits the __sse runtime block and the sse aggregate for an SSE op', () => {
    const out = emitSingleFile(sseModel());
    expect(out).toContain('async function* __sse');
    expect(out).toContain('export const sse =');
  });

  it('emitSingleFile omits __sse and the sse aggregate when no op streams', () => {
    const out = emitSingleFile(
      apiModel({ services: [{ name: 'Default', operations: [operation()] }] })
    );
    expect(out).not.toContain('async function* __sse');
    expect(out).not.toContain('export const sse =');
  });

  it('emitModules http exports the __sse generator for an SSE model', () => {
    const m = emitModules(sseModel());
    expect(m.http).toContain('export async function* __sse');
  });

  it('publicReexport re-exports ServerSentEvent + SseOptions only for an SSE model', () => {
    const sse = emitModules(sseModel()).publicReexport('client');
    const typeLine = sse.split('\n').find((l) => l.startsWith('export type {')) ?? '';
    expect(typeLine).toContain('ServerSentEvent');
    expect(typeLine).toContain('SseOptions');

    const plain = emitModules(apiModel()).publicReexport('client');
    expect(plain).not.toContain('ServerSentEvent');
    expect(plain).not.toContain('SseOptions');
  });

  it('endpointImports pulls __sse (value) + ServerSentEvent/SseOptions (types) + the event type', () => {
    const ops = [sseOperation()];
    const imports = emitModules(sseModel()).endpointImports(ops, 'client');
    expect(imports).toContain('__sse');
    expect(imports).toContain('type ServerSentEvent');
    expect(imports).toContain('type SseOptions');
    // The streamed event schema is imported from the schemas module.
    expect(imports).toContain('import type { Message } from "./client.schemas.js";');
    // An SSE-only file never references the regular request terminal or RequestOptions.
    expect(imports).not.toMatch(/\b__request\b/);
    expect(imports).not.toContain('RequestOptions');
  });

  it('a regular-only endpoints file imports no SSE symbols', () => {
    const ops = [
      operation({
        name: 'getPet',
        path: '/pets/{id}',
        pathParams: [param('id', 'path', true)],
        successResponses: [
          { contentType: 'application/json', schema: { kind: 'ref', name: 'Pet' }, status: 200 },
        ],
      }),
    ];
    const imports = emitModules(sseModel()).endpointImports(ops, 'client');
    expect(imports).not.toMatch(/\b__sse\b/);
    expect(imports).not.toContain('ServerSentEvent');
    expect(imports).not.toContain('SseOptions');
  });
});

describe('query-auth + TokenProvider threading', () => {
  const queryAuthModel = apiModel({
    securitySchemes: [{ kind: 'apiKeyQuery', key: 'ApiKeyQuery', paramName: 'api_key' }],
    services: [
      {
        name: 'Default',
        operations: [operation({ name: 'ping', path: '/p', security: ['ApiKeyQuery'] })],
      },
    ],
  });

  it('emitSingleFile merges __a.query into the URL for an apiKey-query op (end-to-end)', () => {
    const out = emitSingleFile(queryAuthModel, {});
    expect(out).toContain('...__a.query');
    expect(out).toContain('export type TokenProvider');
    expect(out).toContain('export function setApiKey(');
  });

  it('publicReexport type list includes TokenProvider; value list includes setBearer', () => {
    const bearerModel = apiModel({
      securitySchemes: [{ kind: 'bearer', key: 'Bearer' }],
    });
    const reexport = emitModules(bearerModel, {}).publicReexport('client');
    const valueLine = reexport.split('\n').find((l) => l.startsWith('export {')) ?? '';
    const typeLine = reexport.split('\n').find((l) => l.startsWith('export type {')) ?? '';
    expect(valueLine).toContain('setBearer');
    expect(typeLine).toContain('TokenProvider');
  });

  it('publicReexport value list includes setBasicAuth + apiKey setters across all in', () => {
    const mixed = apiModel({
      securitySchemes: [
        { kind: 'basic', key: 'Basic' },
        { kind: 'apiKeyQuery', key: 'Q', paramName: 'q' },
        { kind: 'apiKeyCookie', key: 'C', cookieName: 'c' },
      ],
    });
    const reexport = emitModules(mixed, {}).publicReexport('client');
    const valueLine = reexport.split('\n').find((l) => l.startsWith('export {')) ?? '';
    const typeLine = reexport.split('\n').find((l) => l.startsWith('export type {')) ?? '';
    expect(valueLine).toContain('setBasicAuth');
    // Two apiKey schemes of distinct `in` → distinct setters.
    expect(valueLine).toMatch(/setApiKey\w+/);
    expect(typeLine).toContain('TokenProvider');
  });

  it('renderEndpoints threads queryAuthKeys into the per-tag endpoint render', () => {
    const m = emitModules(queryAuthModel, {});
    const ops = [operation({ name: 'ping', path: '/p', security: ['ApiKeyQuery'] })];
    expect(m.renderEndpoints(ops, 'PingService')).toContain('...__a.query');
  });
});

describe('errorMode threading', () => {
  const resultModel = apiModel({
    services: [{ name: 'Default', operations: [operation({ name: 'ping', path: '/p' })] }],
  });

  it('emitSingleFile honors errorMode: result in runtime + operations', () => {
    const out = emitSingleFile(resultModel, { errorMode: 'result' });
    expect(out).toContain('__requestResult');
    expect(out).toContain('export type Result<');
    expect(out).toContain('Promise<Result<');
  });

  it('emitSingleFile defaults to throw mode (no result surface)', () => {
    const out = emitSingleFile(resultModel, {});
    expect(out).not.toContain('__requestResult');
    expect(out).not.toContain('export type Result<');
    expect(out).not.toContain('Promise<Result<');
  });

  it('emitModules publicReexport re-exports Result only in result mode', () => {
    const reexportLine = (out: string) =>
      out.split('\n').find((l) => l.startsWith('export type {')) ?? '';

    const result = emitModules(resultModel, { errorMode: 'result' }).publicReexport('client');
    expect(reexportLine(result)).toContain('Result');

    const thrown = emitModules(resultModel, {}).publicReexport('client');
    expect(reexportLine(thrown)).not.toContain('Result');
  });

  it('renderEndpoints emits result-mode operations (the per-tag layout path)', () => {
    const m = emitModules(resultModel, { errorMode: 'result' });
    const ops = [operation({ name: 'ping', path: '/p' })];
    const out = m.renderEndpoints(ops, 'PingService');
    expect(out).toContain('__requestResult<');
    expect(out).toContain('Promise<Result<');
    expect(out).not.toContain('__request<');
  });

  it('endpointImports pulls __requestResult in result mode, __request in throw mode', () => {
    const ops = [operation({ name: 'ping', path: '/p' })];

    const result = emitModules(resultModel, { errorMode: 'result' });
    const resultImports = result.endpointImports(ops, 'client');
    expect(resultImports).toContain('__requestResult');
    expect(resultImports).not.toContain('__request,');
    expect(resultImports).not.toMatch(/\b__request\b(?!Result)/);
    // Result-mode signatures reference `Result<…>`, so the endpoints file must
    // import the type from the http module.
    expect(resultImports).toContain('type Result');

    const thrown = emitModules(resultModel, {});
    const thrownImports = thrown.endpointImports(ops, 'client');
    expect(thrownImports).toMatch(/\b__request\b/);
    expect(thrownImports).not.toContain('__requestResult');
    expect(thrownImports).not.toContain('type Result');
  });

  it('endpointImports imports error-body schemas only in result mode', () => {
    // An op whose only named-schema reference is in its error response.
    const ops = [
      operation({
        name: 'ping',
        path: '/p',
        errorResponses: [
          {
            contentType: 'application/json',
            schema: { kind: 'ref', name: 'Problem' },
            status: 200,
          },
        ],
      }),
    ];

    // Result mode names the error body (`PingError = Problem`), so it imports `Problem`.
    expect(
      emitModules(resultModel, { errorMode: 'result' }).endpointImports(ops, 'client')
    ).toContain('Problem');
    // Throw mode never names the error body — importing it would trip `noUnusedLocals`.
    expect(emitModules(resultModel, {}).endpointImports(ops, 'client')).not.toContain('Problem');
  });
});

describe('multipart serialization helper (#5)', () => {
  const uploadModel = apiModel({
    services: [
      {
        name: 'Default',
        operations: [
          operation({
            name: 'upload',
            method: 'post',
            requestBody: {
              contentType: 'multipart/form-data',
              required: true,
              schema: {
                kind: 'object',
                properties: [
                  {
                    name: 'file',
                    schema: { kind: 'scalar', scalar: 'string', metadata: { format: 'binary' } },
                    required: true,
                  },
                ],
              },
            },
          }),
        ],
      },
    ],
  });

  it('emits __toFormData when an operation has a typed multipart body', () => {
    expect(emitSingleFile(uploadModel)).toContain('function __toFormData');
  });

  it('omits __toFormData when no operation needs it', () => {
    expect(emitSingleFile(apiModel())).not.toContain('__toFormData');
  });

  it('imports __toFormData into the endpoints module in multi-file output', () => {
    const ops = uploadModel.services[0].operations;
    // The call site lives in the endpoints module; the helper in the http module — so a
    // multipart op must pull `__toFormData` across the module boundary (else TS2552).
    expect(emitModules(uploadModel, {}).endpointImports(ops, 'client')).toContain('__toFormData');
    // A non-multipart op must NOT import it (noUnusedLocals).
    const plain = apiModel({
      services: [{ name: 'Default', operations: [operation({ name: 'ping' })] }],
    });
    expect(
      emitModules(plain, {}).endpointImports(plain.services[0].operations, 'client')
    ).not.toContain('__toFormData');
  });
});
