import { banner, HEADER, renderTitleComment } from '../emit-options.js';
import { apiModel } from './fixtures.js';

describe('banner', () => {
  it('joins non-empty sections with blank lines and appends a trailing newline', () => {
    expect(banner(['a', 'b'])).toBe('a\n\nb\n');
  });

  it('drops empty sections so no double separators appear', () => {
    expect(banner(['a', '', 'b'])).toBe('a\n\nb\n');
  });
});

describe('HEADER', () => {
  it('names the generator and the regeneration command', () => {
    expect(HEADER).toContain('Generated by @redocly/client-generator');
    expect(HEADER).toContain('redocly generate-client');
  });
});

describe('renderTitleComment', () => {
  it('emits a JSDoc block with the title and version', () => {
    const out = renderTitleComment(apiModel({ title: 'My API', version: '2.0.0' }));
    expect(out).toBe('/**\n * My API (v2.0.0)\n */');
  });

  it('appends multi-line descriptions in the block', () => {
    const out = renderTitleComment(apiModel({ title: 'D', description: 'line one\nline two' }));
    expect(out).toContain(' * line one');
    expect(out).toContain(' * line two');
  });

  it('escapes `*/` in attacker-controllable title/description text', () => {
    const out = renderTitleComment(
      apiModel({ title: 'X */ alert(1) /*', description: 'desc */ boom' })
    );
    // The comment must not be closable from inside.
    expect(out.slice(3, -2)).not.toContain('*/');
  });
});
