// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`E2E lint no-invalid-media-type-examples-invalid-schema 1`] = `

validating /openapi.yaml...
[1] openapi.yaml:28:17 at #/paths/~1test/get/responses/202/content/application~1json/schema

Example validation errored: "nullable" cannot be used without "type".

26 |     application/json:
27 |       schema:
28 |         $ref: "#/components/schemas/Test"
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
29 |       example: {}
30 | '400':

referenced from openapi.yaml:27:15 at #/paths/~1test/get/responses/202/content/application~1json 

Warning was generated by the no-invalid-media-type-examples rule.


/openapi.yaml: validated in <test>ms

Woohoo! Your OpenAPI definition is valid. 🎉
You have 1 warning.


`;
