// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`E2E path-not-include-query-error 1`] = `
[1] openapi.yaml:10:3 at #/paths/~1ping~1items?id=###

Don't put query string items in the path, they belong in parameters with in: query.

 8 |
 9 | paths:
10 |   '/ping/items?id=###':
   |   ^^^^^^^^^^^^^^^^^^^^
11 |     get:
12 |       responses:

error was generated by path-not-include-query rule.



❌ Validation failed with 1 error and 0 warnings. 

run with \`--generate-exceptions\` to add all messages to exceptions file


`;
