import type { ApiMap } from '../build.js';
import { renderApiMap } from '../render.js';

const mapFixture: ApiMap = {
  headline:
    'Museum API · oas3_0 · 3 operations · generated by @redocly/cli from openapi.yaml — do not edit; regenerate after editing the spec',
  legend: ['legend line one', 'legend line two'],
  servers: 'https://api.example.com/v1',
  security: ['ApiKey: apiKey in header X-Key'],
  groups: [
    {
      name: 'Tickets',
      summary: 'Buy tickets',
      rows: ['POST /tickets · buyTickets · src: openapi.yaml L10-40'],
    },
    {
      name: 'Events',
      rows: [
        'GET /events · listEvents · src: openapi.yaml L50-60',
        'POST /events · addEvent · src: openapi.yaml L61-80',
      ],
    },
  ],
  webhooks: ['POST webhook newTicket · src: openapi.yaml L8-9'],
  operationCount: 3,
};

describe('renderApiMap', () => {
  it('renders every section and toc ranges that point at the real group lines', () => {
    const text = renderApiMap(mapFixture);
    const lines = text.split('\n');

    expect(lines[0]).toBe(`# ${mapFixture.headline}`);

    // The toc ranges must agree with where the groups actually landed.
    const tocLines = lines.filter((line) => /^\S+ \(\d+\) L\d+-\d+/.test(line));
    expect(tocLines).toHaveLength(2);
    for (const tocLine of tocLines) {
      const [, name, start, end] = tocLine.match(/^(\S+) \(\d+\) L(\d+)-(\d+)/)!;
      expect(lines[Number(start) - 1]).toBe(`## ${name}`);
      expect(Number(end)).toBeGreaterThanOrEqual(Number(start));
    }

    expect(text).toMatchInlineSnapshot(`
      "# Museum API · oas3_0 · 3 operations · generated by @redocly/cli from openapi.yaml — do not edit; regenerate after editing the spec
      # legend line one
      # legend line two
      servers: https://api.example.com/v1

      == security
      ApiKey: apiKey in header X-Key

      == toc
      Tickets (1) L14-15 — Buy tickets
      Events (2) L17-19

      == operations
      ## Tickets
      POST /tickets · buyTickets · src: openapi.yaml L10-40

      ## Events
      GET /events · listEvents · src: openapi.yaml L50-60
      POST /events · addEvent · src: openapi.yaml L61-80

      == webhooks
      POST webhook newTicket · src: openapi.yaml L8-9
      "
    `);
  });

  it('is deterministic', () => {
    expect(renderApiMap(mapFixture)).toBe(renderApiMap(mapFixture));
  });
});
