export const ASYNCAPI_ACTION_NAMES = ['send', 'receive'] as const;
export const ASYNCAPI2_COMPONENT_NAMES = [
  'schemas',
  'messages',
  'parameters',
  'correlationIds',
  'messageTraits',
  'operationTraits',
  'securitySchemes',
  'servers',
  'serverVariables',
  'channels',
  'serverBindings',
  'channelBindings',
  'operationBindings',
  'messageBindings',
] as const;

export const ASYNCAPI2_SPLITTABLE_COMPONENT_NAMES = [
  'schemas',
  'messages',
  'securitySchemes',
  'parameters',
  'correlationIds',
  'messageTraits',
  'operationTraits',
  'serverBindings',
  'channelBindings',
  'operationBindings',
  'messageBindings',
] as const;

export const ASYNCAPI3_COMPONENT_NAMES = [
  'schemas',
  'messages',
  'parameters',
  'replies',
  'replyAddresses',
  'correlationIds',
  'messageTraits',
  'operationTraits',
  'tags',
  'externalDocs',
  'securitySchemes',
  'servers',
  'serverVariables',
  'channels',
  'operations',
  'serverBindings',
  'channelBindings',
  'operationBindings',
  'messageBindings',
] as const;

export const ASYNCAPI3_SPLITTABLE_COMPONENT_NAMES = [
  'schemas',
  'messages',
  'securitySchemes',
  'servers',
  'serverVariables',
  'parameters',
  'replies',
  'replyAddresses',
  'correlationIds',
  'messageTraits',
  'operationTraits',
  'tags',
  'externalDocs',
  'serverBindings',
  'channelBindings',
  'operationBindings',
  'messageBindings',
] as const;
