import { spawnSync } from 'node:child_process';
import { existsSync, mkdtempSync, readdirSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, '../../..');
const cli = join(repoRoot, 'packages/cli/lib/index.js');
const tsx = join(repoRoot, 'node_modules/.bin/tsx');
const examplesDir = join(__dirname, 'examples');

// Every directory under examples/ is an example; `_shared` holds the spec they have in common.
const EXAMPLES = readdirSync(examplesDir, { withFileTypes: true })
  .filter((entry) => entry.isDirectory() && entry.name !== '_shared')
  .map((entry) => entry.name)
  .sort();

// The one example whose generated client stays committed (its README sells the single
// self-contained file); it doubles as the drift baseline for the generator's output.
// The other examples gitignore `src/api/` — CI regenerates and type-checks them via
// `examples:regen` + `typecheck:examples` in @redocly/client-generator.
const COMMITTED = 'zero-install-quickstart';

/**
 * Regenerate an example's client into `outFile`. A `redocly.yaml` example is generated by
 * naming its `apis:` alias (which equals the example folder name) with `--output` redirecting
 * the entry file to a temp dir; the programmatic example runs its `generate.ts` with `OUT`.
 */
function regenerate(
  exampleDir: string,
  name: string,
  outFile: string
): { status: number | null; stderr: string } {
  if (existsSync(join(exampleDir, 'redocly.yaml'))) {
    return spawnSync('node', [cli, 'generate-client', name, '--output', outFile], {
      cwd: exampleDir,
      encoding: 'utf-8',
    });
  }
  return spawnSync(tsx, [join(exampleDir, 'generate.ts')], {
    cwd: exampleDir,
    encoding: 'utf-8',
    env: { ...process.env, OUT: outFile },
  });
}

/** All files (relative paths) under a dir, recursively. */
function listFiles(dir: string, base = dir): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...listFiles(full, base));
    else out.push(full.slice(base.length + 1));
  }
  return out;
}

describe('examples generate with the current generator', () => {
  for (const name of EXAMPLES) {
    it(`${name}: generation succeeds`, () => {
      const exampleDir = join(examplesDir, name);
      const tmp = mkdtempSync(join(tmpdir(), `ex-${name}-`));
      try {
        const res = regenerate(exampleDir, name, join(tmp, 'client.ts'));
        expect(res.status, res.stderr).toBe(0);
        expect(listFiles(tmp).length).toBeGreaterThan(0);

        if (name === COMMITTED) {
          const committed = join(exampleDir, 'src/api');
          const committedFiles = listFiles(committed).sort();
          expect(listFiles(tmp).sort(), `file set differs for ${name}`).toEqual(committedFiles);
          for (const rel of committedFiles) {
            expect(
              readFileSync(join(tmp, rel), 'utf-8'),
              `${name}/src/api/${rel} is stale — run \`npm run examples:regen -w @redocly/client-generator\``
            ).toBe(readFileSync(join(committed, rel), 'utf-8'));
          }
        }
      } finally {
        rmSync(tmp, { recursive: true, force: true });
      }
    }, 60_000);
  }
});

describe('generator-authoring examples carry the current AGENTS.md', () => {
  // The eject/architect examples commit the AGENTS.md drop so browsers see the full
  // story; this pins them byte-for-byte to the shipped template (markers included).
  const template = readFileSync(
    join(repoRoot, 'packages/client-generator/eject-assets/AGENTS.md'),
    'utf-8'
  ).trim();
  const expected = `<!-- redocly-generators:begin — managed by \`redocly eject-generator\`; content between markers is refreshed on eject -->\n\n${template}\n\n<!-- redocly-generators:end -->\n`;

  for (const example of ['ejected-generator', 'architected-generator']) {
    it(`${example}/generators/AGENTS.md matches the shipped template`, () => {
      const dropped = readFileSync(join(examplesDir, example, 'generators/AGENTS.md'), 'utf-8');
      expect(
        dropped,
        `stale — re-run \`redocly eject-generator\` or \`architect-generator\` in the example`
      ).toBe(expected);
    });
  }
});
