// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`E2E build-docs build docs with config option 1`] = `

🎉 bundled successfully in: nested/redoc-static.html (33 KiB) [⏱ <test>ms].

[1] nested/redocly.yaml:5:5 at #/theme/openapi/htmlTemplate

Property \`htmlTemplate\` is not expected here.

3 | theme:
4 |   openapi:
5 |     htmlTemplate: ../index.hbs
  |     ^^^^^^^^^^^^
6 |

Warning was generated by the configuration spec rule.


⚠️ Your config has 1 warning.
Found nested/redocly.yaml and using theme.openapi options
Prerendering docs

`;
