// Generated by @redocly/client-generator — do not edit by hand.
// Source: OpenAPI document. Re-run `redocly generate-client` to update.

/**
 * Package Runtime API (v1.0.0)
 */

import { createClient, type OperationDescriptor, type RequestOptions, type SseOptions } from '@redocly/client-generator';

export type Order = {
    id: string;
    status: string;
};

export type NewOrder = {
    status: string;
};

export type OrderEvent = {
    seq: number;
    text?: string;
};

export type GetOrderResult = Order;

export type GetOrderParams = {
    expand?: string;
};

export type GetOrderVariables = {
    "order-id": string;
    params?: GetOrderParams;
};

export type CreateOrderResult = Order;

export type CreateOrderBody = NewOrder;

export type CreateOrderVariables = {
    body: CreateOrderBody;
};

export type ConfigureResult = string;

/**
 * Per-operation `args`/`result` shapes (plus `kind: 'sse'` for event streams) — the
 * type-level companion of `OPERATIONS` that gives `createClient<Ops>` its typed methods.
 */
export type Ops = {
    getOrder: {
        args: {
            "order-id": string;
            params?: GetOrderParams;
        };
        result: GetOrderResult;
    };
    createOrder: {
        args: {
            body: CreateOrderBody;
        };
        result: CreateOrderResult;
    };
    configure_2: {
        args: {};
        result: ConfigureResult;
    };
    streamEvents: {
        args: {};
        result: OrderEvent;
        kind: "sse";
    };
};

/**
 * The wire-shape descriptor for every operation, keyed by operationId — the data the
 * runtime routes requests by. Also minification-safe static metadata (method, path,
 * tags) for cache keys, tracing span names, and request logging.
 */
export const OPERATIONS = {
    getOrder: { id: "getOrder", method: "GET", path: "/orders/{order-id}", params: [{ name: "order-id", in: "path" }, { name: "expand", in: "query" }], security: [{ scheme: "bearerAuth", kind: "bearer" }] },
    createOrder: { id: "createOrder", method: "POST", path: "/orders", body: { contentType: "application/json" } },
    configure_2: { id: "configure", method: "GET", path: "/configure-op" },
    streamEvents: { id: "streamEvents", method: "GET", path: "/events", responseKind: "sse", sseDataKind: "json" }
} as const satisfies Record<string, OperationDescriptor>;

export type OperationId = keyof typeof OPERATIONS;

export type OperationPath = (typeof OPERATIONS)[OperationId]["path"];

export const client = createClient<Ops, OperationId, OperationPath, string>(OPERATIONS, { serverUrl: "http://localhost:3123" });

export const { configure, use } = client;
export const setBearer = client.auth.bearer;
export const getOrder = (order_id: string, params: {
    expand?: string;
} = {}, init: RequestOptions = {}) => client.getOrder({ "order-id": order_id, params }, init);
export const createOrder = (body: NewOrder, init: RequestOptions = {}) => client.createOrder({ body }, init);
export const configure_2 = (init: RequestOptions = {}) => client.configure_2({}, init);
export const streamEvents = (init: SseOptions = {}) => client.streamEvents({}, init);

export { ApiError, createClient } from '@redocly/client-generator';
export type { ClientConfig, Middleware, RequestOptions, ServerSentEvent, SseOptions } from '@redocly/client-generator';
