// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`E2E lint operation-security-scheme-oas2-error 1`] = `

validating /openapi.yaml...
[1] openapi.yaml:22:5 at #/securityDefinitions/bearerAuth/flows

Property \`flows\` is not expected here.

Did you mean: flow ?

20 | in: header
21 | description: bearer auth
22 | flows: api flows
   | ^^^^^
23 | x-internal: true
24 | testProp: test

Error was generated by the spec rule.


[2] openapi.yaml:24:5 at #/securityDefinitions/bearerAuth/testProp

Property \`testProp\` is not expected here.

22 |   flows: api flows
23 |   x-internal: true
24 |   testProp: test
   |   ^^^^^^^^
25 | oauthImplicit:
26 |   type: oauth2

Error was generated by the spec rule.


/openapi.yaml: validated in <test>ms

❌ Validation failed with 2 errors.
run \`openapi lint --generate-ignore-file\` to add all problems to the ignore file.


`;
