import { parse } from 'node:path';

import { resolveModelPagination } from '../../../emitters/pagination.js';
import type { GeneratorInput } from '../../types.js';

/** The banner lines the pipeline derives from `HEADER` for every run. */
export const BANNER = [
  'Generated by @redocly/client-generator — do not edit by hand.',
  'Source: OpenAPI description. Re-run `redocly generate-client` to update.',
];

/**
 * Build a `GeneratorInput` the way the pipeline does: parse the `--output` anchor,
 * stamp the banner, and resolve pagination once. Tests call generators directly, so
 * they mirror those steps here.
 */
export function generatorInput(
  overrides: Omit<GeneratorInput, 'output' | 'banner' | 'pagination'> & { outputPath: string }
): GeneratorInput {
  const { outputPath, ...rest } = overrides;
  const { dir, name: stem, ext } = parse(outputPath);
  return {
    ...rest,
    output: { path: outputPath, dir, stem, ext },
    banner: BANNER,
    pagination: resolveModelPagination(overrides.model, undefined),
  };
}
