// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`E2E lint operation-security-scheme-basic-error 1`] = `

validating /openapi.yaml...
[1] openapi.yaml:14:5 at #/securityDefinitions/basicAuth/name

The field \`name\` is not allowed here.

12 | basicAuth:
13 |   type: basic
14 |   name: Authorization
   |   ^^^^
15 |   x-internal: true
16 | bearerAuth:

Error was generated by the spec rule.


/openapi.yaml: validated in <test>ms

❌ Validation failed with 1 error.
run \`openapi lint --generate-ignore-file\` to add all problems to the ignore file.


`;
