// Generated by the route-map custom generator. Do not edit by hand.
export const routes = {
  listMenuItems: 'GET /menu',
  createMenuItem: 'POST /menu',
  deleteMenuItem: 'DELETE /menu/{menuItemId}',
  getMenuItemPhoto: 'GET /menu-item-images/{menuItemId}',
  listOrders: 'GET /orders',
  createOrder: 'POST /orders',
  getOrderById: 'GET /orders/{orderId}',
  deleteOrder: 'DELETE /orders/{orderId}',
  updateOrder: 'PATCH /orders/{orderId}',
  listOrderItems: 'GET /order-items',
  getRevenue: 'GET /revenue',
  registerOAuth2Client: 'POST /oauth2/register',
} as const;
