// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`E2E tags-alphabetical-warning 1`] = `
[1] openapi.yaml:31:5 at #/tags/0

The "tags" array should be in alphabetical order

29 |         - astore    
30 | tags:
31 |   - name: xpets
   |     ^^^^^^^^^^^
32 |     description: Everything about your Pets
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
33 |     externalDocs:
   |     ^^^^^^^^^^^^^
34 |       url: http://docs.my-api.com/pet-operations.htm
   |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
35 |   - name: astore
36 |     description: Access to Petstore orders

warning was generated by tags-alphabetical rule.



Woohoo! Your OpenAPI definition is valid 🎉
You have 1 warning 


`;
