import type { ApiModel, OperationModel, SecuritySchemeModel } from '../intermediate-representation/model.js';
import { collectOperationRefs } from '../intermediate-representation/refs.js';
import { authSetterNames, authStatements, authTypeNames } from './auth.js';
import {
  type ArgsStyle,
  type Facade,
  isTypedMultipart,
  operationsBlockStatements,
  operationsMetaStatements,
  serviceClassName,
} from './operations.js';
import { PUBLIC_RUNTIME_TYPES, runtimeStatements, type OperationContextTypes } from './runtime.js';
import { isSseOp, sseFragmentName } from './sse.js';
import { splitLines } from './support.js';
import { escapeJsDoc, printNodes, printStatements, ts } from './ts.js';
import { typeGuardStatements } from './type-guards.js';
import { type DateType, type EnumStyle, typesStatements } from './types.js';

// The public option vocabulary and the writer-facing utilities are re-exported
// from this composition module, so writers and the package barrel import the
// emitter surface from one place — the carved-out structural emitters stay
// internal to `emitters/`.
export { serviceClassName } from './operations.js';
export type { ArgsStyle, Facade } from './operations.js';

const { factory } = ts;

/** The generated-by banner prepended to every emitted module. */
export const HEADER = `// Generated by @redocly/client-generator — do not edit by hand.
// Source: OpenAPI document. Re-run \`redocly generate-client\` to update.`;

/** The security-scheme keys whose credential is injected as a URL query param. */
function queryAuthKeysFor(schemes: SecuritySchemeModel[]): Set<string> {
  return new Set(schemes.filter((s) => s.kind === 'apiKeyQuery').map((s) => s.key));
}

export type EmitOptions = {
  /**
   * Override the BASE URL inlined into the emitted runtime. When omitted, the
   * value is derived from `servers[0].url` in the source OpenAPI document.
   */
  serverUrl?: string;
  /**
   * How named string enums are emitted:
   * - `'union'`: only the string-literal union type (`type X = "a" | "b"`).
   * - `'const-object'` (default): the union type *and* a sibling
   *   `export const X = { a: "a", b: "b" } as const;` so callers can reference
   *   the values at runtime (`X.a`).
   */
  enumStyle?: EnumStyle;
  /** Developer-facing operation shape. Defaults to `'functions'`. */
  facade?: Facade;
  /**
   * How operation inputs are passed to each function/method. Defaults to
   * `'flat'`; `'grouped'` bundles inputs into a single `args` object.
   */
  argsStyle?: ArgsStyle;
  /**
   * Class name for the `service-class` facade in single/split layouts. Ignored by
   * the `functions` facade and by per-tag service classes. Defaults to `'Client'`.
   */
  name?: string;
  /** Error-handling shape of the generated client. Defaults to `'throw'`. */
  errorMode?: 'throw' | 'result';
  /**
   * How `format: date-time`/`date` string fields are typed. `'string'` (default)
   * keeps the ISO wire shape; `'Date'` emits a `Date` reference. Opt-in — pair with
   * the `transformers` generator so the runtime value matches the type.
   */
  dateType?: DateType;
  /**
   * TanStack Query adapter the generated module imports from
   * (`@tanstack/${queryFramework}-query`). Defaults to `'react'`; the emitted body
   * is byte-identical across frameworks — only the import specifier changes.
   */
  queryFramework?: 'react' | 'vue' | 'svelte' | 'solid';
  /**
   * How the `mock` generator produces data. `'baked'` (default) inlines deterministic
   * literals (zero-dep, contract-faithful); `'faker'` emits `@faker-js/faker` calls for
   * realistic data — reproducible when `mockSeed` is set. Only the mock module is affected.
   */
  mockData?: 'baked' | 'faker';
  /** Seed for faker-mode mocks: emits a top-level `faker.seed(<n>)` so runs reproduce. */
  mockSeed?: number;
  /**
   * A pre-baked publisher setup block (from `bakeSetup`) appended at the end of the single-file
   * client, after the runtime + `configure`/`use` definitions. Absent when no `--setup` is given.
   */
  setup?: string;
};

/**
 * The independent code fragments that make up a generated client — an *internal*
 * breakdown, each a list of `ts.Statement`s. `emitSingleFile` concatenates them
 * into one file and prints once; `emitModules` composes them into the shared
 * modules writers consume. Never exposed to writers, so the fragment set can
 * change without touching them.
 */
type ClientFragments = {
  title: string;
  types: ts.Statement[];
  typeGuards: ts.Statement[];
  /**
   * The `OPERATIONS` metadata map (+ `OperationId` / `OperationMetadata` types).
   * Pure data with no runtime or type dependencies, so multi-file writers place it
   * in the shared schemas module alongside the model types.
   */
  operationsMeta: ts.Statement[];
  runtime: ts.Statement[];
  auth: ts.Statement[];
  operations: ts.Statement[];
};

/**
 * The operation-union wiring derived from the model: `opCtx` narrows the runtime's `OperationContext`
 * field types, and `opNames` is the type-only import list the http module pulls from the schemas
 * module in multi-file layouts. Falls back to all-`string` (and no import) when the spec has no
 * operations; tags fall back to `string[]` (no `OperationTag`) when no operation is tagged.
 */
function operationUnionInfo(allOps: OperationModel[]): {
  opCtx: OperationContextTypes;
  opNames: string[];
} {
  const hasOps = allOps.length > 0;
  const hasTags = allOps.some((op) => op.tags.length > 0);
  return {
    opCtx: {
      id: hasOps ? 'OperationId' : 'string',
      path: hasOps ? 'OperationPath' : 'string',
      tags: hasTags ? 'OperationTag[]' : 'string[]',
    },
    opNames: hasOps
      ? hasTags
        ? ['OperationId', 'OperationPath', 'OperationTag']
        : ['OperationId', 'OperationPath']
      : [],
  };
}

function renderFragments(
  model: ApiModel,
  options: EmitOptions,
  exportHelpers: boolean
): ClientFragments {
  const serverUrl = options.serverUrl ?? model.serverUrl;
  const enumStyle: EnumStyle = options.enumStyle ?? 'const-object';
  const errorMode = options.errorMode ?? 'throw';
  const dateType: DateType = options.dateType ?? 'string';
  const needsHeaderHelper = model.services.some((s) =>
    s.operations.some((op) => op.headerParams.length > 0)
  );
  const needsAuthHelper = model.services.some((s) =>
    s.operations.some((op) => op.security.length > 0)
  );
  const allOps = model.services.flatMap((s) => s.operations);
  const needsSse = allOps.some(isSseOp);
  // The `__toFormData` runtime helper is emitted only when some operation has a typed
  // multipart body (object schema); `__send` serializes it after the onRequest chain.
  const needsMultipart = allOps.some((op) => op.requestBody && isTypedMultipart(op.requestBody));
  // ClientConfig gains an `auth?: AuthCredentials` field (per-instance credentials)
  // whenever the client has injectable security schemes — the type the auth emitter
  // produces. Gated so non-auth clients are byte-identical.
  const authConfig = model.securitySchemes.length > 0;
  return {
    title: renderTitleComment(model),
    types: typesStatements(model.schemas, enumStyle, dateType),
    typeGuards: typeGuardStatements(model.schemas),
    operationsMeta: operationsMetaStatements(allOps),
    runtime: runtimeStatements(
      serverUrl,
      needsHeaderHelper,
      exportHelpers,
      errorMode,
      needsSse,
      authConfig,
      needsMultipart,
      operationUnionInfo(allOps).opCtx
    ),
    auth: authStatements(model.securitySchemes, needsAuthHelper, exportHelpers),
    operations: operationsBlockStatements(allOps, {
      facade: options.facade ?? 'functions',
      className: options.name ?? 'Client',
      argsStyle: options.argsStyle ?? 'flat',
      errorMode,
      dateType,
      queryAuthKeys: queryAuthKeysFor(model.securitySchemes),
      schemaNames: new Set(model.schemas.map((s) => s.name)),
      bakedSetup: !!options.setup,
    }),
  };
}

export function emitSingleFile(model: ApiModel, options: EmitOptions = {}): string {
  const f = renderFragments(model, options, false);
  return banner([
    HEADER,
    f.title,
    printStatements([
      ...f.types,
      ...f.typeGuards,
      ...f.operationsMeta,
      ...f.runtime,
      ...f.auth,
      ...f.operations,
    ]),
    // Publisher setup baked in last, so `configure`/`use` are already defined when it runs.
    ...(options.setup ? [setupApply(options.setup, options.facade ?? 'functions', false)] : []),
  ]);
}

/**
 * Render the baked publisher setup (`--setup`). `setupExpr` is the neutral expression from
 * `bakeSetup`; it becomes a module-scoped `const __redoclySetup`. Applied per facade:
 * - `functions`: also call `configure`/`use` so the global config + middleware chain are set.
 * - `service-class`: declaration only — the generated class constructor merges `__redoclySetup`
 *   into each instance's `config`. `exported` re-exports it from the http module so per-tag service
 *   classes in multi-file layouts can import it.
 */
export function setupApply(setupExpr: string, facade: Facade, exported: boolean): string {
  // Annotated so `.config`/`.middleware` are always accessible (a setup with only `config` would
  // otherwise infer a type without a `middleware` property, breaking the service-class merge).
  const decl = `${exported ? 'export ' : ''}const __redoclySetup: { config?: ClientConfig; middleware?: Middleware[] } = ${setupExpr};`;
  const header = '// ─── Baked-in setup (--setup) ───';
  if (facade === 'service-class') return `${header}\n${decl}`;
  return `${header}\n${decl}\nconfigure(__redoclySetup.config ?? {});\nuse(...(__redoclySetup.middleware ?? []));`;
}

/**
 * Assemble file content from a header banner and a printed body: the leading
 * `// Generated by …` comment and the `/** title *​/` block are structural
 * banners (not part of the printed AST), prepended with blank-line separation.
 * Trailing newline mirrors a hand-authored file.
 */
function banner(sections: string[]): string {
  return sections.filter((s) => s.length > 0).join('\n\n') + '\n';
}

/**
 * The writer-facing view of an emitted client. The shared-module contents are
 * eager strings; the per-file wiring (`renderEndpoints`, `endpointImports`,
 * `publicReexport`) are methods because they depend on the writer's chosen file
 * names (`stem`, `prefix`) and operation grouping. `emitSingleFile` is the
 * single-file counterpart that needs none of this.
 */
export type ClientModules = {
  /** The generated-by header comment, prepended to every emitted file. */
  header: string;
  /**
   * Shared http module: runtime + auth state + public setters. A method (not a string) because the
   * narrowed `OperationContext` type-imports `OperationId`/`OperationPath`/`OperationTag` from the
   * `<stem>.schemas` module, so the content depends on the writer's chosen stem.
   */
  http(stem: string): string;
  /** Shared schemas module: model types + type guards + operation metadata. */
  schemas: string;
  /** Whether the schemas module exports anything (else its file + re-export are skipped). */
  hasSchemas: boolean;
  /** Every operation rendered together (the `split` entry file's endpoints). */
  operations: string;
  /** Render a subset of operations as their own block, for per-tag layouts. */
  renderEndpoints(ops: OperationModel[], className: string): string;
  /**
   * The import header an endpoints file needs: the schema types it references and
   * the runtime helpers it uses. `prefix` is the relative path back to the shared
   * modules (`./` beside them, `../` one folder deeper, as in `tags-split`).
   */
  endpointImports(ops: OperationModel[], stem: string, prefix?: string): string;
  /** Re-export the public runtime surface (values + config types) from the http module. */
  publicReexport(stem: string): string;
  /**
   * The entry-barrel `export const sse = { ...frag }` merging per-tag SSE fragments
   * (functions facade). Empty string when none.
   */
  sseBarrel(groups: { tagStem: string; moduleSpec: string; ops: OperationModel[] }[]): string;
};

/**
 * Build the multi-file view of a client. The operation-facing runtime helpers are
 * `export`ed (endpoints import them from the shared http module); `facade` and
 * `argsStyle` are captured here so writers needn't thread them through.
 */
export function emitModules(model: ApiModel, options: EmitOptions = {}): ClientModules {
  const f = renderFragments(model, options, true);
  const facade = options.facade ?? 'functions';
  const argsStyle = options.argsStyle ?? 'flat';
  const errorMode = options.errorMode ?? 'throw';
  const dateType: DateType = options.dateType ?? 'string';
  const queryAuthKeys = queryAuthKeysFor(model.securitySchemes);
  const schemaNames = new Set(model.schemas.map((s) => s.name));
  const allOps = model.services.flatMap((s) => s.operations);
  const hasSse = allOps.some(isSseOp);
  const { opNames } = operationUnionInfo(allOps);
  return {
    header: HEADER,
    http: (stem) => httpModuleContent(f, options, stem, opNames),
    schemas: schemasModuleContent(f),
    hasSchemas: hasSchemas(f),
    operations: printStatements(f.operations),
    renderEndpoints: (ops, className) =>
      printStatements(
        operationsBlockStatements(ops, {
          facade,
          className,
          argsStyle,
          errorMode,
          dateType,
          queryAuthKeys,
          schemaNames,
          bakedSetup: !!options.setup,
          // Per-tag SSE aggregates carry the class-derived name so the barrel can
          // re-merge them without collisions.
          sseExportName: sseFragmentName(className),
        })
      ),
    endpointImports: (ops, stem, prefix) =>
      printNodes(endpointImportNodes(ops, stem, facade, errorMode, prefix, !!options.setup)),
    publicReexport: (stem) =>
      printNodes(publicReexportNodes(stem, model.securitySchemes, options.errorMode, hasSse)),
    sseBarrel: (groups) => {
      if (facade !== 'functions') return '';
      const withSse = groups.filter((g) => g.ops.some(isSseOp));
      if (withSse.length === 0) return '';
      // `serviceClassName` is applied exactly once (on the raw tag stem) here and in
      // `renderEndpoints`, so the producer fragment and this import agree.
      const frags = withSse.map((g) => sseFragmentName(serviceClassName(g.tagStem)));
      const imports = withSse
        .map((g, i) => `import { ${frags[i]} } from '${g.moduleSpec}';`)
        .join('\n');
      const spread = frags.map((f) => `...${f}`).join(', ');
      return `${imports}\nexport const sse = { ${spread} };`;
    },
  };
}

/**
 * The relative-import basename for emitting `from './<stem>.<kind>.js'`. The `.js`
 * extension is required for `node16`/`nodenext` module resolution and accepted by
 * bundler resolution, so generated imports stay portable. Writers also use this to
 * wire the barrel's cross-module re-exports.
 */
export function moduleSpecifier(stem: string, kind: 'schemas' | 'http', prefix = './'): string {
  return `${prefix}${stem}.${kind}.js`;
}

/** The shared http module's content: runtime + auth state + public setters. */
function httpModuleContent(
  f: ClientFragments,
  options: EmitOptions,
  stem: string,
  opNames: string[]
): string {
  const facade = options.facade ?? 'functions';
  // The narrowed `OperationContext` references the operation unions, which live in the schemas
  // module; pull them in type-only (erased, zero-dep, acyclic). Empty when the spec has no operations.
  const importLine =
    opNames.length > 0
      ? `import type { ${opNames.join(', ')} } from "${moduleSpecifier(stem, 'schemas')}";`
      : '';
  // The baked setup lives in the shared http module: `configure`/`use` are defined here, and every
  // layout's entry imports it, so it runs on load. Service-class exports `__redoclySetup` so each
  // per-tag class module can import and merge it.
  const setup = options.setup
    ? [setupApply(options.setup, facade, facade === 'service-class')]
    : [];
  return banner(
    [HEADER, importLine, printStatements([...f.runtime, ...f.auth]), ...setup].filter(Boolean)
  );
}

/** The shared schemas module's content: model types + type guards + operation metadata. */
function schemasModuleContent(f: ClientFragments): string {
  return banner([HEADER, printStatements([...f.types, ...f.typeGuards, ...f.operationsMeta])]);
}

/** True when the schemas module actually exports anything. */
function hasSchemas(f: ClientFragments): boolean {
  return f.types.length > 0 || f.typeGuards.length > 0 || f.operationsMeta.length > 0;
}

/** The named types a set of operations references, sorted for deterministic imports. */
function typeNamesFor(ops: OperationModel[], errorMode: 'throw' | 'result'): string[] {
  const refs = new Set<string>();
  for (const op of ops) {
    for (const ref of collectOperationRefs(op, errorMode)) refs.add(ref);
  }
  return [...refs].sort();
}

/** The runtime helpers a set of operations imports from the http module. */
function helperNamesFor(ops: OperationModel[], errorMode: 'throw' | 'result'): string[] {
  const helpers: string[] = [];
  // `__buildUrl` is used by both SSE and regular ops; the request terminal
  // (`__requestResult` in result mode, `__request` in throw mode) only by regular
  // ops, and `__sse` only by SSE ops — guard each so an SSE-only or regular-only
  // file never imports a helper it doesn't reference (`noUnusedLocals`).
  if (ops.length > 0) helpers.push('__buildUrl');
  if (ops.some((op) => !isSseOp(op)))
    helpers.push(errorMode === 'result' ? '__requestResult' : '__request');
  if (ops.some(isSseOp)) helpers.push('__sse');
  if (ops.some((op) => op.security.length > 0)) helpers.push('__auth');
  if (ops.some((op) => op.headerParams.length > 0)) helpers.push('__headers');
  // `__toFormData` is not imported here: `__send` (in the runtime module) serializes a
  // multipart body itself, so the endpoints module never references the helper.
  return helpers.sort();
}

/**
 * The import declarations an endpoints file needs: referenced types + used helpers.
 *
 * The `facade` decides how the config is reached: the functions facade imports the
 * global `__config` value; the service-class facade imports the `ClientConfig` type
 * for its constructor (each instance carries its own config).
 */
function endpointImportNodes(
  ops: OperationModel[],
  stem: string,
  facade: Facade,
  errorMode: 'throw' | 'result',
  prefix = './',
  bakedSetup = false
): ts.ImportDeclaration[] {
  const typeNames = typeNamesFor(ops, errorMode);
  const httpValues = helperNamesFor(ops, errorMode);
  if (facade === 'functions') httpValues.push('__config');
  // A service-class constructor merges the baked `__redoclySetup` (exported from the http module).
  if (facade === 'service-class' && bakedSetup) httpValues.push('__redoclySetup');
  httpValues.sort();
  // The class constructor needs the `ClientConfig` *type*; pull it from the http
  // module via an inline `type` modifier so the value/type imports stay one
  // declaration. Every listed type must be referenced by this file's emitted code,
  // else `noUnusedLocals` trips: `RequestOptions` is only the per-call init of a
  // regular op (SSE ops take `SseOptions`); `Result<…>` is only named by a
  // regular op in result mode; `ServerSentEvent`/`SseOptions` only by an SSE op.
  const hasRegular = ops.some((op) => !isSseOp(op));
  const hasSse = ops.some(isSseOp);
  const httpTypeNames = [
    // The class constructor needs `ClientConfig`; its `use()` method needs `Middleware`.
    ...(facade === 'service-class' ? ['ClientConfig', 'Middleware'] : []),
    ...(hasRegular ? ['RequestOptions'] : []),
    ...(errorMode === 'result' && hasRegular ? ['Result'] : []),
    ...(hasSse ? ['ServerSentEvent', 'SseOptions'] : []),
  ];

  const decls: ts.ImportDeclaration[] = [];
  if (typeNames.length > 0) {
    decls.push(importDeclaration(true, typeNames, moduleSpecifier(stem, 'schemas', prefix)));
  }
  // Always non-empty: every facade reaches the http module — the functions facade
  // for `__config`, the service-class facade for the `ClientConfig` type. Inline
  // `type` modifiers keep value and type imports in one declaration.
  decls.push(
    importDeclaration(
      false,
      [
        ...httpValues.map((name) => ({ name })),
        ...httpTypeNames.map((name) => ({ name, typeOnly: true })),
      ],
      moduleSpecifier(stem, 'http', prefix)
    )
  );
  return decls;
}

/**
 * Re-export the public runtime surface from the http module: the values
 * (`ApiError`, `setServerUrl`, `configure`, auth setters) and the config types
 * (`PUBLIC_RUNTIME_TYPES` — `ClientConfig`, `RequestContext`, `RequestOptions`,
 * and the retry types) so callers get the whole surface from the entry.
 */
function publicReexportNodes(
  stem: string,
  schemes: SecuritySchemeModel[],
  errorMode: 'throw' | 'result' | undefined,
  hasSse: boolean
): ts.ExportDeclaration[] {
  const values = ['ApiError', 'configure', 'use', 'setServerUrl', ...authSetterNames(schemes)].sort();
  const types = [
    ...PUBLIC_RUNTIME_TYPES,
    ...authTypeNames(schemes),
    ...(errorMode === 'result' ? ['Result'] : []),
    // `ServerSentEvent`/`SseOptions` are conditionally re-exported (not in
    // PUBLIC_RUNTIME_TYPES) so a non-SSE client's barrel stays free of them.
    ...(hasSse ? ['ServerSentEvent', 'SseOptions'] : []),
  ].sort();
  const spec = moduleSpecifier(stem, 'http');
  return [exportDeclaration(false, values, spec), exportDeclaration(true, types, spec)];
}

/** `import [type] { <a>, type <b>, … } from '<spec>';` */
function importDeclaration(
  typeOnly: boolean,
  names: readonly (string | { name: string; typeOnly?: boolean })[],
  spec: string
): ts.ImportDeclaration {
  const specifiers = names.map((n) => {
    const { name, typeOnly: inline } = typeof n === 'string' ? { name: n, typeOnly: false } : n;
    return factory.createImportSpecifier(
      inline ?? false,
      undefined,
      factory.createIdentifier(name)
    );
  });
  return factory.createImportDeclaration(
    undefined,
    // Boolean overload (not the phase-modifier `SyntaxKind.TypeKeyword` overload, which
    // only exists in TS 5.9+): runtime-stable across our `>=5.5` peer range. The TS6387
    // deprecation hint on TS 6.x is harmless — emitted output is byte-identical.
    factory.createImportClause(typeOnly, undefined, factory.createNamedImports(specifiers)),
    factory.createStringLiteral(spec)
  );
}

/** `export [type] { <a>, <b>, … } from '<spec>';` */
function exportDeclaration(typeOnly: boolean, names: string[], spec: string): ts.ExportDeclaration {
  return factory.createExportDeclaration(
    undefined,
    typeOnly,
    factory.createNamedExports(
      names.map((name) =>
        factory.createExportSpecifier(false, undefined, factory.createIdentifier(name))
      )
    ),
    factory.createStringLiteral(spec)
  );
}

function renderTitleComment(model: ApiModel): string {
  // This banner is a raw string (it does not flow through `jsdoc()`), so escape
  // `*/` here too — `info.title`/`info.description` are attacker-controllable and
  // would otherwise close the comment and inject code at the top of every file.
  const lines = [`/**`, ` * ${escapeJsDoc(`${model.title} (v${model.version})`)}`];
  if (model.description) {
    for (const line of splitLines(escapeJsDoc(model.description))) {
      lines.push(` * ${line}`);
    }
  }
  lines.push(' */');
  return lines.join('\n');
}
