import type { ApiModel } from '../intermediate-representation/model.js';
import type { ArgsStyle } from './operations.js';
import type { PaginationConfig } from './pagination.js';
import { splitLines } from './support.js';
import { escapeJsDoc } from './ts.js';
import type { DateType } from './types.js';

// The public option vocabulary is re-exported from this module, so generators
// and the package barrel import the emitter surface from one place.
export type { ArgsStyle } from './operations.js';

/** The generated-by banner prepended to every emitted module. */
export const HEADER = `// Generated by @redocly/client-generator — do not edit by hand.
// Source: OpenAPI document. Re-run \`redocly generate-client\` to update.`;

export type EmitOptions = {
  /**
   * Override the server URL baked into the generated client config. When omitted,
   * the value is derived from `servers[0].url` in the source OpenAPI document.
   */
  serverUrl?: string;
  /**
   * How operation inputs are passed to each call. Defaults to `'flat'`;
   * `'grouped'` bundles inputs into a single `args` object.
   */
  argsStyle?: ArgsStyle;
  /** Error-handling shape of the generated client. Defaults to `'throw'`. */
  errorMode?: 'throw' | 'result';
  /**
   * How `format: date-time`/`date` string fields are typed. `'string'` (default)
   * keeps the ISO wire shape; `'Date'` emits a `Date` reference. Opt-in — pair with
   * the `transformers` generator so the runtime value matches the type.
   */
  dateType?: DateType;
  /**
   * How the `mock` generator produces data. `'static'` (default) inlines deterministic
   * literals (zero-dep, contract-faithful); `'faker'` emits `@faker-js/faker` calls for
   * realistic data — reproducible when `mockSeed` is set. Only the mock module is affected.
   */
  mockData?: 'static' | 'faker';
  /** Seed for faker-mode mocks: emits a top-level `faker.seed(<n>)` so runs reproduce. */
  mockSeed?: number;
  /**
   * A pre-baked publisher setup block (from `bakeSetup`) merged into the client's config
   * via `mergeSetup`. Absent when no `--setup` is given.
   */
  setup?: string;
  /** Runtime distribution: 'inline' (default, self-contained) | 'package' (imports @redocly/client-generator). */
  runtime?: 'inline' | 'package';
  /**
   * Extension used in generated relative import specifiers (the split entry's schemas
   * re-export and each satellite's sdk import). `'js'` (default) is the tsc/bundler
   * convention; `'ts'` targets runtimes that resolve specifiers literally, like Node's
   * built-in type stripping (`node client.ts`).
   */
  importExt?: 'js' | 'ts';
  /**
   * Auto-pagination rules (a convention rule + per-operation overrides + `exclude`),
   * resolved together with each operation's `x-pagination` extension. Verified
   * statically: an explicit rule that doesn't fit its operation fails generation.
   */
  pagination?: PaginationConfig;
};

/**
 * Assemble file content from a header banner and a printed body: the leading
 * `// Generated by …` comment and the `/** title *​/` block are structural
 * banners (not part of the printed AST), prepended with blank-line separation.
 * Trailing newline mirrors a hand-authored file.
 */
export function banner(sections: string[]): string {
  return sections.filter((s) => s.length > 0).join('\n\n') + '\n';
}

export function renderTitleComment(model: ApiModel): string {
  // This banner is a raw string (it does not flow through `jsdoc()`), so escape
  // `*/` here too — `info.title`/`info.description` are attacker-controllable and
  // would otherwise close the comment and inject code at the top of every file.
  const lines = [`/**`, ` * ${escapeJsDoc(`${model.title} (v${model.version})`)}`];
  if (model.description) {
    for (const line of splitLines(escapeJsDoc(model.description))) {
      lines.push(` * ${line}`);
    }
  }
  lines.push(' */');
  return lines.join('\n');
}
