// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`E2E lint assertions-enum-on-keys-error 1`] = `

validating /openapi.yaml...
[1] openapi.yaml:28:11 at #/paths/~1pet~1findByStatus/get/responses/200/content

Only application/json can be used

26 | '200':
27 |   description: example description
28 |   content:
   |   ^^^^^^^
29 |     application/json:
30 |       schema:

Error was generated by the assertions rule.


/openapi.yaml: validated in <test>ms

❌ Validation failed with 1 error.
run \`openapi lint --generate-ignore-file\` to add all problems to the ignore file.


`;
