// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`E2E miscellaneous apply a decorator to a specific api (when the api is specified as an alias) 1`] = `
openapi: 3.1.0
info:
  title: Test
  version: 1.0.0
paths: {}
components:
  schemas:
    Unused:
      type: string

bundling nested/openapi/main.yaml...
📦 Created a bundle for nested/openapi/main.yaml at stdout <test>ms.

`;

exports[`E2E miscellaneous apply a decorator to a specific api (without specifying the api) 1`] = `
openapi: 3.1.0
info:
  title: Test
  version: 1.0.0
paths: {}
components:
  schemas:
    Unused:
      type: string
openapi: 3.1.0
info:
  title: Test
paths: {}
components:
  schemas:
    Unused:
      type: string

bundling nested/openapi/main.yaml...
📦 Created a bundle for nested/openapi/main.yaml at stdout <test>ms.
bundling https://raw.githubusercontent.com/Redocly/redocly-cli/refs/heads/v1/__tests__/miscellaneous/apply-per-api-decorators/nested/openapi/main.yaml...
📦 Created a bundle for https://raw.githubusercontent.com/Redocly/redocly-cli/refs/heads/v1/__tests__/miscellaneous/apply-per-api-decorators/nested/openapi/main.yaml at stdout <test>ms.

`;

exports[`E2E miscellaneous lint a specific api (when the api is specified as an alias and it points to an external URL) 1`] = `

validating https://raw.githubusercontent.com/Redocly/redocly-cli/refs/heads/v1/__tests__/miscellaneous/apply-per-api-decorators/nested/openapi/main.yaml...
[1] https://raw.githubusercontent.com/Redocly/redocly-cli/refs/heads/v1/__tests__/miscellaneous/apply-per-api-decorators/nested/openapi/main.yaml:2:1 at #/info/contact

Info object should contain \`contact\` field.

1 | openapi: 3.1.0
2 | info:
  | ^^^^
3 |   title: Test
4 | paths: {}

Error was generated by the info-contact rule.


https://raw.githubusercontent.com/Redocly/redocly-cli/refs/heads/v1/__tests__/miscellaneous/apply-per-api-decorators/nested/openapi/main.yaml: validated in <test>ms

❌ Validation failed with 1 error.
run \`redocly lint --generate-ignore-file\` to add all problems to the ignore file.


`;
