import * as yaml from 'js-yaml';
import * as path from 'path';

import type { Problem } from '../types/index.js';
import { isPlainObject } from '../utils/is-plain-object.js';

/** Parsed baseline file: counts per config-relative file per rule. */
export interface BaselineFile {
  version: 1;
  files: Record<string, Record<string, number>>;
}

export interface BaselineComparison {
  /** Problems to report: non-errors, over-budget groups, and stale entries. */
  problems: Problem[];
  /** Error findings hidden because their (file, rule) count matches the baseline. */
  suppressed: number;
  /** Error findings in groups that exceed their baselined count. */
  newFindings: number;
  /** (file, rule) entries whose baselined count exceeds what this run found. */
  staleEntries: number;
}

const GENERATED_HEADER =
  '# Generated by `redocly recheck --generate-baseline`. Do not edit by hand.\n';

export function parseBaseline(content: string, sourcePath: string): BaselineFile {
  const raw = yaml.load(content);
  if (!isPlainObject(raw)) {
    throw new Error(`baseline file ${sourcePath} must be a YAML mapping`);
  }
  const { version, files } = raw;
  if (version !== 1) {
    throw new Error(`baseline file ${sourcePath} has unsupported version ${String(version)}`);
  }
  const parsed: BaselineFile = { version: 1, files: {} };
  if (files === undefined || files === null) return parsed;
  if (!isPlainObject(files)) {
    throw new Error(`baseline file ${sourcePath}: "files" must be a mapping`);
  }
  for (const [file, rules] of Object.entries(files)) {
    if (!isPlainObject(rules)) {
      throw new Error(`baseline file ${sourcePath}: entry "${file}" must map rules to counts`);
    }
    const counts: Record<string, number> = {};
    for (const [rule, count] of Object.entries(rules)) {
      if (typeof count !== 'number' || !Number.isInteger(count) || count < 1) {
        throw new Error(
          `baseline file ${sourcePath}: "${file}" / "${rule}" must be a positive integer, got ${String(count)}`
        );
      }
      counts[rule] = count;
    }
    parsed.files[file] = counts;
  }
  return parsed;
}

/** Builds a baseline from the error findings. `toKey` gives the file name stored in the baseline. */
export function buildBaseline(problems: Problem[], toKey: (file: string) => string): BaselineFile {
  // No prototype, so a file or rule named `__proto__` is an ordinary key.
  const files: Record<string, Record<string, number>> = Object.create(null);
  for (const problem of problems) {
    if (problem.severity !== 'error') continue;
    const key = toKey(problem.file);
    const rules: Record<string, number> = (files[key] ??= Object.create(null));
    rules[problem.ruleName] = (rules[problem.ruleName] ?? 0) + 1;
  }
  return { version: 1, files };
}

/** Writes the baseline with sorted keys, so unchanged input gives identical output. */
export function serializeBaseline(baseline: BaselineFile): string {
  const files: Record<string, Record<string, number>> = {};
  for (const file of Object.keys(baseline.files).sort()) {
    const rules: Record<string, number> = {};
    for (const rule of Object.keys(baseline.files[file]).sort()) {
      rules[rule] = baseline.files[file][rule];
    }
    files[file] = rules;
  }
  return GENERATED_HEADER + yaml.dump({ version: 1, files }, { sortKeys: false });
}

export interface CompareOptions {
  /** Files this run scanned, in the Problem.file form. */
  scannedFiles: string[];
  /** Rule names (full config keys) that actually ran. */
  executedRules: Set<string>;
  /** Maps a Problem.file to the config-relative key the baseline stores. */
  toKey: (file: string) => string;
  /**
   * Config-relative folders that were fully scanned. Baseline entries under them count as
   * seen even if the file was deleted, so they turn stale. Leave unset for `--changed-only`.
   */
  scanRoots?: string[];
  /** Baseline keys of files this run could not read; their entries are neither matched nor stale. */
  skipFiles?: Set<string>;
}

function underRoot(key: string, root: string): boolean {
  if (root === '' || root === '.') return true;
  return key === root || key.startsWith(`${root}/`);
}

/**
 * Applies the baseline to the problems. Only errors are affected. An entry is checked for
 * staleness only if its file was scanned and its rule ran, so `--rule`, `--changed-only` and
 * narrower paths do not cause false alarms.
 */
export function compareToBaseline(
  problems: Problem[],
  baseline: BaselineFile,
  options: CompareOptions
): BaselineComparison {
  const kept: Problem[] = [];
  let suppressed = 0;
  let newFindings = 0;

  const errorGroups = new Map<string, { key: string; rule: string; problems: Problem[] }>();
  for (const problem of problems) {
    if (problem.severity !== 'error') {
      kept.push(problem);
      continue;
    }
    const key = options.toKey(problem.file);
    const groupId = `${key}\0${problem.ruleName}`;
    const group = errorGroups.get(groupId) ?? { key, rule: problem.ruleName, problems: [] };
    group.problems.push(problem);
    errorGroups.set(groupId, group);
  }

  for (const group of errorGroups.values()) {
    const budget = options.skipFiles?.has(group.key)
      ? 0
      : (baseline.files[group.key]?.[group.rule] ?? 0);
    const found = group.problems.length;
    if (found <= budget) {
      suppressed += found;
      continue;
    }
    newFindings += found - budget;
    for (const problem of group.problems) {
      kept.push(
        budget === 0
          ? problem
          : {
              ...problem,
              message: `${problem.message} (baseline ${budget}, found ${found})`,
            }
      );
    }
  }

  // A file counts as seen if it was scanned, or if it is under a fully scanned folder
  // and was not found (a deleted file).
  const scannedKeys = new Set(options.scannedFiles.map(options.toKey));
  const staleProblems: Problem[] = [];
  for (const [file, rules] of Object.entries(baseline.files)) {
    if (options.skipFiles?.has(file)) continue;
    const seen =
      scannedKeys.has(file) || (options.scanRoots ?? []).some((root) => underRoot(file, root));
    if (!seen) continue;
    for (const [rule, budget] of Object.entries(rules)) {
      if (!options.executedRules.has(rule)) continue;
      const groupId = `${file}\0${rule}`;
      const found = errorGroups.get(groupId)?.problems.length ?? 0;
      if (found >= budget) continue;
      staleProblems.push({
        file,
        line: 1,
        column: 1,
        text: '',
        match: '',
        ruleName: rule,
        severity: 'error',
        message:
          `Baseline is stale: expected ${budget} finding(s) of ${rule}, found ${found}. ` +
          `Run \`redocly recheck --generate-baseline\` and commit the result.`,
      });
    }
  }

  return {
    problems: [...kept, ...staleProblems],
    suppressed,
    newFindings,
    staleEntries: staleProblems.length,
  };
}

/** The config-relative key mapper both `run` and `baseline` share. */
export function baselineKeyMapper(configDir: string): (file: string) => string {
  return (file: string) => path.relative(configDir, path.resolve(file)).split(path.sep).join('/');
}
