import type { ApiModel } from '@redocly/client-generator';
import { escapeJsDoc, splitLines } from '@redocly/client-generator/printers/typescript';

/** The generated-by banner prepended to every emitted module. */
export const HEADER = `// Generated by @redocly/client-generator — do not edit by hand.
// Source: OpenAPI description. Re-run \`redocly generate-client\` to update.`;

/**
 * Assemble file content from a header banner and a printed body: the leading
 * `// Generated by …` comment and the `/** title *​/` block are structural
 * banners (not part of the printed AST), prepended with blank-line separation.
 * Trailing newline mirrors a hand-authored file.
 */
export function banner(sections: string[]): string {
  return sections.filter((s) => s.length > 0).join('\n\n') + '\n';
}

export function renderTitleComment(model: ApiModel): string {
  // This banner is a raw string (it does not flow through `jsdoc()`), so escape
  // `*/` here too — `info.title`/`info.description` are attacker-controllable and
  // would otherwise close the comment and inject code at the top of every file.
  const lines = [`/**`, ` * ${escapeJsDoc(`${model.title} (v${model.version})`)}`];
  if (model.description) {
    for (const line of splitLines(escapeJsDoc(model.description))) {
      // A blank line prints as ` *` — a trailing space fails consumer formatter checks.
      lines.push(` * ${line}`.replace(/ +$/, ''));
    }
  }
  lines.push(' */');
  return lines.join('\n');
}
