// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`E2E lint oas3.1 1`] = `

validating /openapi.yaml...
[1] openapi.yaml:156:5 at #/components/schemas/Problem

Component: "Problem" is never used.

154 | pathItems: {}
155 | schemas:
156 |   Problem:
    |   ^^^^^^^
157 |     id: "https://tools.ietf.org/rfc/rfc7807.txt"
158 |     $schema: "http://json-schema.org/draft-06/schema#"

Warning was generated by the no-unused-components rule.


/openapi.yaml: validated in <test>ms

Woohoo! Your OpenAPI definition is valid. 🎉
You have 1 warning.


`;
