// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`E2E lint oas3.1-error 1`] = `

validating /openapi.yaml...
[1] openapi.yaml:1:1 at #/

Must contain at least one of the following fields: paths, components, webhooks.

 1 | openapi: 3.1.0
   | ^^^^^^^^^^^^^^
 2 | info:
   | ^^^^^
 … | < 19 more lines >
22 |         default: b
   |         ^^^^^^^^^^
23 |

Error was generated by the spec rule.


/openapi.yaml: validated in <test>ms

❌ Validation failed with 1 error.
run \`openapi lint --generate-ignore-file\` to add all problems to the ignore file.


`;
