// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`E2E lint operation-operationId-in-callback 1`] = `

validating /openapi.yaml...
[1] openapi.yaml:27:9 at #/paths/~1test/post/responses/400

Response \`4xx\` must have content-type \`application/problem+json\`.

25 |   '202':
26 |     description: Accepted
27 |   '400':
   |   ^^^^^
28 |     description: An error response
29 | callbacks:

Error was generated by the operation-4xx-problem-details-rfc7807 rule.


[2] openapi.yaml:46:17 at #/paths/~1test/post/callbacks/notification/{$request.body#~1callbackURL}/post/responses/400

Response \`4xx\` must have content-type \`application/problem+json\`.

44 | '200':
45 |   description: OK
46 | '400':
   | ^^^^^
47 |   description: An error response
48 |

Error was generated by the operation-4xx-problem-details-rfc7807 rule.


/openapi.yaml: validated in <test>ms

❌ Validation failed with 2 errors.
run \`openapi lint --generate-ignore-file\` to add all problems to the ignore file.


`;
