// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`E2E lint assertions-ref-forbidden-error 1`] = `

validating /openapi.yaml...
[1] openapi.yaml:47:17 at #/paths/~1pets/get/responses/default/content/application~1json/schema

Response MediaType schema should NOT have a ref

45 |           application/json:
46 |             schema:
47 |               $ref: ./components/schemas/Error.yaml
   |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
48 | /owners:
49 |   $ref: components/schemas/Owners.yaml

Error was generated by the ref-forbidden assertion rule.


[2] components/schemas/Owners.yaml:1:1 at #/

PathItems should NOT should have a ref

 1 | get:
   | ^^^^
 2 |   summary: List all owners
   |   ^^^^^^^^^^^^^^^^^^^^^^^^
 … |   < 24 more lines >
27 |                 type: integer
   |                 ^^^^^^^^^^^^^

Error was generated by the ref-forbidden-no-property assertion rule.


/openapi.yaml: validated in <test>ms

❌ Validation failed with 2 errors.
run \`openapi lint --generate-ignore-file\` to add all problems to the ignore file.


`;
