// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`E2E lint no-invalid-media-type-examples 1`] = `

validating openapi.yaml...
[1] example.yaml:1:1 at #/

Example value must conform to the schema: type must be string.

1 | network: social
  | ^^^^^^^^^^^^^^^
2 |

referenced from openapi.yaml:18:13 at #/paths/~1pet/get/requestBody/content/application~1json 

Error was generated by the no-invalid-media-type-examples rule.


openapi.yaml: validated in <test>ms

❌ Validation failed with 1 error.
run \`redocly lint --generate-ignore-file\` to add all problems to the ignore file.


`;
