import type { Kind } from 'graphql';

export type GraphqlNodeKind = `${Kind}`;

export const graphqlNodeKinds: GraphqlNodeKind[] = [
  'Name',
  'Document',
  'OperationDefinition',
  'VariableDefinition',
  'SelectionSet',
  'Field',
  'Argument',
  'FragmentSpread',
  'InlineFragment',
  'FragmentDefinition',
  'Variable',
  'IntValue',
  'FloatValue',
  'StringValue',
  'BooleanValue',
  'NullValue',
  'EnumValue',
  'ListValue',
  'ObjectValue',
  'ObjectField',
  'Directive',
  'NamedType',
  'ListType',
  'NonNullType',
  'SchemaDefinition',
  'OperationTypeDefinition',
  'ScalarTypeDefinition',
  'ObjectTypeDefinition',
  'FieldDefinition',
  'InputValueDefinition',
  'InterfaceTypeDefinition',
  'UnionTypeDefinition',
  'EnumTypeDefinition',
  'EnumValueDefinition',
  'InputObjectTypeDefinition',
  'DirectiveDefinition',
  'SchemaExtension',
  'DirectiveExtension',
  'ScalarTypeExtension',
  'ObjectTypeExtension',
  'InterfaceTypeExtension',
  'UnionTypeExtension',
  'EnumTypeExtension',
  'InputObjectTypeExtension',
  'TypeCoordinate',
  'MemberCoordinate',
  'ArgumentCoordinate',
  'DirectiveCoordinate',
  'DirectiveArgumentCoordinate',
];
