// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`E2E no-unused-components-warning 1`] = `
[1] openapi.yaml:17:5 at #/components/schemas/Category

Component: "Category" is never used.

15 | components:
16 |   schemas:
17 |     Category:
   |     ^^^^^^^^
18 |       type: object
19 |       properties:

warning was generated by no-unused-components rule.



Woohoo! Your OpenAPI definition is valid 🎉
You have 1 warning 


`;

exports[`E2E no-unused-components-warning! 1`] = `
[1] openapi.yaml:17:5 at #/components/schemas/Category

Component: "Category" is never used.

15 | components:
16 |   schemas:
17 |     Category:
   |     ^^^^^^^^
18 |       type: object
19 |       properties:

warning was generated by no-unused-components rule.



Woohoo! Your OpenAPI definition is valid 🎉
You have 1 warning 


`;
