// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`E2E test-unused-component 1`] = `

No configurations were defined in extends -- using built in recommended configuration by default.

validating ./openapi.yaml...
[1] openapi.yaml:8:5 at #/info/license

License object should contain \`url\` field.

 6 |   title: Swagger Petstore
 7 |   license:
 8 |     name: MIT
   |     ^^^^^^^^^
 9 | servers:
10 |   - url: http://petstore.swagger.io/v1

Warning was generated by the info-license-url rule.


[2] openapi.yaml:25:5 at #/components/parameters/anotherParam

Expected type 'string' but got 'number'

2 | info:
3 |   title: Example OpenAPI 3 definition.
4 |   version: 1.0
  |            ^^^
5 |
6 | paths:

Warning was generated by the no-unused-components rule.


[3] openapi.yaml:31:5 at #/components/schemas/Someaa

OpenAPI servers must be present.

 1 | openapi: 3.0.0
   | ^^^^^^^^^^^^^^
 2 | info:
   | ^^^^^
 … | < 8 more lines >
11 |           description: example description
   |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Warning was generated by the no-unused-components rule.


./openapi.yaml: validated in <test>ms

Woohoo! Your OpenAPI definition is valid. 🎉
You have 3 warnings.



`;
