// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`E2E lint request-response-mime-type-oas3-error 1`] = `

No configurations were defined in extends -- using built in recommended configuration by default.

validating /openapi.yaml...
[1] openapi.yaml:25:11 at #/paths/~1store~1subscribe/post/requestBody/content/application~1xml

Mime type "application/xml" is not allowed

23 | requestBody:
24 |   content:
25 |     application/xml:
   |     ^^^^^^^^^^^^^^^
26 |       schema:
27 |         type: object

Error was generated by the request-mime-type rule.


[2] openapi.yaml:56:19 at #/paths/~1store~1subscribe/post/callbacks/orderInProgress/{$request.body#~1callbackUrl}?event={$request.body#~1eventName}/post/requestBody/content/application~1xml

Mime type "application/xml" is not allowed

54 | requestBody:
55 |   content:
56 |     application/xml:
   |     ^^^^^^^^^^^^^^^
57 |       schema:
58 |         type: object

Error was generated by the response-mime-type rule.


[3] openapi.yaml:67:21 at #/paths/~1store~1subscribe/post/callbacks/orderInProgress/{$request.body#~1callbackUrl}?event={$request.body#~1eventName}/post/responses/200/content/application~1xml

Mime type "application/xml" is not allowed

65 | description: Callback successfully processed and no retries will be performed
66 | content:
67 |   application/xml:
   |   ^^^^^^^^^^^^^^^
68 |     schema:
69 |       type: object

Error was generated by the request-mime-type rule.


[4] openapi.yaml:84:11 at #/x-webhooks/newPet/post/requestBody/content/application~1xml

Mime type "application/xml" is not allowed

82 | requestBody:
83 |   content:
84 |     application/xml:
   |     ^^^^^^^^^^^^^^^
85 |       schema:
86 |         type: object

Error was generated by the response-mime-type rule.


[5] openapi.yaml:96:13 at #/x-webhooks/newPet/post/responses/200/content/application~1xml

Mime type "application/xml" is not allowed

94 | description: Return a 200 status
95 | content:
96 |   application/xml:
   |   ^^^^^^^^^^^^^^^
97 |     schema:
98 |       type: object

Error was generated by the request-mime-type rule.


/openapi.yaml: validated in <test>ms

❌ Validation failed with 5 errors.
run \`openapi lint --generate-ignore-file\` to add all problems to the ignore file.


`;
