// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`E2E lint request-response-mime-type-oas3-error 1`] = `

No configurations were defined in extends -- using built in recommended configuration by default.

validating /openapi.yaml...
[1] openapi.yaml:25:11 at #/paths/~1store~1subscribe/post/requestBody/content/application~1xml

mimeType 'application/xml' is not allowed

23 | requestBody:
24 |   content:
25 |     application/xml:
   |     ^^^^^^^^^^^^^^^
26 |       schema:
27 |         type: object

Error was generated by the request-mime-type rule.


/openapi.yaml: validated in <test>ms

❌ Validation failed with 1 error.
run \`openapi lint --generate-ignore-file\` to add all problems to the ignore file.


`;
