// Generated by @redocly/client-generator — do not edit by hand.
// Source: OpenAPI document. Re-run `redocly generate-client` to update.

/**
 * Redocly Cafe (v1.0.0)
 * Demo API for cafe operators (not customers) to manage menus, orders, and revenue.
 * Create API credentials and try it yourself in a realistic OpenAPI workflow.
 * 
 */

export type Page = {
    /**
     * Use with the `after` query parameter to load the next page of data.
     * When `null`, there is no data.
     * The cursor is opaque and internal structure is subject to change.
     */
    endCursor: string | null;
    /**
     * Use with the `before` query parameter to load the previous page of data.
     * When `null`, there is no data.
     * The cursor is opaque and internal structure is subject to change.
     */
    startCursor: string | null;
    /**
     * Indicates if there is a next page with items.
     */
    hasNextPage: boolean;
    /**
     * Indicates if there is a previous page with items.
     */
    hasPrevPage: boolean;
    /**
     * Value showing how many items are in the page limit.
     * @minimum 1
     * @maximum 100
     */
    limit: number;
    /**
     * Count of items across all pages.
     * @minimum 0
     */
    total: number;
};

export type MenuBaseItem = {
    /**
     * Created date.
     * @format date-time
     */
    readonly createdAt: string;
    /**
     * Updated date.
     * @format date-time
     */
    readonly updatedAt: string;
    /**
     * Menu item ID. Unique identifier prefixed with `prd_`.
     * @pattern ^prd_[0-9abcdefghjkmnpqrstvwxyz]{26}$
     */
    readonly id: string;
    /**
     * Entity name.
     */
    readonly object: "menuItem";
    /**
     * Menu item name.
     * @minLength 1
     * @maxLength 50
     */
    name: string;
    /**
     * Price in cents.
     * @minimum 0
     */
    price: number;
    /**
     * Photo of the menu item. Must be a PNG image and less than 1MB.
     * @format binary
     */
    photo?: Blob | null;
    /**
     * Photo URL of the menu item.
     * @format uri
     */
    readonly photoUrl?: string;
    photoTextDescription?: string | null;
};

export type Beverage = {
    /**
     * Menu item category.
     */
    category: "beverage";
    /**
     * Size of the beverage in milliliters.
     * @exclusiveMinimum 0
     */
    volume: number;
    /**
     * Indicates if the beverage contains caffeine.
     */
    containsCaffeine: boolean;
} & MenuBaseItem;

export type Dessert = {
    /**
     * Menu item category.
     */
    category: "dessert";
    /**
     * Amount of calories.
     * @exclusiveMinimum 0
     */
    calories: number;
} & MenuBaseItem;

export type MenuItem = Beverage | Dessert;

export type MenuItemList = {
    /**
     * Entity name.
     */
    object: "list";
    page: Page;
    items: MenuItem[];
};

export type Error = {
    /**
     * URI reference that identifies the problem type.
     * @format uri-reference
     */
    type: string;
    /**
     * Short summary of the problem type.
     */
    title: string;
    /**
     * HTTP status code generated by the origin server for this occurrence of the problem.
     * @minimum 100
     * @exclusiveMaximum 600
     * @format int32
     */
    status: number;
    /**
     * URI reference that identifies the specific occurrence of the problem, e.g. by adding a fragment identifier or sub-path to the problem type.
     * May be used to locate the root of this problem in the source code.
     * @format uri-reference
     */
    instance?: string;
    /**
     * Additional error details.
     */
    details?: Record<string, unknown>;
};

/**
 * Order status.
 */
export type OrderStatus = "placed" | "preparing" | "completed" | "canceled";

export const OrderStatus = {
    placed: "placed",
    preparing: "preparing",
    completed: "completed",
    canceled: "canceled"
} as const;

export type Order = {
    /**
     * Order ID. Unique identifier prefixed with `ord_`.
     * @pattern ^ord_[0-9abcdefghjkmnpqrstvwxyz]{26}$
     * @format ulid
     */
    readonly id?: string;
    /**
     * Entity name.
     */
    readonly object?: "order";
    /**
     * Name of the customer who placed the order.
     * Must start and end with a letter, and can contain letters, spaces, hyphens, and apostrophes (e.g., "John Doe", "Mary-Jane", "O'Brien").
     * @minLength 1
     * @maxLength 100
     * @pattern ^[A-Za-z]+(?:[\s'-][A-Za-z]+)*$
     */
    customerName: string;
    readonly status?: OrderStatus;
    /**
     * Total order price in cents.
     * @minimum 0
     */
    readonly totalPrice?: number;
    /**
     * Created date.
     * @format date-time
     */
    readonly createdAt?: string;
    /**
     * Updated date.
     * @format date-time
     */
    readonly updatedAt?: string;
    /**
     * List of items to include in the order.
     * @minItems 1
     */
    orderItems: {
        /**
         * ID of the menu item to add to the order.
         * @format ulid
         */
        menuItemId: string;
        /**
         * Quantity of the menu item.
         * @minimum 1
         */
        quantity: number;
        /**
         * Discount amount in cents (absolute value).
         * @minimum 0
         */
        discount?: number;
        /**
         * Optional comment for the order item (e.g., "No sugar").
         * @maxLength 500
         */
        comment?: string;
    }[];
};

export type OrderList = {
    /**
     * Entity name.
     */
    object: "list";
    page: Page;
    items: Order[];
};

export type OrderItem = {
    /**
     * ID of the menu item to add to the order.
     */
    menuItemId: string;
    /**
     * Menu item that is part of the order.
     */
    readonly menuItem?: MenuItem;
    /**
     * Quantity of the menu item.
     * @minimum 1
     */
    quantity: number;
    /**
     * Discount amount in cents (absolute value).
     * @minimum 0
     */
    discount?: number;
    /**
     * Optional comment for the order item (e.g., "No sugar").
     * @maxLength 500
     */
    comment?: string;
};

/**
 * Revenue statistics for a given date range.
 */
export type RevenueStatistics = {
    /**
     * Total revenue in cents from completed orders.
     * @minimum 0
     * @format float
     */
    revenue: number;
    /**
     * Average order amount in cents (calculated from completed orders only).
     * @minimum 0
     * @format float
     */
    averageOrderAmount: number;
    /**
     * Total number of orders (all statuses) in the date range.
     * @minimum 0
     */
    totalOrders: number;
    /**
     * Number of placed orders.
     * @minimum 0
     */
    placedOrders: number;
    /**
     * Number of preparing orders.
     * @minimum 0
     */
    preparingOrders: number;
    /**
     * Number of completed orders.
     * @minimum 0
     */
    completedOrders: number;
    /**
     * Number of canceled orders.
     * @minimum 0
     */
    canceledOrders: number;
    /**
     * Start date of the revenue calculation period.
     * @format date
     */
    startDate: string;
    /**
     * End date of the revenue calculation period.
     * @format date
     */
    endDate: string;
};

export type RegisterClientObject = {
    /**
     * Client name.
     */
    name: string;
    /**
     * List of redirect URIs (optional, defaults to empty array).
     */
    redirectUris?: string[];
    /**
     * List of scopes.
     */
    scopes?: ("menu:read" | "menu:write" | "orders:read" | "orders:write")[];
    /**
     * List of grant types.
     */
    grantTypes?: ("authorization_code" | "client_credentials")[];
};

/**
 * OAuth2 client registration response. Per RFC 7591, includes the client identifier, secret, timestamps, and all registered client metadata.
 */
export type OAuth2Client = {
    /**
     * Client identifier issued by the authorization server.
     */
    clientId: string;
    /**
     * Client secret issued by the authorization server.
     */
    clientSecret: string;
    /**
     * Time when the client_id is issued, represented as seconds since epoch (RFC7591).
     * @format int64
     */
    clientIdIssuedAt: number;
    /**
     * Time at which the client_secret expires, represented as seconds since epoch. 0 indicates the secret does not expire (RFC 7591).
     * @format int64
     */
    clientSecretExpiresAt: number;
    /**
     * Client name (registered metadata).
     */
    name?: string;
    /**
     * List of redirect URIs (registered metadata).
     */
    redirectUris?: string[];
    /**
     * URL of the client configuration endpoint for managing this client registration (RFC 7592).
     * @format uri
     */
    registrationClientUri: string;
    /**
     * Access token to be used at the client configuration endpoint for managing this client registration (RFC 7592).
     */
    registrationAccessToken: string;
    /**
     * List of scopes (registered metadata).
     */
    scopes?: ("menu:read" | "menu:write" | "orders:read" | "orders:write")[];
    /**
     * List of grant types (registered metadata).
     */
    grantTypes?: ("authorization_code" | "client_credentials")[];
};

export type OrderNotification = {
    /**
     * Unique order identifier.
     */
    orderId: string;
    orderStatus: OrderStatus;
    /**
     * When the event occurred.
     * @format date-time
     */
    timestamp: string;
};

/**
 * Narrow a `MenuItem` to `Beverage` via its `category` discriminant.
 */
export function isBeverage(value: MenuItem): value is Beverage {
    return (value as Record<string, unknown>)["category"] === "beverage";
}

/**
 * Narrow a `MenuItem` to `Dessert` via its `category` discriminant.
 */
export function isDessert(value: MenuItem): value is Dessert {
    return (value as Record<string, unknown>)["category"] === "dessert";
}

export type ListMenuItemsResult = MenuItemList;

export type ListMenuItemsParams = {
    /**
     * Use the `endCursor` as a value for the `after` parameter to get the next page.
     */
    after?: string;
    /**
     * Use the `startCursor` as a value for the `before` parameter to get the next page.
     */
    before?: string;
    /**
     * To sort by id in descending order use `-id`.
     * To sort by id in ascending order use `id`.
     */
    sort?: string;
    /**
     * Filters the collection items using space-separated `field:value` pairs.
     *
     * **Format:** `field1:value1 field2:value2`
     *
     * **Supported operators:**
     * - `field:value` - Exact match
     * - `field:value1,value2` - Match any of the comma-separated values (OR)
     * - Time ranges: Use `30d` (30 days), `7d` (7 days), `1h` (1 hour), etc.
     *
     * **Examples:**
     * - `status:placed` - Filter by single status.
     * - `status:placed,completed` - Filter by multiple statuses.
     * - `createdAt:30d` - Filter orders created in the last 30 days.
     * - `orderId:ord_01h1s5z6vf2mm1mz3hevnn9va7` - Filter by specific order ID.
     * - `status:placed createdAt:7d` - Combine multiple filters.
     */
    filter?: string;
    /**
     * Performs a case-insensitive text search across relevant fields in the collection.
     *
     * **Fields searched depend on the endpoint:**
     * - **Menu items:** `name`, `photoTextDescription`
     * - **Orders:** `customerName`, `id`
     *
     * Returns items where any of the searchable fields contain the search term as a substring.
     */
    search?: string;
    /**
     * Use to return a number of results per page.
     * If there is more data, use in combination with `after` to page through the data.
     * @minimum 1
     * @maximum 100
     */
    limit?: number;
};

export type ListMenuItemsVariables = {
    params?: ListMenuItemsParams;
};

export type CreateMenuItemResult = MenuItem;

export type CreateMenuItemBody = FormData;

export type CreateMenuItemVariables = {
    body: CreateMenuItemBody;
};

export type DeleteMenuItemResult = void;

export type DeleteMenuItemVariables = {
    /**
     * ID of the menu item to retrieve.
     * @pattern ^prd_[0-9abcdefghjkmnpqrstvwxyz]{26}$
     */
    menuItemId: string;
};

export type GetMenuItemPhotoResult = Blob | string;

export type GetMenuItemPhotoParams = {
    /**
     * Photo size to retrieve.
     */
    photoSize?: "thumbnail" | "medium" | "large";
};

export type GetMenuItemPhotoVariables = {
    /**
     * ID of the menu item to retrieve.
     * @pattern ^prd_[0-9abcdefghjkmnpqrstvwxyz]{26}$
     */
    menuItemId: string;
    params?: GetMenuItemPhotoParams;
};

export type ListOrdersResult = OrderList;

export type ListOrdersParams = {
    /**
     * Filters the collection items using space-separated `field:value` pairs.
     *
     * **Format:** `field1:value1 field2:value2`
     *
     * **Supported operators:**
     * - `field:value` - Exact match
     * - `field:value1,value2` - Match any of the comma-separated values (OR)
     * - Time ranges: Use `30d` (30 days), `7d` (7 days), `1h` (1 hour), etc.
     *
     * **Examples:**
     * - `status:placed` - Filter by single status.
     * - `status:placed,completed` - Filter by multiple statuses.
     * - `createdAt:30d` - Filter orders created in the last 30 days.
     * - `orderId:ord_01h1s5z6vf2mm1mz3hevnn9va7` - Filter by specific order ID.
     * - `status:placed createdAt:7d` - Combine multiple filters.
     */
    filter?: string;
    /**
     * To sort by id in descending order use `-id`.
     * To sort by id in ascending order use `id`.
     */
    sort?: string;
    /**
     * Use to return a number of results per page.
     * If there is more data, use in combination with `after` to page through the data.
     * @minimum 1
     * @maximum 100
     */
    limit?: number;
    /**
     * Use the `endCursor` as a value for the `after` parameter to get the next page.
     */
    after?: string;
    /**
     * Use the `startCursor` as a value for the `before` parameter to get the next page.
     */
    before?: string;
    /**
     * Performs a case-insensitive text search across relevant fields in the collection.
     *
     * **Fields searched depend on the endpoint:**
     * - **Menu items:** `name`, `photoTextDescription`
     * - **Orders:** `customerName`, `id`
     *
     * Returns items where any of the searchable fields contain the search term as a substring.
     */
    search?: string;
};

export type ListOrdersVariables = {
    params?: ListOrdersParams;
};

export type CreateOrderResult = Order;

export type CreateOrderBody = Omit<Order, "id" | "object" | "status" | "totalPrice" | "createdAt" | "updatedAt">;

export type CreateOrderVariables = {
    body: CreateOrderBody;
};

export type GetOrderByIdResult = Order;

export type GetOrderByIdHeaders = {
    /**
     * Optional client-supplied correlation ID, echoed in logs and traces.
     * @format uuid
     */
    "X-Request-Id"?: string;
};

export type GetOrderByIdVariables = {
    /**
     * ID of the order to retrieve.
     * @pattern ^ord_[0-9abcdefghjkmnpqrstvwxyz]{26}$
     */
    orderId: string;
    headers?: GetOrderByIdHeaders;
};

export type DeleteOrderResult = void;

export type DeleteOrderVariables = {
    /**
     * ID of the order to retrieve.
     * @pattern ^ord_[0-9abcdefghjkmnpqrstvwxyz]{26}$
     */
    orderId: string;
};

export type UpdateOrderResult = Order;

export type UpdateOrderBody = {
    status: OrderStatus;
};

export type UpdateOrderVariables = {
    /**
     * ID of the order to retrieve.
     * @pattern ^ord_[0-9abcdefghjkmnpqrstvwxyz]{26}$
     */
    orderId: string;
    body?: UpdateOrderBody;
};

export type ListOrderItemsResult = OrderItem[];

export type ListOrderItemsParams = {
    /**
     * Filters the collection items using space-separated `field:value` pairs.
     *
     * **Format:** `field1:value1 field2:value2`
     *
     * **Supported operators:**
     * - `field:value` - Exact match
     * - `field:value1,value2` - Match any of the comma-separated values (OR)
     * - Time ranges: Use `30d` (30 days), `7d` (7 days), `1h` (1 hour), etc.
     *
     * **Examples:**
     * - `status:placed` - Filter by single status.
     * - `status:placed,completed` - Filter by multiple statuses.
     * - `createdAt:30d` - Filter orders created in the last 30 days.
     * - `orderId:ord_01h1s5z6vf2mm1mz3hevnn9va7` - Filter by specific order ID.
     * - `status:placed createdAt:7d` - Combine multiple filters.
     */
    filter?: string;
};

export type ListOrderItemsVariables = {
    params?: ListOrderItemsParams;
};

export type GetRevenueResult = RevenueStatistics;

export type GetRevenueParams = {
    /**
     * Start date for the revenue calculation period (ISO 8601 datetime format).
     * Defaults to 30 days ago if not provided.
     * @format date
     */
    startDate?: string;
    /**
     * End date for the revenue calculation period (ISO 8601 datetime format).
     * Defaults to current time if not provided.
     * @format date
     */
    endDate?: string;
};

export type GetRevenueVariables = {
    params?: GetRevenueParams;
};

export type RegisterOAuth2ClientResult = OAuth2Client;

export type RegisterOAuth2ClientBody = RegisterClientObject;

export type RegisterOAuth2ClientVariables = {
    body: RegisterOAuth2ClientBody;
};

/**
 * Per-operation `args`/`result` shapes (plus `kind: 'sse'` for event streams) — the
 * type-level companion of `OPERATIONS` that gives `createClient<Ops>` its typed methods.
 */
export type Ops = {
    listMenuItems: {
        args: {
            params?: ListMenuItemsParams;
        };
        result: ListMenuItemsResult;
    };
    createMenuItem: {
        args: {
            body: CreateMenuItemBody;
        };
        result: CreateMenuItemResult;
    };
    deleteMenuItem: {
        args: {
            /**
             * ID of the menu item to retrieve.
             * @pattern ^prd_[0-9abcdefghjkmnpqrstvwxyz]{26}$
             */
            menuItemId: string;
        };
        result: DeleteMenuItemResult;
    };
    getMenuItemPhoto: {
        args: {
            /**
             * ID of the menu item to retrieve.
             * @pattern ^prd_[0-9abcdefghjkmnpqrstvwxyz]{26}$
             */
            menuItemId: string;
            params?: GetMenuItemPhotoParams;
        };
        result: GetMenuItemPhotoResult;
    };
    listOrders: {
        args: {
            params?: ListOrdersParams;
        };
        result: ListOrdersResult;
    };
    createOrder: {
        args: {
            body: CreateOrderBody;
        };
        result: CreateOrderResult;
    };
    getOrderById: {
        args: {
            /**
             * ID of the order to retrieve.
             * @pattern ^ord_[0-9abcdefghjkmnpqrstvwxyz]{26}$
             */
            orderId: string;
            headers?: GetOrderByIdHeaders;
        };
        result: GetOrderByIdResult;
    };
    deleteOrder: {
        args: {
            /**
             * ID of the order to retrieve.
             * @pattern ^ord_[0-9abcdefghjkmnpqrstvwxyz]{26}$
             */
            orderId: string;
        };
        result: DeleteOrderResult;
    };
    updateOrder: {
        args: {
            /**
             * ID of the order to retrieve.
             * @pattern ^ord_[0-9abcdefghjkmnpqrstvwxyz]{26}$
             */
            orderId: string;
            body?: UpdateOrderBody;
        };
        result: UpdateOrderResult;
    };
    listOrderItems: {
        args: {
            params?: ListOrderItemsParams;
        };
        result: ListOrderItemsResult;
    };
    getRevenue: {
        args: {
            params?: GetRevenueParams;
        };
        result: GetRevenueResult;
    };
    registerOAuth2Client: {
        args: {
            body: RegisterOAuth2ClientBody;
        };
        result: RegisterOAuth2ClientResult;
    };
};

/**
 * The wire-shape descriptor for every operation, keyed by operationId — the data the
 * runtime routes requests by. Also minification-safe static metadata (method, path,
 * tags) for cache keys, tracing span names, and request logging.
 */
export const OPERATIONS = {
    listMenuItems: { id: "listMenuItems", method: "GET", path: "/menu", tags: ["Products"], params: [{ name: "after", in: "query" }, { name: "before", in: "query" }, { name: "sort", in: "query" }, { name: "filter", in: "query" }, { name: "search", in: "query" }, { name: "limit", in: "query" }] },
    createMenuItem: { id: "createMenuItem", method: "POST", path: "/menu", tags: ["Products"], body: { contentType: "multipart/form-data" }, security: [[{ scheme: "OAuth2", kind: "bearer" }]] },
    deleteMenuItem: { id: "deleteMenuItem", method: "DELETE", path: "/menu/{menuItemId}", tags: ["Products"], params: [{ name: "menuItemId", in: "path" }], responseKind: "void", security: [[{ scheme: "OAuth2", kind: "bearer" }]] },
    getMenuItemPhoto: { id: "getMenuItemPhoto", method: "GET", path: "/menu-item-images/{menuItemId}", tags: ["Products"], params: [{ name: "menuItemId", in: "path" }, { name: "photoSize", in: "query" }], responseKind: "blob" },
    listOrders: { id: "listOrders", method: "GET", path: "/orders", tags: ["Orders"], params: [{ name: "filter", in: "query" }, { name: "sort", in: "query" }, { name: "limit", in: "query" }, { name: "after", in: "query" }, { name: "before", in: "query" }, { name: "search", in: "query" }], security: [[{ scheme: "OAuth2", kind: "bearer" }]] },
    createOrder: { id: "createOrder", method: "POST", path: "/orders", tags: ["Orders"], body: { contentType: "application/json" }, security: [[{ scheme: "OAuth2", kind: "bearer" }]] },
    getOrderById: { id: "getOrderById", method: "GET", path: "/orders/{orderId}", tags: ["Orders"], params: [{ name: "orderId", in: "path" }, { name: "X-Request-Id", in: "header" }], security: [[{ scheme: "OAuth2", kind: "bearer" }]] },
    deleteOrder: { id: "deleteOrder", method: "DELETE", path: "/orders/{orderId}", tags: ["Orders"], params: [{ name: "orderId", in: "path" }], responseKind: "void", security: [[{ scheme: "OAuth2", kind: "bearer" }]] },
    updateOrder: { id: "updateOrder", method: "PATCH", path: "/orders/{orderId}", tags: ["Orders"], params: [{ name: "orderId", in: "path" }], body: { contentType: "application/json" }, security: [[{ scheme: "OAuth2", kind: "bearer" }]] },
    listOrderItems: { id: "listOrderItems", method: "GET", path: "/order-items", tags: ["Orders"], params: [{ name: "filter", in: "query" }], security: [[{ scheme: "OAuth2", kind: "bearer" }]] },
    getRevenue: { id: "getRevenue", method: "GET", path: "/revenue", tags: ["Statistics"], params: [{ name: "startDate", in: "query" }, { name: "endDate", in: "query" }], security: [[{ scheme: "ApiKey", kind: "apiKey", name: "X-API-Key", in: "header" }]] },
    registerOAuth2Client: { id: "registerOAuth2Client", method: "POST", path: "/oauth2/register", tags: ["Authorization"], body: { contentType: "application/json" } }
} as const satisfies Record<string, OperationDescriptor>;

export type OperationId = keyof typeof OPERATIONS;

export type OperationPath = (typeof OPERATIONS)[OperationId]["path"];

export type OperationTag = Extract<(typeof OPERATIONS)[OperationId], {
    tags: readonly string[];
}>["tags"][number];

// ─── Embedded runtime (@redocly/client-generator, assembled per this API's needs) ───

/**
 * The public type surface of the client runtime — `@redocly/client-generator`'s
 * app-facing runtime module. Pure types, no runtime code (excluded from coverage).
 * The generator emits `OPERATIONS` literals typed
 * `satisfies Record<string, OperationDescriptor>` against this module, so an
 * incompatible runtime/generated pair fails the consumer's build (the semver skew guard).
 */

/** How one operation parameter is sent: its location plus OpenAPI query-serialization hints. */
export type ParamSpec = {
  name: string;
  in: 'path' | 'query' | 'header';
  style?: 'form' | 'spaceDelimited' | 'pipeDelimited' | 'deepObject';
  explode?: boolean;
  allowReserved?: boolean;
};

/** One security scheme, denormalized onto the operation (`scheme` names the spec's scheme). */
export type SecuritySpec =
  | { scheme: string; kind: 'bearer' | 'basic' }
  | { scheme: string; kind: 'apiKey'; name: string; in: 'header' | 'query' | 'cookie' };

/**
 * How to auto-iterate a paginated operation (drives its `.pages()`/`.items()` members).
 * `nextCursor` and `items` are RFC 6901 JSON pointers into the page (response) value.
 */
export type PaginationSpec = {
  style: 'cursor' | 'offset' | 'page';
  /** The query param the iterator advances: the cursor (`cursor`) or number (`offset`/`page`). */
  param: string;
  /** Optional page-size query param (recorded for tooling; never set by the runtime). */
  limitParam?: string;
  /** Cursor style only: pointer to the next cursor in the page. */
  nextCursor?: string;
  /** Pointer to the page's item array. */
  items: string;
};

/** The frozen data contract between generated code and the runtime: one operation's wire shape. */
export type OperationDescriptor = {
  id: string;
  method: string;
  path: string;
  tags?: readonly string[];
  params?: readonly ParamSpec[];
  /** `multipart: true` marks a typed object body serialized to FormData by the runtime. */
  body?: { contentType: string; multipart?: boolean };
  /** Defaults to `'json'` (content-type negotiation on parse). */
  responseKind?: 'json' | 'text' | 'blob' | 'void' | 'sse';
  sseDataKind?: 'json' | 'text';
  /** OR-alternatives, each an AND-set: the runtime applies the first fully-configured one. */
  security?: readonly (readonly SecuritySpec[])[];
  pagination?: PaginationSpec;
};

/** A query value: scalars, arrays of scalars, or objects (serialized as deepObject brackets). */
export type QueryValue =
  | string
  | number
  | boolean
  | null
  | undefined
  | Array<string | number | boolean | null | undefined>
  | Record<string, unknown>;

/** A credential: a literal, or a (possibly async) function resolved per request (refresh flows). */
export type TokenProvider = string | (() => string | Promise<string>);

/** Per-instance credentials, keyed by the scheme kinds the runtime can inject. */
export type AuthCredentials = {
  bearer?: TokenProvider;
  basic?: { username: string; password: string };
  apiKey?: Record<string, TokenProvider>;
};

/** Backoff shape: 'fixed' = constant delay; 'exponential' = doubling per attempt. */
export type RetryStrategy = 'fixed' | 'exponential';

/**
 * The operation's identity, exposed to middleware for targeting (`ctx.operation`).
 * Generated clients instantiate the type parameters with the spec's literal unions
 * (`OperationId`/`OperationPath`/`OperationTag`) so a misspelled operation id in a
 * middleware comparison fails to compile; the string defaults keep every
 * spec-independent consumer (`runtime-contract.ts`, the runtime internals) working
 * with the base shape. `tags` stays mutable (`Tag[]`) so setup-contract types
 * (byte-locked to generated output) remain assignable through middleware callbacks.
 */
export type OperationContext<
  Id extends string = string,
  Path extends string = string,
  Tag extends string = string,
> = { id: Id; path: Path; tags: Tag[] };

/** The mutable request context threaded through the middleware chain. */
export type RequestContext<Op extends OperationContext = OperationContext> = {
  url: string;
  method: string;
  headers: Record<string, string>;
  body?: unknown;
  operation: Op;
};

/** The failed attempt handed to a custom `retryOn`: exactly one of `response`/`error` is set. */
export type RetryContext<Op extends OperationContext = OperationContext> = {
  attempt: number;
  request: RequestContext<Op>;
  response?: Response;
  error?: unknown;
};

/** Opt-in retry policy; a per-call override merges field-by-field over the config policy. */
export type RetryConfig<Op extends OperationContext = OperationContext> = {
  retries?: number;
  retryDelay?: number;
  retryStrategy?: RetryStrategy;
  jitter?: boolean;
  retryOn?: (ctx: RetryContext<Op>) => boolean | Promise<boolean>;
};

/**
 * Structural stand-in for the runtime's ApiError so this module stays import-free
 * (pure types); the real `ApiError` class is assignable to it.
 */
export type ApiErrorLike = globalThis.Error & {
  url: string;
  status: number;
  statusText: string;
  body: unknown;
};

/** One interceptor: any subset of the three hooks. */
export type Middleware<Op extends OperationContext = OperationContext> = {
  onRequest?: (ctx: RequestContext<Op>) => void | Promise<void>;
  onResponse?: (
    response: Response,
    ctx: RequestContext<Op>
  ) => Response | void | Promise<Response | void>;
  /** Throw mode only: may map/replace the error. */
  // `globalThis.Error` so a spec schema named `Error` cannot shadow it in inline mode.
  onError?: (
    error: ApiErrorLike,
    ctx: RequestContext<Op>
  ) => globalThis.Error | Promise<globalThis.Error>;
};

/** Client configuration: transport, defaults, retry policy, middleware, and credentials. */
export type ClientConfig<Op extends OperationContext = OperationContext> = {
  serverUrl?: string;
  fetch?: typeof fetch;
  headers?:
    | Record<string, string>
    | (() => Record<string, string> | Promise<Record<string, string>>);
  retry?: RetryConfig<Op>;
  middleware?: Middleware<Op>[];
  auth?: AuthCredentials;
  /** Fixed at generate time by the generator (`'throw'` when omitted); `configure()` ignores it. */
  errorMode?: 'throw' | 'result';
  onRequest?: Middleware<Op>['onRequest'];
  onResponse?: Middleware<Op>['onResponse'];
  onError?: Middleware<Op>['onError'];
};

/** Response readers for the per-call `parseAs` override. */
export type ParseAs = 'auto' | 'json' | 'text' | 'blob' | 'arrayBuffer' | 'formData' | 'stream';

/** Per-call options: standard `RequestInit` plus a retry override and a forced reader. */
export type RequestOptions = RequestInit & { retry?: RetryConfig; parseAs?: ParseAs };

/** Per-call options for an SSE stream; reconnect defaults to true. */
export type SseOptions = RequestInit & { reconnect?: boolean; reconnectDelay?: number };

/** A single decoded Server-Sent Event with its payload typed from the spec. */
export type ServerSentEvent<T> = { event?: string; data: T; id?: string; retry?: number };

/** Result-mode return shape: exactly one of `data`/`error` is set. */
export type Result<TData, TError> =
  | { data: TData; error: undefined; response: Response }
  | { data: undefined; error: TError; response: Response };

/**
 * The generated `Ops` type's shape: per-operation args/result, plus `kind: 'sse'` for
 * streams and, for paginated operations, `item` (the page's element type) and — on
 * result-mode clients only — `page` (the RAW page type `.pages()` yields, since
 * iteration unwraps the `Result` envelope the one-shot `result` carries).
 */
export type OpsShape = Record<
  string,
  { args: object; result: unknown; kind?: 'sse'; item?: unknown; page?: unknown }
>;

/** The always-present client members (assigned after the operation loop — they win collisions). */
export type ClientCore<Op extends OperationContext = OperationContext> = {
  /** Merge into the config; note `middleware` REPLACES the chain (use `use()` to compose). */
  configure(config: ClientConfig<Op>): void;
  /** Append interceptors (composes with baked/publisher middleware). */
  use(...middleware: Middleware<Op>[]): void;
  auth: {
    bearer(token: TokenProvider): void;
    basic(username: string, password: string): void;
    apiKey(scheme: string, value: TokenProvider): void;
  };
};

/**
 * The standard TypeScript optionality probe: `{}` has no required members, so
 * `{} extends A` is true exactly when every member of `A` is optional.
 */
// oxlint-disable-next-line typescript/no-empty-object-type
type NoRequiredKeys<A> = {} extends A ? true : false;

/**
 * The page type `.pages()` yields: the RAW page declared by `page` (the generator
 * writes it only on result-mode paginated entries, whose `result` is the envelope),
 * or the method's own `result` (throw mode — already the raw page).
 */
type PageOf<Entry extends OpsShape[string]> = Entry extends { page: unknown }
  ? Entry['page']
  : Entry['result'];

/**
 * The auto-pagination members intersected onto a paginated method — present exactly when
 * the Ops entry declares `item` (the generator writes it only for paginated operations).
 * Args optionality mirrors the method's own; `unknown` otherwise (identity under `&`).
 * Iteration is error-mode-agnostic: `.pages()`/`.items()` yield raw pages/items, and a
 * failed page aborts iteration by throwing `ApiError`, even on result-mode clients; the
 * `onError` middleware hook (throw-mode-only) is not invoked.
 */
type Paginated<Entry extends OpsShape[string]> = 'item' extends keyof Entry
  ? NoRequiredKeys<Entry['args']> extends true
    ? {
        pages(args?: Entry['args'], init?: RequestOptions): AsyncGenerator<PageOf<Entry>>;
        items(args?: Entry['args'], init?: RequestOptions): AsyncGenerator<Entry['item']>;
      }
    : {
        pages(args: Entry['args'], init?: RequestOptions): AsyncGenerator<PageOf<Entry>>;
        items(args: Entry['args'], init?: RequestOptions): AsyncGenerator<Entry['item']>;
      }
  : unknown;

/** The typed instance client: one bound method per operation plus the core members. */
export type Client<Ops extends OpsShape, Op extends OperationContext = OperationContext> = {
  [K in keyof Ops]: Ops[K] extends { kind: 'sse' }
    ? NoRequiredKeys<Ops[K]['args']> extends true
      ? (
          args?: Ops[K]['args'],
          init?: SseOptions
        ) => AsyncGenerator<ServerSentEvent<Ops[K]['result']>>
      : (
          args: Ops[K]['args'],
          init?: SseOptions
        ) => AsyncGenerator<ServerSentEvent<Ops[K]['result']>>
    : (NoRequiredKeys<Ops[K]['args']> extends true
        ? (args?: Ops[K]['args'], init?: RequestOptions) => Promise<Ops[K]['result']>
        : (args: Ops[K]['args'], init?: RequestOptions) => Promise<Ops[K]['result']>) &
        Paginated<Ops[K]>;
} & ClientCore<Op>;

/** The error thrown (throw mode) for a non-2xx response, carrying the decoded error body. */
export class ApiError extends Error {
  public readonly url: string;
  public readonly status: number;
  public readonly statusText: string;
  public readonly body: unknown;
  constructor(url: string, status: number, statusText: string, body: unknown) {
    super(`Request failed with status ${status}`);
    this.name = 'ApiError';
    this.url = url;
    this.status = status;
    this.statusText = statusText;
    this.body = body;
  }
}

/** The error to throw for an aborted request: the caller's abort reason when it is an Error. */
// `globalThis.Error` (not bare `Error`) so a spec schema named `Error` cannot shadow it
// when this module is embedded alongside generated types (inline mode).
function abortError(signal: AbortSignal): globalThis.Error {
  const reason = (signal as { reason?: unknown }).reason;
  if (reason instanceof Error) return reason;
  return new DOMException('The operation was aborted.', 'AbortError');
}

/**
 * The RESOLVED OpenAPI serialization spec for one query parameter — callers apply the
 * OpenAPI defaults (`style: 'form'`, `explode: true`) before building one.
 */
type QueryStyle = {
  style: NonNullable<ParamSpec['style']>;
  explode: boolean;
  allowReserved?: boolean;
};

/**
 * Encode everything except the RFC-3986 reserved set, for `allowReserved: true` params —
 * `filter=a/b` survives instead of `filter=a%2Fb`.
 */
function encodeReserved(value: string): string {
  return encodeURIComponent(value).replace(
    /%(3A|2F|3F|23|5B|5D|40|21|24|26|27|28|29|2A|2B|2C|3B|3D)/g,
    (match) => decodeURIComponent(match)
  );
}

/** Substitute `{name}` template segments with encoded values; a missing value is a caller bug. */
function substitutePath(template: string, values: Record<string, unknown>): string {
  return template.replace(/\{([^{}]+)\}/g, (_match, name: string) => {
    const value = values[name];
    if (value === undefined) throw new Error(`Missing path parameter "${name}"`);
    return encodeURIComponent(String(value));
  });
}

/**
 * Build the request URL: `serverUrl` (trailing slash trimmed) + path + serialized query.
 * Query parameters honor their OpenAPI `style`/`explode`/`allowReserved` (from `styles`);
 * without a spec, arrays repeat the key (`form`+`explode`), objects serialize as
 * `deepObject` brackets, and `null`/`undefined` entries are skipped.
 */
function buildUrl(
  serverUrl: string,
  path: string,
  query?: Record<string, QueryValue>,
  styles?: Record<string, QueryStyle>
): string {
  // Trim trailing slashes with a scan, not `/\/+$/` — an anchored `+` regex is
  // quadratic on adversarial many-slash input (the server URL is caller data).
  let end = serverUrl.length;
  while (end > 0 && serverUrl.charCodeAt(end - 1) === 47 /* '/' */) end--;
  const url = serverUrl.slice(0, end) + path;
  if (!query) return url;
  const params = new URLSearchParams();
  const raw: string[] = [];
  for (const [key, value] of Object.entries(query)) {
    if (value === undefined || value === null) continue;
    const spec = styles?.[key];
    if (!spec) {
      if (Array.isArray(value)) {
        for (const v of value) {
          if (v !== undefined && v !== null) params.append(key, String(v));
        }
      } else if (Object(value) === value) {
        // Object-valued query params use `deepObject` style: key[subKey]=subValue.
        for (const [subKey, subValue] of Object.entries(value)) {
          if (subValue !== undefined && subValue !== null) {
            params.append(`${key}[${subKey}]`, String(subValue));
          }
        }
      } else {
        params.append(key, String(value));
      }
      continue;
    }
    if (Array.isArray(value)) {
      const items = value.filter((v) => v !== undefined && v !== null).map(String);
      if (spec.style === 'form' && spec.explode) {
        for (const v of items) {
          if (spec.allowReserved) raw.push(`${key}=${encodeReserved(v)}`);
          else params.append(key, v);
        }
      } else {
        // Delimited styles put the LITERAL delimiter on the wire; only the
        // values are encoded. `%20` (not `+`) is the literal space delimiter.
        const delim =
          spec.style === 'pipeDelimited' ? '|' : spec.style === 'spaceDelimited' ? '%20' : ',';
        const enc = spec.allowReserved ? encodeReserved : encodeURIComponent;
        raw.push(`${encodeURIComponent(key)}=${items.map(enc).join(delim)}`);
      }
    } else if (Object(value) === value) {
      // `deepObject` (and any object spec, for now): key[subKey]=subValue.
      for (const [subKey, subValue] of Object.entries(value)) {
        if (subValue !== undefined && subValue !== null) {
          if (spec.allowReserved) raw.push(`${key}[${subKey}]=${encodeReserved(String(subValue))}`);
          else params.append(`${key}[${subKey}]`, String(subValue));
        }
      }
    } else if (spec.allowReserved) {
      raw.push(`${key}=${encodeReserved(String(value))}`);
    } else {
      params.append(key, String(value));
    }
  }
  const qs = [params.toString(), ...raw].filter(Boolean).join('&');
  return qs ? `${url}?${qs}` : url;
}

/**
 * Read the response body per `kind`. `'auto'` negotiates from the content type
 * (JSON, then `text/*`, then Blob); `'void'` and `204` responses read nothing.
 */
async function parse(response: Response, kind: ParseAs | 'void'): Promise<unknown> {
  if (kind === 'void' || response.status === 204) return undefined;
  if (kind === 'stream') return response.body;
  if (kind === 'blob') return response.blob();
  if (kind === 'arrayBuffer') return response.arrayBuffer();
  if (kind === 'formData') return response.formData();
  if (kind === 'text') return response.text();
  if (kind === 'json') return response.json();
  // 'auto' — negotiate from the response's content type (case-insensitively:
  // `Text/Plain` and `application/JSON` are valid per RFC 9110).
  const contentType = (response.headers.get('content-type') ?? '').toLowerCase();
  if (contentType.includes('json')) return response.json();
  if (contentType.startsWith('text/')) return response.text();
  return response.blob();
}

/** Best-effort decode of a non-2xx body (JSON when declared, else text; undefined on failure). */
async function readError(response: Response): Promise<unknown> {
  const contentType = response.headers.get('content-type') ?? '';
  if (contentType.toLowerCase().includes('json')) {
    return response.json().catch(() => undefined);
  }
  return response.text().catch(() => undefined);
}

const IDEMPOTENT_METHODS = new Set(['GET', 'HEAD', 'PUT', 'DELETE', 'OPTIONS']);
const TRANSIENT_STATUS = new Set([408, 429, 500, 502, 503, 504]);

/**
 * The default retry predicate: idempotent methods only, on a transport error or a
 * transient status. A custom `retryOn` fully replaces this (no method check kept).
 */
function defaultRetryOn(ctx: RetryContext): boolean {
  if (!IDEMPOTENT_METHODS.has(ctx.request.method.toUpperCase())) return false;
  return ctx.response === undefined || TRANSIENT_STATUS.has(ctx.response.status);
}

/**
 * The delay before the next attempt: a `Retry-After` header (seconds or HTTP-date)
 * wins; otherwise fixed/exponential backoff over `retryDelay`, with full jitter
 * unless `jitter === false`.
 */
function retryDelay(retry: RetryConfig, attempt: number, retryAfter: string | null): number {
  if (retryAfter) {
    const seconds = Number(retryAfter);
    if (!Number.isNaN(seconds)) return seconds * 1000;
    const when = Date.parse(retryAfter);
    if (!Number.isNaN(when)) return Math.max(0, when - Date.now());
  }
  const base = retry.retryDelay ?? 1000;
  const raw = retry.retryStrategy === 'fixed' ? base : base * Math.pow(2, attempt - 1);
  return retry.jitter === false ? raw : Math.random() * raw;
}

/** Abort-aware sleep: resolves after `ms`, rejects with the abort reason immediately on abort. */
function sleep(ms: number, signal?: AbortSignal): Promise<void> {
  return new Promise((resolve, reject) => {
    if (signal?.aborted) {
      reject(abortError(signal));
      return;
    }
    const onAbort = () => {
      clearTimeout(timer);
      reject(abortError(signal as AbortSignal));
    };
    const timer = setTimeout(() => {
      if (signal) signal.removeEventListener('abort', onAbort);
      resolve();
    }, ms);
    if (signal) signal.addEventListener('abort', onAbort, { once: true });
  });
}

/** Resolve a credential: a literal passes through; a function is awaited per request. */
async function resolveToken(provider: TokenProvider): Promise<string> {
  return typeof provider === 'function' ? await provider() : provider;
}

/** UTF-8-safe base64: bare `btoa` throws on non-Latin-1 credentials (RFC 7617 allows UTF-8). */
function encodeBase64(text: string): string {
  let binary = '';
  for (const byte of new TextEncoder().encode(text)) binary += String.fromCharCode(byte);
  return btoa(binary);
}

/** Whether a credential for this scheme is configured on the instance. */
function isConfigured(scheme: SecuritySpec, config: ClientConfig): boolean {
  if (scheme.kind === 'apiKey') return config.auth?.apiKey?.[scheme.scheme] !== undefined;
  if (scheme.kind === 'bearer') return config.auth?.bearer !== undefined;
  return config.auth?.basic !== undefined;
}

/**
 * Build the auth headers/query for one operation's `security` OR-alternatives from the
 * instance credentials (`config.auth`) — capability module, wired into `createClient`.
 * The first alternative whose schemes (an AND-set) are all configured is applied, so
 * "bearer OR apiKey" works with either credential and never sends both. When none is
 * fully configured, the first alternative's configured schemes are still sent (the
 * server rejects the request, mirroring the previous behavior).
 * Cookie-borne apiKeys fold into a single `Cookie` header joined with `; `.
 */
async function resolveAuth(
  security: readonly (readonly SecuritySpec[])[],
  config: ClientConfig
): Promise<{ headers: Record<string, string>; query: Record<string, string> }> {
  const alternative =
    security.find((schemes) => schemes.every((scheme) => isConfigured(scheme, config))) ??
    security[0] ??
    [];
  const headers: Record<string, string> = {};
  const query: Record<string, string> = {};
  const cookies: string[] = [];
  for (const scheme of alternative) {
    if (scheme.kind === 'apiKey') {
      const provider = config.auth?.apiKey?.[scheme.scheme];
      if (provider === undefined) continue;
      const value = await resolveToken(provider);
      if (scheme.in === 'header') headers[scheme.name] = value;
      else if (scheme.in === 'query') query[scheme.name] = value;
      // Cookie values may contain reserved characters (`;`, `=`, space, …); percent-encode
      // so the credential can't break the `Cookie` header syntax.
      else cookies.push(`${scheme.name}=${encodeURIComponent(value)}`);
    } else if (scheme.kind === 'bearer') {
      const provider = config.auth?.bearer;
      if (provider !== undefined) headers.Authorization = `Bearer ${await resolveToken(provider)}`;
    } else {
      const basic = config.auth?.basic;
      if (basic !== undefined) {
        headers.Authorization = `Basic ${encodeBase64(`${basic.username}:${basic.password}`)}`;
      }
    }
  }
  if (cookies.length > 0) headers.Cookie = cookies.join('; ');
  return { headers, query };
}

/**
 * Optional behaviors the send core can use but never statically imports — wired by
 * `createClient` (the same seam the future inline-mode assembler relies on).
 */
type SendCapabilities = {
  /** Serialize a typed multipart body (a plain object) to FormData. */
  serializeMultipart?: (body: Record<string, unknown>) => FormData;
};

/**
 * Normalize a caller's `HeadersInit` (plain record, `Headers` instance, or entry pairs)
 * to a plain record — spreading a `Headers` or an array contributes no entries.
 */
function toHeaderRecord(headers: HeadersInit | undefined): Record<string, string> {
  if (headers === undefined) return {};
  if (headers instanceof Headers) {
    const record: Record<string, string> = {};
    headers.forEach((value, key) => {
      record[key] = value;
    });
    return record;
  }
  if (Array.isArray(headers)) return Object.fromEntries(headers);
  return headers;
}

/**
 * The effective middleware chain for a request: the single `onRequest`/`onResponse`/
 * `onError` config hooks as one implicit first middleware, then `config.middleware`.
 */
function middlewareChain(config: ClientConfig): Middleware[] {
  const single =
    config.onRequest || config.onResponse || config.onError
      ? [{ onRequest: config.onRequest, onResponse: config.onResponse, onError: config.onError }]
      : [];
  return [...single, ...(config.middleware ?? [])];
}

/**
 * The fetch core shared by every operation: default + config + per-call headers, the
 * `onRequest` chain (BEFORE body serialization, so mutations are sent), body
 * serialization (JSON, or FormData via the multipart capability), the retry loop
 * (idempotent-only defaults, `Retry-After`, abandoned-body drain), and the reverse
 * `onResponse` onion. Returns the final response plus the request context.
 */
async function send(
  config: ClientConfig,
  op: OperationContext,
  url: string,
  init: RequestOptions,
  body: unknown | undefined,
  multipart: boolean,
  caps: SendCapabilities
): Promise<{ response: Response; context: RequestContext }> {
  const { retry: callRetry, ...fetchInit } = init;
  const retry: RetryConfig = { ...config.retry, ...callRetry };
  const extra = typeof config.headers === 'function' ? await config.headers() : config.headers;
  const headers: Record<string, string> = {
    Accept: 'application/json',
    ...extra,
    ...toHeaderRecord(fetchInit.headers),
  };
  const context: RequestContext = {
    url,
    method: fetchInit.method ?? 'GET',
    headers,
    body,
    operation: op,
  };
  const middleware = middlewareChain(config);
  for (const mw of middleware) if (mw.onRequest) await mw.onRequest(context);
  // Serialize AFTER onRequest so body mutations (case conversion, enveloping, signing) take effect.
  let payload: BodyInit | undefined;
  if (context.body !== undefined) {
    const value = context.body;
    const isBinary =
      value instanceof Blob ||
      value instanceof ArrayBuffer ||
      ArrayBuffer.isView(value as ArrayBufferView);
    const isFormData = typeof FormData !== 'undefined' && value instanceof FormData;
    const isURLSearchParams = value instanceof URLSearchParams;
    if (isFormData || isURLSearchParams || isBinary || typeof value === 'string') {
      payload = value as BodyInit;
    } else if (multipart) {
      if (!caps.serializeMultipart) {
        throw new Error('Multipart capability not wired: cannot serialize the request body');
      }
      payload = caps.serializeMultipart(value as Record<string, unknown>);
    } else {
      payload = JSON.stringify(value);
      if (!('Content-Type' in context.headers) && !('content-type' in context.headers)) {
        context.headers['Content-Type'] = 'application/json';
      }
    }
  }
  const doFetch = config.fetch ?? fetch;
  const maxAttempts = 1 + (retry.retries ?? 0);
  const retryOn = retry.retryOn ?? defaultRetryOn;
  const signal = fetchInit.signal ?? undefined;

  let attempt = 0;
  while (true) {
    attempt++;
    if (signal?.aborted) throw abortError(signal);
    let response: Response;
    try {
      response = await doFetch(context.url, {
        ...fetchInit,
        method: context.method,
        headers: context.headers,
        body: payload,
      });
    } catch (error) {
      if (
        attempt < maxAttempts &&
        !signal?.aborted &&
        (await retryOn({ attempt, request: context, error }))
      ) {
        await sleep(retryDelay(retry, attempt, null), signal);
        continue;
      }
      throw error;
    }
    // Reverse order: the last-registered middleware wraps closest to the network (onion).
    for (let i = middleware.length - 1; i >= 0; i--) {
      const onResponse = middleware[i].onResponse;
      if (onResponse) {
        const replaced = await onResponse(response, context);
        if (replaced) response = replaced;
      }
    }
    if (
      !response.ok &&
      attempt < maxAttempts &&
      !signal?.aborted &&
      (await retryOn({ attempt, request: context, response }))
    ) {
      const retryAfter = response.headers.get('retry-after');
      // Drain the abandoned response body before the next attempt: an unread body
      // keeps the connection checked out (and can stall the pool) under Node/undici
      // and other strict HTTP clients. Ignore errors (e.g. a middleware already read it).
      await response.body?.cancel().catch(() => undefined);
      await sleep(retryDelay(retry, attempt, retryAfter), signal);
      continue;
    }
    return { response, context };
  }
}

/**
 * The optional behaviors `createClientCore` can dispatch to but never statically
 * imports. The package's public `createClient` wires the full set; the future
 * inline-mode assembler wires only the capabilities a spec needs.
 */
type Capabilities = SendCapabilities & {
  resolveAuth?: (
    security: readonly (readonly SecuritySpec[])[],
    config: ClientConfig
  ) => Promise<{ headers: Record<string, string>; query: Record<string, string> }>;
  sse?: (
    config: ClientConfig,
    op: OperationContext,
    // Re-preparing per (re)connect (not a frozen url/init) lets a refresh-style
    // TokenProvider issue a fresh credential after a dropped stream reconnects.
    prepare: () => Promise<{ url: string; init: SseOptions }>,
    dataKind: 'json' | 'text'
  ) => AsyncGenerator<ServerSentEvent<unknown>>;
  paginate?: {
    pages: (
      call: (args?: OperationArgs, init?: RequestOptions) => Promise<unknown>,
      spec: PaginationSpec,
      args?: OperationArgs,
      init?: RequestOptions
    ) => AsyncGenerator<unknown>;
    items: (
      call: (args?: OperationArgs, init?: RequestOptions) => Promise<unknown>,
      spec: PaginationSpec,
      args?: OperationArgs,
      init?: RequestOptions
    ) => AsyncGenerator<unknown>;
  };
};

/** The grouped args wire shape: path params by name plus the `params`/`body`/`headers` slots. */
type OperationArgs = {
  params?: Record<string, QueryValue>;
  body?: unknown;
  headers?: Record<string, unknown>;
} & Record<string, unknown>;

/** The response reader implied by the descriptor (before any per-call `parseAs` override). */
function kindFor(op: OperationDescriptor): ParseAs | 'void' {
  if (op.responseKind === 'void' || op.responseKind === 'blob' || op.responseKind === 'text') {
    return op.responseKind;
  }
  return 'auto';
}

/** Route the grouped args by the descriptor: path values, query object, body, extra headers. */
function splitArgs(op: OperationDescriptor, args: OperationArgs) {
  const path: Record<string, unknown> = {};
  for (const param of op.params ?? []) {
    if (param.in === 'path') path[param.name] = args[param.name];
  }
  return { path, query: args.params, body: args.body, headers: args.headers };
}

/**
 * The query-serialization hints for the descriptor's query params. A spec is built only
 * when the param deviates from the OpenAPI defaults (`form` + `explode: true`, encoded),
 * and always fully resolved — so `explode: false` or `allowReserved` alone (no `style`)
 * are honored, and an omitted `explode` keeps the exploded default.
 */
function queryStyles(op: OperationDescriptor): Record<string, QueryStyle> | undefined {
  let styles: Record<string, QueryStyle> | undefined;
  for (const param of op.params ?? []) {
    if (param.in !== 'query') continue;
    const deviates =
      (param.style !== undefined && param.style !== 'form') ||
      param.explode === false ||
      param.allowReserved === true;
    if (!deviates) continue;
    styles ??= {};
    styles[param.name] = {
      style: param.style ?? 'form',
      explode: param.explode ?? true,
      allowReserved: param.allowReserved,
    };
  }
  return styles;
}

/** Stringify caller-supplied extra headers, skipping empty entries. */
function stringHeaders(headers: Record<string, unknown> | undefined): Record<string, string> {
  const out: Record<string, string> = {};
  for (const [key, value] of Object.entries(headers ?? {})) {
    if (value !== undefined && value !== null) out[key] = String(value);
  }
  return out;
}

/** Build the request pieces an attempt needs: the final URL and the merged per-call init. */
async function prepareRequest(
  config: ClientConfig,
  op: OperationDescriptor,
  args: OperationArgs,
  init: RequestOptions | SseOptions,
  caps: Capabilities
): Promise<{ url: string; init: RequestOptions; body: unknown }> {
  const { path, query, body, headers } = splitArgs(op, args);
  const authed =
    op.security?.length && caps.resolveAuth
      ? await caps.resolveAuth(op.security, config)
      : { headers: {}, query: {} };
  const fullQuery: Record<string, QueryValue> = { ...query, ...authed.query };
  const url = buildUrl(
    config.serverUrl ?? '',
    substitutePath(op.path, path),
    Object.keys(fullQuery).length > 0 ? fullQuery : undefined,
    queryStyles(op)
  );
  const mergedInit: RequestOptions = {
    ...init,
    method: op.method.toUpperCase(),
    // Precedence, lowest → highest (later spreads win): injected auth → explicit
    // header params → caller `init.headers` — the caller always overrides both.
    headers: {
      ...authed.headers,
      ...stringHeaders(headers),
      ...toHeaderRecord(init.headers),
    },
  };
  return { url, init: mergedInit, body };
}

/** One non-SSE call: send, then branch on the configured error mode. */
async function execute(
  config: ClientConfig,
  op: OperationDescriptor,
  args: OperationArgs,
  init: RequestOptions,
  caps: Capabilities
): Promise<unknown> {
  const prepared = await prepareRequest(config, op, args, init, caps);
  const opCtx: OperationContext = { id: op.id, path: op.path, tags: [...(op.tags ?? [])] };
  const { parseAs, ...sendInit } = prepared.init;
  const { response, context } = await send(
    config,
    opCtx,
    prepared.url,
    sendInit,
    prepared.body,
    op.body?.multipart === true,
    caps
  );
  const readKind = parseAs ?? kindFor(op);
  if (config.errorMode === 'result') {
    if (!response.ok) {
      return { data: undefined, error: await readError(response), response };
    }
    return { data: await parse(response, readKind), error: undefined, response };
  }
  if (!response.ok) {
    let error: globalThis.Error = new ApiError(
      context.url,
      response.status,
      response.statusText,
      await readError(response)
    );
    // Thread the error through each middleware's onError in turn (each may replace it).
    for (const mw of middlewareChain(config)) {
      if (mw.onError) error = await mw.onError(error as ApiErrorLike, context);
    }
    throw error;
  }
  return parse(response, readKind);
}

/** The paginate capability, or a descriptive throw when a paginated op is iterated unwired. */
function paginateCapability(caps: Capabilities, op: OperationDescriptor) {
  if (!caps.paginate) {
    throw new Error(`Pagination capability not wired: cannot iterate operation "${op.id}"`);
  }
  return caps.paginate;
}

/**
 * The per-page call the iterators drive: the method itself in throw mode; in result
 * mode a wrapper that unwraps the `{ data, error, response }` envelope — the page
 * pointers are data-rooted — rethrowing a failed page as `ApiError` (iteration is
 * error-mode-agnostic; the throw-mode-only `onError` middleware hook is not invoked).
 */
function pageCall(
  method: (args?: OperationArgs, init?: RequestOptions) => Promise<unknown>,
  config: ClientConfig
) {
  if (config.errorMode !== 'result') return method;
  return async (args?: OperationArgs, init?: RequestOptions) => {
    const envelope = (await method(args, init)) as {
      data: unknown;
      error: unknown;
      response: Response;
    };
    // Failure is `!response.ok` — NOT `data === undefined`: a successful bodyless page
    // (204/void) also parses to undefined data, and a failed page's `error` can be
    // undefined too (unreadable body). The pointers then miss on the undefined data
    // and iteration stops cleanly, which is the correct semantics for an empty page.
    if (!envelope.response.ok) {
      const { response } = envelope;
      throw new ApiError(response.url, response.status, response.statusText, envelope.error);
    }
    return envelope.data;
  };
}

/**
 * Build a typed instance client over operation descriptors: one real bound method per
 * operation (attached by a construction-time loop — no Proxy), plus the core members
 * (`configure`/`use`/`auth`), which are assigned AFTER the loop so they win any name
 * collision with an operation. All behavior dispatches through the capability seam.
 */
function createClientCore<
  Ops extends OpsShape,
  Id extends string = string,
  Path extends string = string,
  Tag extends string = string,
>(
  operations: Record<string, OperationDescriptor>,
  initial: ClientConfig<OperationContext<Id, Path, Tag>> = {},
  caps: Capabilities = {}
): Client<Ops, OperationContext<Id, Path, Tag>> {
  // The literal-union narrowing is a compile-time DX contract only; internally the
  // runtime works with the base (string-typed) context. One cast at this boundary —
  // `ClientConfig<Narrow>` is not assignable to `ClientConfig` (middleware ctx
  // params are contravariant).
  const given = initial as ClientConfig;
  // Private mutable config; the middleware array is copied so `use()` never mutates the caller's.
  const config: ClientConfig = { ...given, middleware: [...(given.middleware ?? [])] };
  const client = {} as Record<string, unknown>;

  for (const [name, op] of Object.entries(operations)) {
    if (op.responseKind === 'sse') {
      client[name] = (args: OperationArgs = {}, init: SseOptions = {}) => {
        if (!caps.sse) {
          throw new Error(`SSE capability not wired: cannot stream operation "${op.id}"`);
        }
        const stream = caps.sse;
        return (async function* () {
          const opCtx: OperationContext = { id: op.id, path: op.path, tags: [...(op.tags ?? [])] };
          // A thunk the stream re-runs on every (re)connect, so auth (which `prepareRequest`
          // resolves) is refreshed per attempt rather than frozen at the first connect.
          const prepare = async () => {
            const prepared = await prepareRequest(config, op, args, init, caps);
            return { url: prepared.url, init: prepared.init as SseOptions };
          };
          yield* stream(config, opCtx, prepare, op.sseDataKind ?? 'text');
        })();
      };
    } else {
      const method = (args: OperationArgs = {}, init: RequestOptions = {}) =>
        execute(config, op, args, init, caps);
      const spec = op.pagination;
      // Paginated ops keep their one-shot call and gain `.pages`/`.items`, dispatching
      // through the capability seam (like SSE: absent capability throws descriptively).
      // Iteration is error-mode-agnostic: the iterators' pointers are data-rooted, so on
      // a result-mode client (`errorMode` is fixed at construction — `configure()`
      // ignores it) each page's envelope is unwrapped before it reaches the capability.
      // A failed page aborts iteration by throwing ApiError, even on result-mode
      // clients; the `onError` middleware hook (throw-mode-only) is not invoked.
      client[name] = spec
        ? Object.assign(method, {
            pages: (args?: OperationArgs, init?: RequestOptions) =>
              paginateCapability(caps, op).pages(pageCall(method, config), spec, args, init),
            items: (args?: OperationArgs, init?: RequestOptions) =>
              paginateCapability(caps, op).items(pageCall(method, config), spec, args, init),
          })
        : method;
    }
  }

  // Core members are assigned AFTER the operation loop — they win over colliding op names.
  client.configure = (next: ClientConfig): void => {
    // `errorMode` is fixed at generate time (it shapes the static types); flipping it at
    // runtime would silently desync return shapes from `Client<Ops>`, so it is ignored.
    const { errorMode: _fixed, auth, ...rest } = next;
    Object.assign(config, rest);
    // `auth` merges into existing credentials (like the `auth.*` setters) rather than
    // replacing wholesale — so `configure({ auth: { bearer } })` keeps a previously set
    // basic/apiKey. `apiKey` merges per scheme.
    if (auth) {
      config.auth = {
        ...config.auth,
        ...auth,
        ...(auth.apiKey ? { apiKey: { ...config.auth?.apiKey, ...auth.apiKey } } : {}),
      };
    }
  };
  client.use = (...middleware: Middleware[]): void => {
    // Reassign (don't push) so a caller-provided `middleware` array isn't mutated.
    config.middleware = [...(config.middleware ?? []), ...middleware];
  };
  client.auth = {
    bearer(token: TokenProvider): void {
      config.auth = { ...config.auth, bearer: token };
    },
    basic(username: string, password: string): void {
      config.auth = { ...config.auth, basic: { username, password } };
    },
    apiKey(scheme: string, value: TokenProvider): void {
      config.auth = { ...config.auth, apiKey: { ...config.auth?.apiKey, [scheme]: value } };
    },
  };

  return client as Client<Ops, OperationContext<Id, Path, Tag>>;
}

/**
 * The client factory: `createClientCore` wired with the capabilities this API needs.
 * Exported so apps can build additional instances (per-tenant, per-environment) over
 * the same `OPERATIONS`/`Ops`. The trailing string params carry the wiring's literal
 * unions (`OperationId`/`OperationPath`/`OperationTag`) into `ctx.operation`.
 */
export function createClient<
  Ops extends OpsShape,
  Id extends string = string,
  Path extends string = string,
  Tag extends string = string,
>(
  operations: Record<string, OperationDescriptor>,
  config?: ClientConfig<OperationContext<Id, Path, Tag>>
): Client<Ops, OperationContext<Id, Path, Tag>> {
  return createClientCore<Ops, Id, Path, Tag>(operations, config, { resolveAuth });
}

export const client = createClient<Ops, OperationId, OperationPath, OperationTag>(OPERATIONS, { serverUrl: "https://api.cafe.redocly.com" });

export const { configure, use } = client;
export const setBearer = client.auth.bearer;
export const setApiKey = (value: TokenProvider) => client.auth.apiKey("ApiKey", value);
export const listMenuItems = (params: {
    /**
     * Use the `endCursor` as a value for the `after` parameter to get the next page.
     */
    after?: string;
    /**
     * Use the `startCursor` as a value for the `before` parameter to get the next page.
     */
    before?: string;
    /**
     * To sort by id in descending order use `-id`.
     * To sort by id in ascending order use `id`.
     */
    sort?: string;
    /**
     * Filters the collection items using space-separated `field:value` pairs.
     *
     * **Format:** `field1:value1 field2:value2`
     *
     * **Supported operators:**
     * - `field:value` - Exact match
     * - `field:value1,value2` - Match any of the comma-separated values (OR)
     * - Time ranges: Use `30d` (30 days), `7d` (7 days), `1h` (1 hour), etc.
     *
     * **Examples:**
     * - `status:placed` - Filter by single status.
     * - `status:placed,completed` - Filter by multiple statuses.
     * - `createdAt:30d` - Filter orders created in the last 30 days.
     * - `orderId:ord_01h1s5z6vf2mm1mz3hevnn9va7` - Filter by specific order ID.
     * - `status:placed createdAt:7d` - Combine multiple filters.
     */
    filter?: string;
    /**
     * Performs a case-insensitive text search across relevant fields in the collection.
     *
     * **Fields searched depend on the endpoint:**
     * - **Menu items:** `name`, `photoTextDescription`
     * - **Orders:** `customerName`, `id`
     *
     * Returns items where any of the searchable fields contain the search term as a substring.
     */
    search?: string;
    /**
     * Use to return a number of results per page.
     * If there is more data, use in combination with `after` to page through the data.
     * @minimum 1
     * @maximum 100
     */
    limit?: number;
} = {}, init: RequestOptions = {}) => client.listMenuItems({ params }, init);
export const createMenuItem = (body: FormData, init: RequestOptions = {}) => client.createMenuItem({ body }, init);
export const deleteMenuItem = (menuItemId: string, init: RequestOptions = {}) => client.deleteMenuItem({ menuItemId }, init);
export const getMenuItemPhoto = (menuItemId: string, params: {
    /**
     * Photo size to retrieve.
     */
    photoSize?: "thumbnail" | "medium" | "large";
} = {}, init: RequestOptions = {}) => client.getMenuItemPhoto({ menuItemId, params }, init);
export const listOrders = (params: {
    /**
     * Filters the collection items using space-separated `field:value` pairs.
     *
     * **Format:** `field1:value1 field2:value2`
     *
     * **Supported operators:**
     * - `field:value` - Exact match
     * - `field:value1,value2` - Match any of the comma-separated values (OR)
     * - Time ranges: Use `30d` (30 days), `7d` (7 days), `1h` (1 hour), etc.
     *
     * **Examples:**
     * - `status:placed` - Filter by single status.
     * - `status:placed,completed` - Filter by multiple statuses.
     * - `createdAt:30d` - Filter orders created in the last 30 days.
     * - `orderId:ord_01h1s5z6vf2mm1mz3hevnn9va7` - Filter by specific order ID.
     * - `status:placed createdAt:7d` - Combine multiple filters.
     */
    filter?: string;
    /**
     * To sort by id in descending order use `-id`.
     * To sort by id in ascending order use `id`.
     */
    sort?: string;
    /**
     * Use to return a number of results per page.
     * If there is more data, use in combination with `after` to page through the data.
     * @minimum 1
     * @maximum 100
     */
    limit?: number;
    /**
     * Use the `endCursor` as a value for the `after` parameter to get the next page.
     */
    after?: string;
    /**
     * Use the `startCursor` as a value for the `before` parameter to get the next page.
     */
    before?: string;
    /**
     * Performs a case-insensitive text search across relevant fields in the collection.
     *
     * **Fields searched depend on the endpoint:**
     * - **Menu items:** `name`, `photoTextDescription`
     * - **Orders:** `customerName`, `id`
     *
     * Returns items where any of the searchable fields contain the search term as a substring.
     */
    search?: string;
} = {}, init: RequestOptions = {}) => client.listOrders({ params }, init);
export const createOrder = (body: Omit<Order, "id" | "object" | "status" | "totalPrice" | "createdAt" | "updatedAt">, init: RequestOptions = {}) => client.createOrder({ body }, init);
export const getOrderById = (orderId: string, headers: {
    /**
     * Optional client-supplied correlation ID, echoed in logs and traces.
     * @format uuid
     */
    "X-Request-Id"?: string;
} = {}, init: RequestOptions = {}) => client.getOrderById({ orderId, headers }, init);
export const deleteOrder = (orderId: string, init: RequestOptions = {}) => client.deleteOrder({ orderId }, init);
export const updateOrder = (orderId: string, body?: {
    status: OrderStatus;
}, init: RequestOptions = {}) => client.updateOrder({ orderId, body }, init);
export const listOrderItems = (params: {
    /**
     * Filters the collection items using space-separated `field:value` pairs.
     *
     * **Format:** `field1:value1 field2:value2`
     *
     * **Supported operators:**
     * - `field:value` - Exact match
     * - `field:value1,value2` - Match any of the comma-separated values (OR)
     * - Time ranges: Use `30d` (30 days), `7d` (7 days), `1h` (1 hour), etc.
     *
     * **Examples:**
     * - `status:placed` - Filter by single status.
     * - `status:placed,completed` - Filter by multiple statuses.
     * - `createdAt:30d` - Filter orders created in the last 30 days.
     * - `orderId:ord_01h1s5z6vf2mm1mz3hevnn9va7` - Filter by specific order ID.
     * - `status:placed createdAt:7d` - Combine multiple filters.
     */
    filter?: string;
} = {}, init: RequestOptions = {}) => client.listOrderItems({ params }, init);
export const getRevenue = (params: {
    /**
     * Start date for the revenue calculation period (ISO 8601 datetime format).
     * Defaults to 30 days ago if not provided.
     * @format date
     */
    startDate?: string;
    /**
     * End date for the revenue calculation period (ISO 8601 datetime format).
     * Defaults to current time if not provided.
     * @format date
     */
    endDate?: string;
} = {}, init: RequestOptions = {}) => client.getRevenue({ params }, init);
export const registerOAuth2Client = (body: RegisterClientObject, init: RequestOptions = {}) => client.registerOAuth2Client({ body }, init);
