// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`E2E lint assertion-string-property-min-length 1`] = `

validating /openapi.yaml...
[1] openapi.yaml:38:21 at #/paths/~1pet~1findByStatus/get/responses/200/content/application~1json/schema/properties/a

minLength assertion failed because the Schema didn't meet the assertions: Required property minLength for type string

36 | properties:
37 |   a:
38 |     type: string
   |     ^^^^^^^^^^^^
39 |     
40 |   b:

Error was generated by the minLength assertion rule.


[2] openapi.yaml:51:25 at #/paths/~1pet~1findByStatus/get/responses/200/content/application~1json/schema/properties/c/properties/k

minLength assertion failed because the Schema didn't meet the assertions: Required property minLength for type string

49 | properties: 
50 |   k:
51 |     type: string       
   |     ^^^^^^^^^^^^

Error was generated by the minLength assertion rule.


/openapi.yaml: validated in <test>ms

❌ Validation failed with 2 errors.
run \`openapi lint --generate-ignore-file\` to add all problems to the ignore file.


`;
