// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`E2E lint assertion-string-property-min-length 1`] = `

validating /openapi.yaml...
[1] openapi.yaml:31:17 at #/paths/~1pet~1findByStatus/get/responses/200/content/application~1json/schema

minLength assertion failed because the Schema didn't meet the assertions: 
- Required property minLength inside a string property
- Required property minLength inside k string property

29 | application/json:
30 |   schema:
31 |     type: object
   |     ^^^^^^^^^^^^
32 |     required: 
   |     ^^^^^^^^^^
 … |     < 20 more lines >
53 |             minLength: 2
   |             ^^^^^^^^^^^^
54 | 

Error was generated by the minLength assertion rule.


/openapi.yaml: validated in <test>ms

❌ Validation failed with 1 error.
run \`openapi lint --generate-ignore-file\` to add all problems to the ignore file.


`;
