// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`E2E lint example-schema-type-oas3.1-error 1`] = `

validating /openapi.yaml...
[1] openapi.yaml:34:21 at #/paths/~1my_post/post/requestBody/content/application~1json/schema/properties/one/example

Example value must conform to the schema: type must be integer,string but got \`array\`.

32 |               - string
33 |             example:
34 |               - test
   |               ^^^^^^
35 | responses:
   | ^
36 |   '200':
37 |     description: My 200 response

referenced from openapi.yaml:29:19

Error was generated by the schema-example-type rule.


/openapi.yaml: validated in <test>ms

❌ Validation failed with 1 error.
run \`openapi lint --generate-ignore-file\` to add all problems to the ignore file.


`;
