import { apiModel, operation } from '../../emitters/__tests__/fixtures.js';
import { getGenerator } from '../index.js';
import { tanstackQueryGenerator } from '../tanstack-query.js';

const SERVICES = [
  {
    name: 'Default',
    operations: [
      operation({ name: 'getPet', method: 'get', path: '/pet' }),
      operation({ name: 'createPet', method: 'post', path: '/pet' }),
    ],
  },
];

describe('tanstackQueryGenerator', () => {
  it('emits one <stem>.tanstack.ts file beside the client with the header + factories', () => {
    const files = tanstackQueryGenerator({
      model: apiModel({ services: SERVICES }),
      outputPath: '/tmp/out/client.ts',
      outputMode: 'single',
      emit: {},
    });
    expect(files).toHaveLength(1);
    expect(files[0].path).toBe('/tmp/out/client.tanstack.ts');
    expect(files[0].content).toContain('// Generated by @redocly/openapi-typescript');
    expect(files[0].content).toContain('import { queryOptions } from "@tanstack/react-query"');
    expect(files[0].content).toContain('export const getPetOptions');
    expect(files[0].content).toContain('export const createPetMutation');
    expect(files[0].content).toContain('from "./client.js"');
  });

  it('emits nothing when the model has no operations', () => {
    const files = tanstackQueryGenerator({
      model: apiModel({ services: [{ name: 'Default', operations: [] }] }),
      outputPath: '/tmp/out/client.ts',
      outputMode: 'single',
      emit: {},
    });
    expect(files).toEqual([]);
  });

  it('passes queryFramework through to the import specifier', () => {
    const files = tanstackQueryGenerator({
      model: apiModel({ services: SERVICES }),
      outputPath: '/tmp/out/client.ts',
      outputMode: 'single',
      emit: { queryFramework: 'svelte' },
    });
    expect(files[0].content).toContain('import { queryOptions } from "@tanstack/svelte-query"');
  });

  it('is registered under "tanstack-query"', () => {
    expect(getGenerator('tanstack-query').run).toBe(tanstackQueryGenerator);
  });
});
