import { apiModel, namedSchema } from '../../emitters/__tests__/fixtures.js';
import { zodGenerator } from '../zod.js';

const PET = namedSchema('Pet', {
  kind: 'object',
  properties: [{ name: 'id', schema: { kind: 'scalar', scalar: 'string' }, required: true }],
});

describe('zodGenerator', () => {
  it('emits one <stem>.zod.ts file beside the client with the header + schemas', () => {
    const files = zodGenerator({
      model: apiModel({ schemas: [PET] }),
      outputPath: '/tmp/out/client.ts',
      outputMode: 'single',
      emit: {},
    });
    expect(files).toHaveLength(1);
    expect(files[0].path).toBe('/tmp/out/client.zod.ts');
    expect(files[0].content).toContain('// Generated by @redocly/openapi-typescript');
    expect(files[0].content).toContain('import { z } from "zod"');
    expect(files[0].content).toContain('export const PetSchema = z.object(');
  });

  it('emits nothing when the model has no schemas', () => {
    const files = zodGenerator({
      model: apiModel({ schemas: [] }),
      outputPath: '/tmp/out/client.ts',
      outputMode: 'single',
      emit: {},
    });
    expect(files).toEqual([]);
  });
});
